# Optimización de Modelos Conjunto Soleado por GMM

In [175]:
#Importaciones
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

#Lectura de datos
datos = pd.read_excel('03_Clusterizacion.xlsx')
datos.head(24)

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,Cluster GMM
0,2022-09-01 00:00:00,0.000000,19,7,77,0,4,15,0,Noche,Noche
1,2022-09-01 01:00:00,0.000000,19,7,82,0,4,16,1,Noche,Noche
2,2022-09-01 02:00:00,0.000000,18,9,85,0,3,16,2,Noche,Noche
3,2022-09-01 03:00:00,0.000000,18,11,87,0,3,16,3,Noche,Noche
4,2022-09-01 04:00:00,0.000000,18,11,88,0,3,16,4,Noche,Noche
5,2022-09-01 05:00:00,0.000000,17,15,86,0,3,14,5,Noche,Noche
6,2022-09-01 06:00:00,0.000000,18,47,89,0,3,16,6,Nublado,Lluvioso
7,2022-09-01 07:00:00,6.584959,18,51,95,0,4,17,7,Nublado,Lluvioso
8,2022-09-01 08:00:00,560.422022,18,47,100,0,3,18,8,Nublado,Lluvioso
9,2022-09-01 09:00:00,7720.582326,18,5,100,1,4,18,9,Nublado,Lluvioso
10,2022-09-01 10:00:00,9433.109309,19,5,93,2,4,18,10,Nublado,Lluvioso
11,2022-09-01 11:00:00,22189.147406,20,5,79,2,4,17,11,Nublado,Lluvioso
12,2022-09-01 12:00:00,29196.986647,22,5,64,6,3,15,12,Nublado,Lluvioso
13,2022-09-01 13:00:00,25478.471342,23,5,51,11,3,13,13,Soleado,Lluvioso
14,2022-09-01 14:00:00,29057.585772,25,3,41,12,1,11,14,Soleado,Lluvioso
15,2022-09-01 15:00:00,30000.000000,26,0,35,11,1,9,15,Soleado,Soleado
16,2022-09-01 16:00:00,28062.328964,27,0,33,8,1,9,16,Soleado,Soleado
17,2022-09-01 17:00:00,28786.629243,28,0,34,5,1,11,17,Soleado,Soleado
18,2022-09-01 18:00:00,29900.303971,27,0,37,3,2,11,18,Soleado,Soleado
19,2022-09-01 19:00:00,18282.505369,26,0,41,2,3,12,19,Soleado,Soleado
20,2022-09-01 20:00:00,3411.083740,24,2,48,0,3,12,20,Nublado,Lluvioso
21,2022-09-01 21:00:00,382.187718,22,6,55,0,3,13,21,Nublado,Lluvioso
22,2022-09-01 22:00:00,0.000000,21,6,61,0,4,13,22,Noche,Noche
23,2022-09-01 23:00:00,0.000000,20,6,68,0,4,14,23,Noche,Noche

In [176]:
datos["Generacion_prev_hour"] = datos["Generación"].shift(1)
datos["Generacion_prev_day"] = datos["Generación"].shift(24)
datos = datos.dropna(how="any", axis= 0)

Definimos X y y

In [ ]:
datos_dia = datos[datos["Cluster GMM"] == "Soleado"].copy()
datos_dia.head(10)

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day
35,2022-09-02 11:00:00,17036.043251,20,0,71,2,2,14,11,Soleado,Nublado,5030.740421,22189.147406
36,2022-09-02 12:00:00,27523.885172,21,0,57,4,2,13,12,Soleado,Nublado,17036.043251,29196.986647
37,2022-09-02 13:00:00,20596.278869,23,0,45,5,2,11,13,Soleado,Soleado,27523.885172,25478.471342
38,2022-09-02 14:00:00,28500.000000,24,3,37,6,2,9,14,Soleado,Lluvioso,20596.278869,29057.585772
64,2022-09-03 16:00:00,23122.803757,25,16,41,6,3,11,16,Soleado,Lluvioso,25500.000000,25500.000000
85,2022-09-04 13:00:00,27000.000000,22,32,58,10,2,13,13,Soleado,Lluvioso,22850.891263,20400.000000
86,2022-09-04 14:00:00,25168.164594,23,25,51,12,1,12,14,Soleado,Lluvioso,27000.000000,21548.984244
87,2022-09-04 15:00:00,24300.000000,23,12,47,10,1,11,15,Soleado,Lluvioso,25168.164594,25500.000000
88,2022-09-04 16:00:00,19686.387416,24,12,46,7,1,12,16,Soleado,Lluvioso,24300.000000,23122.803757
89,2022-09-04 17:00:00,22006.958065,25,12,47,5,1,12,17,Soleado,Lluvioso,19686.387416,25602.778606

In [178]:
columns = datos_dia.drop(columns=["Fecha", "Generación", "Cluster KMeans", "Cluster GMM"]).columns

In [179]:
X = datos_dia[columns]
X

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
35,20,0,71,2,2,14,11,5030.740421,22189.147406
36,21,0,57,4,2,13,12,17036.043251,29196.986647
37,23,0,45,5,2,11,13,27523.885172,25478.471342
38,24,3,37,6,2,9,14,20596.278869,29057.585772
64,25,16,41,6,3,11,16,25500.000000,25500.000000
...,...,...,...,...,...,...,...,...,...
18282,26,0,32,2,1,8,17,25386.000000,22664.000000
18283,25,0,33,1,1,8,18,22872.000000,15736.000000
18284,23,0,38,0,1,8,19,15825.000000,1407.000000
18285,22,0,45,0,1,9,20,1450.000000,0.000000
18286,20,0,54,0,1,10,21,0.000000,0.000000

In [180]:
y = datos_dia[['Generación']]
y

         Generación
35     17036.043251
36     27523.885172
37     20596.278869
38     28500.000000
64     23122.803757
...             ...
18282  22872.000000
18283  15825.000000
18284   1450.000000
18285      0.000000
18286      0.000000

[6962 rows x 1 columns]

Dividimos entrenamiento, validación y prueba

In [181]:
train_size = int(0.7 * len(X))
val_size = int(0.85 * len(X))

In [182]:
# Entrenamiento, validación y prueba, 75, 15 y 15
X_train, y_train =  X.iloc[:train_size, :], y.iloc[:train_size, :]
X_val, y_val = X.iloc[train_size:val_size, :], y.iloc[train_size:val_size, :]
X_test, y_test = X.iloc[val_size:, :],  y.iloc[val_size:,:]

print(f'X_train: {len(X_train)}, y_train: {len(y_train)}')
print(f'X_val: {len(X_val)}, y_val: {len(y_val)}')
print(f'X_test: {len(X_test)}, y_test: {len(y_test)}')

X_train: 4873, y_train: 4873
X_val: 1044, y_val: 1044
X_test: 1045, y_test: 1045

## Escalar con MinMaxScaler

In [183]:
from sklearn.preprocessing import MinMaxScaler

In [184]:
x_scaler = MinMaxScaler().fit(X_train)
x_scaler

MinMaxScaler()

In [185]:
X_train_scaled = x_scaler.transform(X_train)
print(X_train_scaled)
print(X_train_scaled.shape)

[[0.52631579 0.         0.69473684 ... 0.33333333 0.16769135 0.73963825]
 [0.55263158 0.         0.54736842 ... 0.4        0.56786811 0.97323289]
 [0.60526316 0.         0.42105263 ... 0.46666667 0.91746284 0.84928238]
 ...
 [0.21052632 0.         0.48421053 ... 0.06666667 0.         0.        ]
 [0.18421053 0.         0.50526316 ... 0.13333333 0.         0.02536667]
 [0.15789474 0.         0.53684211 ... 0.2        0.01276667 1.        ]]
(4873, 9)

In [186]:
X_train_scaled_df = pd.DataFrame(X_train_scaled, index=X_train.index, columns=X_train.columns)
X_train_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
35,0.526316,0.000000,0.694737,0.142857,0.333333,0.777778,0.333333,0.167691,0.739638
36,0.552632,0.000000,0.547368,0.285714,0.333333,0.722222,0.400000,0.567868,0.973233
37,0.605263,0.000000,0.421053,0.357143,0.333333,0.611111,0.466667,0.917463,0.849282
38,0.631579,0.061224,0.336842,0.428571,0.333333,0.500000,0.533333,0.686543,0.968586
64,0.657895,0.326531,0.378947,0.428571,0.666667,0.611111,0.666667,0.850000,0.850000
...,...,...,...,...,...,...,...,...,...
12570,0.763158,0.000000,0.084211,0.142857,0.666667,0.111111,0.733333,1.000000,1.000000
12583,0.210526,0.000000,0.505263,0.000000,0.000000,0.055556,0.000000,0.000000,0.000000
12584,0.210526,0.000000,0.484211,0.000000,0.000000,0.111111,0.066667,0.000000,0.000000
12585,0.184211,0.000000,0.505263,0.000000,0.333333,0.111111,0.133333,0.000000,0.025367
12586,0.157895,0.000000,0.536842,0.142857,0.333333,0.111111,0.200000,0.012767,1.000000

In [187]:
X_val_scaled = x_scaler.transform(X_val)
print(X_val_scaled)
print(X_val_scaled.shape)

[[0.31578947 0.         0.37894737 ... 0.26666667 0.29363333 1.        ]
 [0.42105263 0.         0.27368421 ... 0.33333333 0.6314     1.        ]
 [0.52631579 0.         0.21052632 ... 0.4        0.67536667 1.        ]
 ...
 [0.92105263 0.         0.14736842 ... 0.6        0.9326     0.97063333]
 [0.94736842 0.         0.11578947 ... 0.66666667 0.97063333 0.95473333]
 [0.97368421 0.         0.10526316 ... 0.73333333 0.95686667 0.8543    ]]
(1044, 9)

In [188]:
X_val_scaled_df = pd.DataFrame(X_val_scaled, index=X_val.index, columns=X_val.columns)
X_val_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
12587,0.315789,0.0,0.378947,0.214286,0.333333,0.055556,0.266667,0.293633,1.000000
12588,0.421053,0.0,0.273684,0.285714,0.333333,0.055556,0.333333,0.631400,1.000000
12589,0.526316,0.0,0.210526,0.357143,0.333333,0.000000,0.400000,0.675367,1.000000
12590,0.605263,0.0,0.178947,0.428571,0.333333,0.055556,0.466667,0.656667,1.000000
12591,0.657895,0.0,0.147368,0.357143,0.333333,0.000000,0.533333,0.713833,1.000000
...,...,...,...,...,...,...,...,...,...
15038,0.842105,0.0,0.210526,1.000000,0.000000,0.555556,0.466667,0.936900,0.928933
15039,0.868421,0.0,0.178947,0.857143,0.000000,0.500000,0.533333,0.928933,0.932600
15040,0.921053,0.0,0.147368,0.642857,0.000000,0.444444,0.600000,0.932600,0.970633
15041,0.947368,0.0,0.115789,0.357143,0.000000,0.388889,0.666667,0.970633,0.954733
15042,0.973684,0.0,0.105263,0.214286,0.333333,0.333333,0.733333,0.956867,0.854300

In [189]:
X_test_scaled = x_scaler.transform(X_test)
print(X_test_scaled)
print(X_test_scaled.shape)

[[0.94736842 0.         0.10526316 ... 0.8        0.85466667 0.71996667]
 [0.92105263 0.         0.11578947 ... 0.86666667 0.72766667 0.2737    ]
 [0.86842105 0.         0.14736842 ... 0.93333333 0.2827     0.0095    ]
 ...
 [0.60526316 0.         0.34736842 ... 0.86666667 0.5275     0.0469    ]
 [0.57894737 0.         0.42105263 ... 0.93333333 0.04833333 0.        ]
 [0.52631579 0.         0.51578947 ... 1.         0.         0.        ]]
(1045, 9)

In [190]:
X_test_scaled_df = pd.DataFrame(X_test_scaled, index=X_test.index, columns=X_test.columns)
X_test_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
15043,0.947368,0.0,0.105263,0.142857,0.333333,0.333333,0.800000,0.854667,0.719967
15044,0.921053,0.0,0.115789,0.071429,0.333333,0.277778,0.866667,0.727667,0.273700
15045,0.868421,0.0,0.147368,0.000000,0.333333,0.388889,0.933333,0.282700,0.009500
15046,0.789474,0.0,0.263158,0.000000,0.000000,0.611111,1.000000,0.010167,0.000000
15055,0.500000,0.0,0.852632,0.000000,0.000000,0.888889,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
18282,0.684211,0.0,0.284211,0.142857,0.000000,0.444444,0.733333,0.846200,0.755467
18283,0.657895,0.0,0.294737,0.071429,0.000000,0.444444,0.800000,0.762400,0.524533
18284,0.605263,0.0,0.347368,0.000000,0.000000,0.444444,0.866667,0.527500,0.046900
18285,0.578947,0.0,0.421053,0.000000,0.000000,0.500000,0.933333,0.048333,0.000000
18286,0.526316,0.0,0.515789,0.000000,0.000000,0.555556,1.000000,0.000000,0.000000

In [191]:
x_scaller_all = MinMaxScaler().fit(X)
print(x_scaller_all)

MinMaxScaler()

In [192]:
X_scaled = x_scaller_all.transform(X)
print(X_scaled)
print(X_scaled.shape)

[[0.51282051 0.         0.70103093 ... 0.33333333 0.16769135 0.73963825]
 [0.53846154 0.         0.55670103 ... 0.4        0.56786811 0.97323289]
 [0.58974359 0.         0.43298969 ... 0.46666667 0.91746284 0.84928238]
 ...
 [0.58974359 0.         0.36082474 ... 0.86666667 0.5275     0.0469    ]
 [0.56410256 0.         0.43298969 ... 0.93333333 0.04833333 0.        ]
 [0.51282051 0.         0.5257732  ... 1.         0.         0.        ]]
(6962, 9)

In [193]:
X_scaled_df = pd.DataFrame(X_scaled, index=X.index, columns=X.columns)
X_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
35,0.512821,0.000000,0.701031,0.142857,0.333333,0.777778,0.333333,0.167691,0.739638
36,0.538462,0.000000,0.556701,0.285714,0.333333,0.722222,0.400000,0.567868,0.973233
37,0.589744,0.000000,0.432990,0.357143,0.333333,0.611111,0.466667,0.917463,0.849282
38,0.615385,0.058824,0.350515,0.428571,0.333333,0.500000,0.533333,0.686543,0.968586
64,0.641026,0.313725,0.391753,0.428571,0.666667,0.611111,0.666667,0.850000,0.850000
...,...,...,...,...,...,...,...,...,...
18282,0.666667,0.000000,0.298969,0.142857,0.000000,0.444444,0.733333,0.846200,0.755467
18283,0.641026,0.000000,0.309278,0.071429,0.000000,0.444444,0.800000,0.762400,0.524533
18284,0.589744,0.000000,0.360825,0.000000,0.000000,0.444444,0.866667,0.527500,0.046900
18285,0.564103,0.000000,0.432990,0.000000,0.000000,0.500000,0.933333,0.048333,0.000000
18286,0.512821,0.000000,0.525773,0.000000,0.000000,0.555556,1.000000,0.000000,0.000000

In [194]:
y_scaler = MinMaxScaler().fit(y_train)
print(y_scaler)

MinMaxScaler()

In [195]:
y_train_scaled = y_scaler.transform(y_train)
print(y_train_scaled)
print(y_train_scaled.shape)

[[0.56786811]
 [0.91746284]
 [0.68654263]
 ...
 [0.        ]
 [0.01276667]
 [0.29363333]]
(4873, 1)

In [196]:
y_train_scaled_df = pd.DataFrame(y_train_scaled, index=y_train.index, columns=y_train.columns)
y_train_scaled_df

       Generación
35       0.567868
36       0.917463
37       0.686543
38       0.950000
64       0.770760
...           ...
12570    1.000000
12583    0.000000
12584    0.000000
12585    0.012767
12586    0.293633

[4873 rows x 1 columns]

In [197]:
y_val_scaled = y_scaler.transform(y_val)
print(y_val_scaled)
print(y_val_scaled.shape)

[[0.6314    ]
 [0.67536667]
 [0.65666667]
 ...
 [0.97063333]
 [0.95686667]
 [0.85466667]]
(1044, 1)

In [198]:
y_val_scaled_df = pd.DataFrame(y_val_scaled, index=y_val.index, columns=y_val.columns)
y_val_scaled_df

       Generación
12587    0.631400
12588    0.675367
12589    0.656667
12590    0.713833
12591    0.627167
...           ...
15038    0.928933
15039    0.932600
15040    0.970633
15041    0.956867
15042    0.854667

[1044 rows x 1 columns]

In [199]:
y_test_scaled = y_scaler.transform(y_test)
print(y_test_scaled)
print(y_test_scaled.shape)

[[0.72766667]
 [0.2827    ]
 [0.01016667]
 ...
 [0.04833333]
 [0.        ]
 [0.        ]]
(1045, 1)

In [200]:
y_test_scaled_df = pd.DataFrame(y_test_scaled, index=y_test.index, columns=y_test.columns)
y_test_scaled_df

       Generación
15043    0.727667
15044    0.282700
15045    0.010167
15046    0.000000
15055    0.000000
...           ...
18282    0.762400
18283    0.527500
18284    0.048333
18285    0.000000
18286    0.000000

[1045 rows x 1 columns]

In [201]:
y_scaller_all = MinMaxScaler().fit(y)
print(y_scaller_all)

MinMaxScaler()

In [202]:
y_scaled = y_scaller_all.transform(y)
print(y_scaled)
print(y_scaled.shape)

[[0.56786811]
 [0.91746284]
 [0.68654263]
 ...
 [0.04833333]
 [0.        ]
 [0.        ]]
(6962, 1)

In [203]:
y_scaled_df = pd.DataFrame(y_scaled, index=y.index, columns=y.columns)
y_scaled_df

       Generación
35       0.567868
36       0.917463
37       0.686543
38       0.950000
64       0.770760
...           ...
18282    0.762400
18283    0.527500
18284    0.048333
18285    0.000000
18286    0.000000

[6962 rows x 1 columns]

## Preparación para Redes Neuronales

In [204]:
import numpy as np
import pandas as pd

def create_sliding_window_with_index(data_X, data_y, lookback):
    X, y, indices = [], [], []
    
    # Asegurar que `data_y` tiene los mismos índices que `data_X`
    data_y = data_y.reindex(data_X.index)

    max_index = len(data_X) - lookback

    for i in range(max_index):
        X.append(data_X.iloc[i:i + lookback].values)  # Ventana de entrada
        
        # Obtener el índice correcto en `data_y`
        y_index = data_X.index[i + lookback]

        # Extraer el valor correspondiente de `data_y`
        if y_index in data_y.index:
            y_value = data_y.loc[y_index]
            if isinstance(y_value, pd.Series):  # Si devuelve una serie, extraer el valor
                y_value = y_value.iloc[0]
        else:
            y_value = np.nan  # Si no está, asignamos NaN

        y.append(y_value)
        indices.append(y_index)  # 🔹 Guardamos el índice original de `data_y`

    # Convertimos `X` en un array y `y` en DataFrame conservando sus índices originales
    X_array = np.array(X)
    y_df = pd.DataFrame(y, index=indices, columns=['y'])  # 🔹 Conservamos los índices originales

    return X_array, y_df

In [205]:
lookback = 48  # Puedes ajustar a 24, 72, etc.

# Aplicar la ventana deslizante a cada conjunto
X_train_windowed, y_train_windowed = create_sliding_window_with_index(X_train_scaled_df, y_train_scaled_df, lookback)
X_val_windowed, y_val_windowed = create_sliding_window_with_index(X_val_scaled_df, y_val_scaled_df, lookback)
X_test_windowed, y_test_windowed = create_sliding_window_with_index(X_test_scaled_df, y_test_scaled_df, lookback)

In [206]:
print(f'X_train: {X_train_windowed.shape}, y_train: {y_train_windowed.shape}')
print(f'X_val: {X_val_windowed.shape}, y_val: {y_val_windowed.shape}')
print(f'X_test: {X_test_windowed.shape}, y_test: {y_test_windowed.shape}')

X_train: (4825, 48, 9), y_train: (4825, 1)
X_val: (996, 48, 9), y_val: (996, 1)
X_test: (997, 48, 9), y_test: (997, 1)

## Optuna

In [207]:
from lightgbm import LGBMRegressor
from sklearn.ensemble import RandomForestRegressor
import optuna
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import seaborn as sns
from sklearn.metrics import mean_absolute_percentage_error as mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error as mean_absolute_error
from sklearn.metrics import mean_squared_error as mean_squared_error
from sklearn.metrics import r2_score as r2_score
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping

### Optimización de LightGBM

In [ ]:
import optuna
import numpy as np
import pandas as pd
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_squared_error

# Definir la función de optimización
def objective(trial):
    # Espacio de búsqueda para los hiperparámetros
    num_leaves = trial.suggest_int('num_leaves', 10, 1000)
    subsample = trial.suggest_float('subsample', 0.1, 1.0)
    colsample_bytree = trial.suggest_float('colsample_bytree', 0.1, 1.0)
    min_data_in_leaf = trial.suggest_int('min_data_in_leaf', 10, 100)

    # Modelo LightGBM con los hiperparámetros sugeridos
    model = LGBMRegressor(
        num_leaves=num_leaves,
        subsample=subsample,
        colsample_bytree=colsample_bytree,
        min_data_in_leaf=min_data_in_leaf,
        random_state=42
    )

    # Entrenamos el modelo con los datos de entrenamiento
    model.fit(X_train_scaled_df, y_train_scaled_df)

    # Predicciones en el conjunto de validación
    y_pred = model.predict(X_val_scaled_df)
    rmse = mean_squared_error(y_val_scaled_df, y_pred)

    return rmse  # Optuna minimizará este valor

# Ejecutar la optimización con 50 iteraciones
LightGBM_study = optuna.create_study(direction="minimize")
LightGBM_study.optimize(objective, n_trials=50)

# Obtener los mejores hiperparámetros
best_params = LightGBM_study.best_params
print("Mejores hiperparámetros:", best_params)

[I 2025-03-12 02:27:09,519] A new study created in memory with name: no-name-b6e1672a-ab53-4b2f-8691-dc8c65f4aa0a
[W 2025-03-12 02:27:09,537] Trial 0 failed with parameters: {'num_leaves': 229, 'subsample': 0.4963396364209546, 'colsample_bytree': 0.5377411730853147, 'min_data_in_leaf': 44} because of the following error: NameError("name 'gpu_support' is not defined").
Traceback (most recent call last):
  File "c:\Users\Claudia\anaconda3\envs\tesina_env\lib\site-packages\optuna\study\_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\Claudia\AppData\Local\Temp\ipykernel_20756\1313049950.py", line 22, in objective
    device= gpu_support
NameError: name 'gpu_support' is not defined
[W 2025-03-12 02:27:09,542] Trial 0 failed with value None.

NameError: name 'gpu_support' is not defined

### Random Forest

In [212]:
def objective(trial):
    # Definir los hiperparámetros a optimizar
    n_estimators = trial.suggest_int("n_estimators", 100, 500, step=50)
    max_depth = trial.suggest_int("max_depth", 10, 50, step=5)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
    min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 10)
    bootstrap = trial.suggest_categorical("bootstrap", [True, False])

    # Definir el modelo con los hiperparámetros actuales
    RF_model = RandomForestRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        bootstrap=bootstrap,
        criterion="squared_error",
        random_state=0
    )

    # Entrenar el modelo
    RF_model.fit(X_train_scaled_df, y_train_scaled_df)

    # Predicciones en el conjunto de validación
    y_pred = RF_model.predict(X_val_scaled_df)
    rmse = mean_squared_error(y_val_scaled_df, y_pred)

    return rmse  # Optuna minimizará este valor

# Crear el estudio de optimización
RF_study = optuna.create_study(direction="minimize")
RF_study.optimize(objective, n_trials=50)  # Ejecutar 50 pruebas

# Imprimir los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", RF_study.best_params)

[I 2025-03-11 19:25:57,467] A new study created in memory with name: no-name-929e11b1-6e85-48ae-adf7-933b9fc550cb
[I 2025-03-11 19:26:13,962] Trial 0 finished with value: 0.011639761189434815 and parameters: {'n_estimators': 300, 'max_depth': 35, 'min_samples_split': 15, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.011639761189434815.
[I 2025-03-11 19:26:24,255] Trial 1 finished with value: 0.009097836418609567 and parameters: {'n_estimators': 250, 'max_depth': 40, 'min_samples_split': 13, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 1 with value: 0.009097836418609567.
[I 2025-03-11 19:26:38,958] Trial 2 finished with value: 0.011574890872546045 and parameters: {'n_estimators': 300, 'max_depth': 25, 'min_samples_split': 18, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 1 with value: 0.009097836418609567.
[I 2025-03-11 19:26:59,495] Trial 3 finished with value: 0.012045692846609326 and parameters: {'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 12, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 1 with value: 0.009097836418609567.
[I 2025-03-11 19:27:11,458] Trial 4 finished with value: 0.006491163196712435 and parameters: {'n_estimators': 400, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 4 with value: 0.006491163196712435.
[I 2025-03-11 19:27:16,542] Trial 5 finished with value: 0.00937884269257088 and parameters: {'n_estimators': 150, 'max_depth': 35, 'min_samples_split': 6, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 4 with value: 0.006491163196712435.
[I 2025-03-11 19:27:23,933] Trial 6 finished with value: 0.006536667515155195 and parameters: {'n_estimators': 200, 'max_depth': 30, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 4 with value: 0.006491163196712435.
[I 2025-03-11 19:27:36,983] Trial 7 finished with value: 0.006492945388673219 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 4 with value: 0.006491163196712435.
[I 2025-03-11 19:27:48,694] Trial 8 finished with value: 0.012132815558260256 and parameters: {'n_estimators': 250, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 4 with value: 0.006491163196712435.
[I 2025-03-11 19:28:03,910] Trial 9 finished with value: 0.00624920669986555 and parameters: {'n_estimators': 500, 'max_depth': 35, 'min_samples_split': 16, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 9 with value: 0.00624920669986555.
[I 2025-03-11 19:28:18,310] Trial 10 finished with value: 0.006199154835991702 and parameters: {'n_estimators': 500, 'max_depth': 50, 'min_samples_split': 20, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 10 with value: 0.006199154835991702.
[I 2025-03-11 19:28:31,848] Trial 11 finished with value: 0.006199154835991702 and parameters: {'n_estimators': 500, 'max_depth': 50, 'min_samples_split': 20, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 10 with value: 0.006199154835991702.
[I 2025-03-11 19:28:43,242] Trial 12 finished with value: 0.006188498742672514 and parameters: {'n_estimators': 400, 'max_depth': 50, 'min_samples_split': 20, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 12 with value: 0.006188498742672514.
[I 2025-03-11 19:28:53,244] Trial 13 finished with value: 0.005975097476711955 and parameters: {'n_estimators': 400, 'max_depth': 50, 'min_samples_split': 20, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 13 with value: 0.005975097476711955.
[I 2025-03-11 19:29:03,437] Trial 14 finished with value: 0.005909366140332638 and parameters: {'n_estimators': 400, 'max_depth': 45, 'min_samples_split': 17, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:29:13,970] Trial 15 finished with value: 0.005909366140332638 and parameters: {'n_estimators': 400, 'max_depth': 45, 'min_samples_split': 16, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:29:24,561] Trial 16 finished with value: 0.00591422565555805 and parameters: {'n_estimators': 350, 'max_depth': 45, 'min_samples_split': 16, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:29:27,512] Trial 17 finished with value: 0.005939700651152661 and parameters: {'n_estimators': 100, 'max_depth': 45, 'min_samples_split': 15, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:29:41,490] Trial 18 finished with value: 0.005949160332617238 and parameters: {'n_estimators': 450, 'max_depth': 40, 'min_samples_split': 13, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:29:52,119] Trial 19 finished with value: 0.006407124980894206 and parameters: {'n_estimators': 350, 'max_depth': 45, 'min_samples_split': 17, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:30:01,433] Trial 20 finished with value: 0.00591422565555805 and parameters: {'n_estimators': 350, 'max_depth': 40, 'min_samples_split': 2, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:30:11,305] Trial 21 finished with value: 0.00591422565555805 and parameters: {'n_estimators': 350, 'max_depth': 45, 'min_samples_split': 18, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:30:25,312] Trial 22 finished with value: 0.006022006789267626 and parameters: {'n_estimators': 450, 'max_depth': 45, 'min_samples_split': 14, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:30:36,744] Trial 23 finished with value: 0.00591771151322701 and parameters: {'n_estimators': 450, 'max_depth': 40, 'min_samples_split': 17, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:30:47,069] Trial 24 finished with value: 0.006032772701976291 and parameters: {'n_estimators': 350, 'max_depth': 45, 'min_samples_split': 11, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:30:53,532] Trial 25 finished with value: 0.005964572088818023 and parameters: {'n_estimators': 250, 'max_depth': 30, 'min_samples_split': 18, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:31:01,375] Trial 26 finished with value: 0.005939140150995346 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 16, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:31:14,994] Trial 27 finished with value: 0.005949160332617238 and parameters: {'n_estimators': 450, 'max_depth': 40, 'min_samples_split': 14, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:31:27,123] Trial 28 finished with value: 0.006015110401442607 and parameters: {'n_estimators': 400, 'max_depth': 50, 'min_samples_split': 16, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:31:38,799] Trial 29 finished with value: 0.008981962948268484 and parameters: {'n_estimators': 300, 'max_depth': 35, 'min_samples_split': 15, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:31:52,479] Trial 30 finished with value: 0.006503443851754231 and parameters: {'n_estimators': 350, 'max_depth': 45, 'min_samples_split': 18, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:32:02,057] Trial 31 finished with value: 0.00591422565555805 and parameters: {'n_estimators': 350, 'max_depth': 40, 'min_samples_split': 2, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:32:08,573] Trial 32 finished with value: 0.005931616463499416 and parameters: {'n_estimators': 300, 'max_depth': 40, 'min_samples_split': 8, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:32:18,390] Trial 33 finished with value: 0.005933135718562704 and parameters: {'n_estimators': 350, 'max_depth': 45, 'min_samples_split': 5, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:32:33,842] Trial 34 finished with value: 0.008944067078981153 and parameters: {'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 12, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:32:48,003] Trial 35 finished with value: 0.006022006789267626 and parameters: {'n_estimators': 450, 'max_depth': 40, 'min_samples_split': 13, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:33:02,172] Trial 36 finished with value: 0.009381338263348336 and parameters: {'n_estimators': 400, 'max_depth': 25, 'min_samples_split': 19, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:33:12,185] Trial 37 finished with value: 0.00591422565555805 and parameters: {'n_estimators': 350, 'max_depth': 50, 'min_samples_split': 2, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:33:22,416] Trial 38 finished with value: 0.009379073485832997 and parameters: {'n_estimators': 250, 'max_depth': 45, 'min_samples_split': 11, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:33:29,623] Trial 39 finished with value: 0.006644316939740039 and parameters: {'n_estimators': 200, 'max_depth': 35, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:33:38,260] Trial 40 finished with value: 0.006078706068192773 and parameters: {'n_estimators': 300, 'max_depth': 30, 'min_samples_split': 14, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:33:46,719] Trial 41 finished with value: 0.00591422565555805 and parameters: {'n_estimators': 350, 'max_depth': 45, 'min_samples_split': 17, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:33:57,459] Trial 42 finished with value: 0.005909366140332638 and parameters: {'n_estimators': 400, 'max_depth': 45, 'min_samples_split': 19, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:34:08,984] Trial 43 finished with value: 0.005953360513848792 and parameters: {'n_estimators': 400, 'max_depth': 40, 'min_samples_split': 19, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:34:21,677] Trial 44 finished with value: 0.00591771151322701 and parameters: {'n_estimators': 450, 'max_depth': 50, 'min_samples_split': 19, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:34:33,109] Trial 45 finished with value: 0.0059345467321373175 and parameters: {'n_estimators': 400, 'max_depth': 40, 'min_samples_split': 15, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:34:44,408] Trial 46 finished with value: 0.008944067078981162 and parameters: {'n_estimators': 300, 'max_depth': 50, 'min_samples_split': 7, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:34:55,716] Trial 47 finished with value: 0.006118325561790227 and parameters: {'n_estimators': 400, 'max_depth': 45, 'min_samples_split': 17, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:35:06,698] Trial 48 finished with value: 0.006018363877889595 and parameters: {'n_estimators': 400, 'max_depth': 15, 'min_samples_split': 16, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.
[I 2025-03-11 19:35:16,493] Trial 49 finished with value: 0.005933135718562704 and parameters: {'n_estimators': 350, 'max_depth': 45, 'min_samples_split': 5, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 14 with value: 0.005909366140332638.

Mejores hiperparámetros: {'n_estimators': 400, 'max_depth': 45, 'min_samples_split': 17, 'min_samples_leaf': 10, 'bootstrap': True}

### CTNET

In [213]:
def compile_and_fit(model, xtrain=X_train_windowed, ytrain=y_train_windowed, learning_rate=0.0001):
    model.compile(loss=[tf.keras.losses.MeanSquaredError()],
                  optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                  metrics=[tf.keras.metrics.RootMeanSquaredError(), tf.keras.metrics.MeanAbsolutePercentageError(), tf.keras.metrics.MeanAbsoluteError()])
    
    history = model.fit(xtrain, ytrain, epochs=50,
                        batch_size=512, validation_split=0.2, verbose=1)
    return history

def Loss(train_loss, valid_loss):
    plt.plot(train_loss)
    plt.plot(valid_loss)
    plt.rcParams["figure.figsize"] = (15, 3)
    plt.title('Model Losses')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(['Train Loss', 'Validation Loss'], loc='upper left')
    plt.savefig('out/loss_plot.png')
    plt.show()

def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    x = layers.LayerNormalization()(inputs)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=128, kernel_size=2, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(norm_x, norm_x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    return norm_x

# Construir modelo con hiperparámetros sugeridos
def build_model(input_shape, head_size, num_heads, ff_dim, num_transformer_blocks, mlp_units, dropout, mlp_dropout):
    inputs = tf.keras.Input(shape=input_shape)
    x = inputs

    for _ in range(num_transformer_blocks):
        x = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)

    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(x, x)
    x = layers.LayerNormalization(epsilon=1e-6)(x)
    x = layers.GlobalAveragePooling1D(data_format="channels_first")(x)
    
    for units in mlp_units:
        x = layers.Dense(units, activation="relu")(x)

    x = layers.Dropout(mlp_dropout)(x)
    outputs = layers.Dense(1)(x)
    return tf.keras.Model(inputs, outputs)

In [214]:
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [215]:
# Definir la función objetivo para Optuna
def objective(trial):
    # Hiperparámetros a optimizar
    head_size = trial.suggest_int("head_size", 2, 8)
    num_heads = trial.suggest_int("num_heads", 2, 8)
    ff_dim = trial.suggest_int("ff_dim", 16, 128, step=16)
    num_transformer_blocks = trial.suggest_int("num_transformer_blocks", 1, 5)
    mlp_units = [trial.suggest_int("mlp_units_1", 64, 512, step=64),
                 trial.suggest_int("mlp_units_2", 32, 256, step=32)]
    dropout = trial.suggest_float("dropout", 0.1, 0.5)
    mlp_dropout = trial.suggest_float("mlp_dropout", 0.1, 0.5)
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-5, 1e-2)
    batch_size = trial.suggest_categorical("batch_size", [128, 256, 512])

    # Construir el modelo
    model = build_model(
        input_shape=(X_train_windowed.shape[1], X_train_windowed.shape[2]),
        head_size=head_size,
        num_heads=num_heads,
        ff_dim=ff_dim,
        num_transformer_blocks=num_transformer_blocks,
        mlp_units=mlp_units,
        dropout=dropout,
        mlp_dropout=mlp_dropout
    )

    # Compilar y entrenar el modelo
    model.compile(
        loss=tf.keras.losses.MeanSquaredError(),
        optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
        metrics=[tf.keras.metrics.RootMeanSquaredError()]
    )

    history = model.fit(
        X_train_windowed, y_train_windowed,
        epochs=100,  # Se puede detener antes con Early Stopping
        batch_size=batch_size,  # 🔹 Batch size optimizado
        validation_data=(X_val_windowed, y_val_windowed),  # 🔹 Validación en cada época
        callbacks=[early_stop],  # 🔹 Early Stopping activado
        verbose=0
    )

    # Obtener pérdida de validación
    val_loss = min(history.history['val_loss'])
    return val_loss  # Minimizar MSE

# Crear el estudio de optimización
CTNET_study = optuna.create_study(direction="minimize")
CTNET_study.optimize(objective, n_trials=50)  # Ejecutar 50 pruebas

# Imprimir los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", CTNET_study.best_params)

[I 2025-03-11 19:35:38,750] A new study created in memory with name: no-name-49fbce82-cf33-4436-b2f8-44cb7b02117d
[I 2025-03-11 20:01:56,672] Trial 0 finished with value: 0.11877622455358505 and parameters: {'head_size': 4, 'num_heads': 8, 'ff_dim': 112, 'num_transformer_blocks': 4, 'mlp_units_1': 320, 'mlp_units_2': 160, 'dropout': 0.23262113635016815, 'mlp_dropout': 0.25004517288331674, 'learning_rate': 2.00581114844137e-05, 'batch_size': 512}. Best is trial 0 with value: 0.11877622455358505.
[I 2025-03-11 20:23:06,728] Trial 1 finished with value: 0.04681694507598877 and parameters: {'head_size': 6, 'num_heads': 7, 'ff_dim': 80, 'num_transformer_blocks': 2, 'mlp_units_1': 448, 'mlp_units_2': 256, 'dropout': 0.303020430244923, 'mlp_dropout': 0.2502938239162138, 'learning_rate': 0.00013214377235462986, 'batch_size': 512}. Best is trial 1 with value: 0.04681694507598877.
[I 2025-03-11 20:38:52,645] Trial 2 finished with value: 0.03452784940600395 and parameters: {'head_size': 5, 'num_heads': 6, 'ff_dim': 16, 'num_transformer_blocks': 4, 'mlp_units_1': 64, 'mlp_units_2': 192, 'dropout': 0.11616866288377214, 'mlp_dropout': 0.11247631466893426, 'learning_rate': 0.0004369218288917723, 'batch_size': 128}. Best is trial 2 with value: 0.03452784940600395.
[I 2025-03-11 20:44:59,585] Trial 3 finished with value: 0.031200017780065536 and parameters: {'head_size': 7, 'num_heads': 5, 'ff_dim': 128, 'num_transformer_blocks': 1, 'mlp_units_1': 512, 'mlp_units_2': 256, 'dropout': 0.38965289888031873, 'mlp_dropout': 0.3425459551978468, 'learning_rate': 0.000853659338701806, 'batch_size': 512}. Best is trial 3 with value: 0.031200017780065536.
[I 2025-03-11 20:53:58,948] Trial 4 finished with value: 0.030530918389558792 and parameters: {'head_size': 5, 'num_heads': 2, 'ff_dim': 64, 'num_transformer_blocks': 5, 'mlp_units_1': 192, 'mlp_units_2': 160, 'dropout': 0.23975231510462278, 'mlp_dropout': 0.3753064338211318, 'learning_rate': 0.0016792045350040906, 'batch_size': 256}. Best is trial 4 with value: 0.030530918389558792.
[I 2025-03-11 21:06:12,832] Trial 5 finished with value: 0.03222144395112991 and parameters: {'head_size': 2, 'num_heads': 6, 'ff_dim': 80, 'num_transformer_blocks': 4, 'mlp_units_1': 320, 'mlp_units_2': 32, 'dropout': 0.11981302723101997, 'mlp_dropout': 0.2393945138730394, 'learning_rate': 0.0005323070447903761, 'batch_size': 512}. Best is trial 4 with value: 0.030530918389558792.
[I 2025-03-11 21:09:03,172] Trial 6 finished with value: 0.0337170846760273 and parameters: {'head_size': 2, 'num_heads': 8, 'ff_dim': 128, 'num_transformer_blocks': 1, 'mlp_units_1': 512, 'mlp_units_2': 128, 'dropout': 0.4567460516845535, 'mlp_dropout': 0.18864289805348028, 'learning_rate': 0.0006958832612018453, 'batch_size': 256}. Best is trial 4 with value: 0.030530918389558792.
[I 2025-03-11 21:12:59,703] Trial 7 finished with value: 0.02969619259238243 and parameters: {'head_size': 4, 'num_heads': 3, 'ff_dim': 128, 'num_transformer_blocks': 3, 'mlp_units_1': 128, 'mlp_units_2': 256, 'dropout': 0.44233071819154957, 'mlp_dropout': 0.17354975512635756, 'learning_rate': 0.0032640272337305233, 'batch_size': 256}. Best is trial 7 with value: 0.02969619259238243.
[I 2025-03-11 21:16:06,679] Trial 8 finished with value: 0.028935639187693596 and parameters: {'head_size': 5, 'num_heads': 4, 'ff_dim': 48, 'num_transformer_blocks': 2, 'mlp_units_1': 320, 'mlp_units_2': 64, 'dropout': 0.44251714327454816, 'mlp_dropout': 0.2868310872821115, 'learning_rate': 0.006424582647113729, 'batch_size': 256}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 21:35:40,543] Trial 9 finished with value: 0.031992822885513306 and parameters: {'head_size': 7, 'num_heads': 7, 'ff_dim': 48, 'num_transformer_blocks': 4, 'mlp_units_1': 448, 'mlp_units_2': 160, 'dropout': 0.4456334804510038, 'mlp_dropout': 0.24245572199697885, 'learning_rate': 0.0007970557312392554, 'batch_size': 512}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 21:39:41,305] Trial 10 finished with value: 0.1266993135213852 and parameters: {'head_size': 8, 'num_heads': 4, 'ff_dim': 16, 'num_transformer_blocks': 2, 'mlp_units_1': 256, 'mlp_units_2': 32, 'dropout': 0.36897898704524207, 'mlp_dropout': 0.4808651633597463, 'learning_rate': 0.009724000132559625, 'batch_size': 128}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 21:41:36,492] Trial 11 finished with value: 0.06329359859228134 and parameters: {'head_size': 4, 'num_heads': 3, 'ff_dim': 48, 'num_transformer_blocks': 2, 'mlp_units_1': 64, 'mlp_units_2': 96, 'dropout': 0.49322510317332946, 'mlp_dropout': 0.12062617702788324, 'learning_rate': 0.009772666265227378, 'batch_size': 256}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 21:48:26,201] Trial 12 finished with value: 0.029095087200403214 and parameters: {'head_size': 4, 'num_heads': 3, 'ff_dim': 96, 'num_transformer_blocks': 3, 'mlp_units_1': 192, 'mlp_units_2': 96, 'dropout': 0.38436064273943094, 'mlp_dropout': 0.4089486295186419, 'learning_rate': 0.0033014924070011004, 'batch_size': 256}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 21:53:44,370] Trial 13 finished with value: 0.029095204547047615 and parameters: {'head_size': 3, 'num_heads': 4, 'ff_dim': 96, 'num_transformer_blocks': 3, 'mlp_units_1': 256, 'mlp_units_2': 96, 'dropout': 0.3620019977272142, 'mlp_dropout': 0.4160918374155367, 'learning_rate': 0.0033651549315207147, 'batch_size': 256}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 22:02:42,976] Trial 14 finished with value: 0.03613971918821335 and parameters: {'head_size': 6, 'num_heads': 2, 'ff_dim': 48, 'num_transformer_blocks': 3, 'mlp_units_1': 384, 'mlp_units_2': 64, 'dropout': 0.31354378995519805, 'mlp_dropout': 0.4564026558345695, 'learning_rate': 0.00015388272378643217, 'batch_size': 256}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 22:05:48,884] Trial 15 finished with value: 0.03153841570019722 and parameters: {'head_size': 3, 'num_heads': 4, 'ff_dim': 96, 'num_transformer_blocks': 2, 'mlp_units_1': 192, 'mlp_units_2': 96, 'dropout': 0.41177673166370743, 'mlp_dropout': 0.3250843369107102, 'learning_rate': 0.003225908325330741, 'batch_size': 256}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 22:14:15,089] Trial 16 finished with value: 0.12210317701101303 and parameters: {'head_size': 6, 'num_heads': 3, 'ff_dim': 32, 'num_transformer_blocks': 3, 'mlp_units_1': 192, 'mlp_units_2': 64, 'dropout': 0.35364185715554475, 'mlp_dropout': 0.3938331795211749, 'learning_rate': 1.7259768579931474e-05, 'batch_size': 256}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 22:17:27,908] Trial 17 finished with value: 0.02901841700077057 and parameters: {'head_size': 3, 'num_heads': 5, 'ff_dim': 64, 'num_transformer_blocks': 1, 'mlp_units_1': 384, 'mlp_units_2': 64, 'dropout': 0.4972454668779291, 'mlp_dropout': 0.3034344023201412, 'learning_rate': 0.005140309193884365, 'batch_size': 128}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 22:23:50,684] Trial 18 finished with value: 0.03495534136891365 and parameters: {'head_size': 3, 'num_heads': 5, 'ff_dim': 64, 'num_transformer_blocks': 1, 'mlp_units_1': 384, 'mlp_units_2': 64, 'dropout': 0.4989417092578515, 'mlp_dropout': 0.2924277149311895, 'learning_rate': 6.665949574185025e-05, 'batch_size': 128}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 22:26:20,664] Trial 19 finished with value: 0.030192948877811432 and parameters: {'head_size': 5, 'num_heads': 5, 'ff_dim': 32, 'num_transformer_blocks': 1, 'mlp_units_1': 384, 'mlp_units_2': 32, 'dropout': 0.24703930151263057, 'mlp_dropout': 0.2948392683116782, 'learning_rate': 0.0016539792763439717, 'batch_size': 128}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 22:31:07,920] Trial 20 finished with value: 0.0384935587644577 and parameters: {'head_size': 2, 'num_heads': 6, 'ff_dim': 64, 'num_transformer_blocks': 2, 'mlp_units_1': 320, 'mlp_units_2': 128, 'dropout': 0.47092481041332895, 'mlp_dropout': 0.3487619742954395, 'learning_rate': 0.006826533404320423, 'batch_size': 128}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 22:34:14,948] Trial 21 finished with value: 0.030505700036883354 and parameters: {'head_size': 4, 'num_heads': 4, 'ff_dim': 96, 'num_transformer_blocks': 2, 'mlp_units_1': 256, 'mlp_units_2': 64, 'dropout': 0.4205378129374282, 'mlp_dropout': 0.4274738436645318, 'learning_rate': 0.0040449398285303225, 'batch_size': 128}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 22:36:51,351] Trial 22 finished with value: 0.029782205820083618 and parameters: {'head_size': 3, 'num_heads': 3, 'ff_dim': 80, 'num_transformer_blocks': 1, 'mlp_units_1': 128, 'mlp_units_2': 96, 'dropout': 0.40052942467215225, 'mlp_dropout': 0.2880284888944907, 'learning_rate': 0.0015291169102217466, 'batch_size': 256}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 22:42:00,230] Trial 23 finished with value: 0.02915973775088787 and parameters: {'head_size': 4, 'num_heads': 5, 'ff_dim': 32, 'num_transformer_blocks': 2, 'mlp_units_1': 448, 'mlp_units_2': 64, 'dropout': 0.327237599415722, 'mlp_dropout': 0.19810130472306337, 'learning_rate': 0.0052328462086973886, 'batch_size': 256}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 22:44:57,641] Trial 24 finished with value: 0.03472818434238434 and parameters: {'head_size': 5, 'num_heads': 4, 'ff_dim': 112, 'num_transformer_blocks': 1, 'mlp_units_1': 384, 'mlp_units_2': 128, 'dropout': 0.4334621150441284, 'mlp_dropout': 0.3668312066616075, 'learning_rate': 0.0017151680367262301, 'batch_size': 128}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 22:48:22,498] Trial 25 finished with value: 0.030760236084461212 and parameters: {'head_size': 3, 'num_heads': 2, 'ff_dim': 48, 'num_transformer_blocks': 3, 'mlp_units_1': 320, 'mlp_units_2': 96, 'dropout': 0.48119817855985575, 'mlp_dropout': 0.4445046560952858, 'learning_rate': 0.005665595521153265, 'batch_size': 256}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 22:56:00,840] Trial 26 finished with value: 0.030003972351551056 and parameters: {'head_size': 4, 'num_heads': 3, 'ff_dim': 64, 'num_transformer_blocks': 5, 'mlp_units_1': 128, 'mlp_units_2': 32, 'dropout': 0.3861800341881313, 'mlp_dropout': 0.4983558536345986, 'learning_rate': 0.0029795428832919742, 'batch_size': 128}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 23:02:44,352] Trial 27 finished with value: 0.03140317648649216 and parameters: {'head_size': 5, 'num_heads': 4, 'ff_dim': 80, 'num_transformer_blocks': 2, 'mlp_units_1': 256, 'mlp_units_2': 64, 'dropout': 0.4623675564065083, 'mlp_dropout': 0.3235037742986381, 'learning_rate': 0.0002790704994065031, 'batch_size': 256}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 23:08:41,106] Trial 28 finished with value: 0.12536336481571198 and parameters: {'head_size': 3, 'num_heads': 5, 'ff_dim': 112, 'num_transformer_blocks': 3, 'mlp_units_1': 192, 'mlp_units_2': 192, 'dropout': 0.3416057830292657, 'mlp_dropout': 0.40045460861278664, 'learning_rate': 0.009332009823387784, 'batch_size': 128}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 23:19:43,158] Trial 29 finished with value: 0.10589521378278732 and parameters: {'head_size': 4, 'num_heads': 3, 'ff_dim': 96, 'num_transformer_blocks': 4, 'mlp_units_1': 320, 'mlp_units_2': 128, 'dropout': 0.2739571009909508, 'mlp_dropout': 0.26883971679825946, 'learning_rate': 4.196556729365282e-05, 'batch_size': 256}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 23:27:46,781] Trial 30 finished with value: 0.030610566958785057 and parameters: {'head_size': 6, 'num_heads': 7, 'ff_dim': 112, 'num_transformer_blocks': 1, 'mlp_units_1': 384, 'mlp_units_2': 96, 'dropout': 0.4225252583860204, 'mlp_dropout': 0.3223639141795909, 'learning_rate': 0.0011466519731571261, 'batch_size': 512}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 23:33:58,406] Trial 31 finished with value: 0.029036084190011024 and parameters: {'head_size': 3, 'num_heads': 4, 'ff_dim': 96, 'num_transformer_blocks': 3, 'mlp_units_1': 256, 'mlp_units_2': 96, 'dropout': 0.16946779147793242, 'mlp_dropout': 0.41430279942224313, 'learning_rate': 0.0032393299277406118, 'batch_size': 256}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-11 23:52:41,519] Trial 32 finished with value: 0.11394712328910828 and parameters: {'head_size': 2, 'num_heads': 4, 'ff_dim': 80, 'num_transformer_blocks': 3, 'mlp_units_1': 256, 'mlp_units_2': 64, 'dropout': 0.1928550347512522, 'mlp_dropout': 0.4585405171826632, 'learning_rate': 1.1078553611077053e-05, 'batch_size': 256}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-12 00:02:00,402] Trial 33 finished with value: 0.03023068606853485 and parameters: {'head_size': 4, 'num_heads': 6, 'ff_dim': 96, 'num_transformer_blocks': 3, 'mlp_units_1': 320, 'mlp_units_2': 96, 'dropout': 0.17956256389167774, 'mlp_dropout': 0.21057509502901914, 'learning_rate': 0.002399912958873533, 'batch_size': 256}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-12 00:11:21,738] Trial 34 finished with value: 0.03054242767393589 and parameters: {'head_size': 3, 'num_heads': 4, 'ff_dim': 64, 'num_transformer_blocks': 4, 'mlp_units_1': 448, 'mlp_units_2': 32, 'dropout': 0.1607740179560963, 'mlp_dropout': 0.3753911410344086, 'learning_rate': 0.005142142699184266, 'batch_size': 256}. Best is trial 8 with value: 0.028935639187693596.
[I 2025-03-12 00:19:43,447] Trial 35 finished with value: 0.02839106135070324 and parameters: {'head_size': 5, 'num_heads': 5, 'ff_dim': 112, 'num_transformer_blocks': 2, 'mlp_units_1': 192, 'mlp_units_2': 128, 'dropout': 0.2933459854281062, 'mlp_dropout': 0.3522227742199008, 'learning_rate': 0.002180590014884393, 'batch_size': 512}. Best is trial 35 with value: 0.02839106135070324.
[I 2025-03-12 00:26:00,009] Trial 36 finished with value: 0.030107660219073296 and parameters: {'head_size': 7, 'num_heads': 5, 'ff_dim': 112, 'num_transformer_blocks': 2, 'mlp_units_1': 256, 'mlp_units_2': 160, 'dropout': 0.27044910449092197, 'mlp_dropout': 0.2621035302426435, 'learning_rate': 0.0021497777720050266, 'batch_size': 512}. Best is trial 35 with value: 0.02839106135070324.
[I 2025-03-12 00:32:52,916] Trial 37 finished with value: 0.03142198547720909 and parameters: {'head_size': 5, 'num_heads': 6, 'ff_dim': 112, 'num_transformer_blocks': 1, 'mlp_units_1': 320, 'mlp_units_2': 224, 'dropout': 0.1347323166908033, 'mlp_dropout': 0.3527818283673989, 'learning_rate': 0.0011603727558025451, 'batch_size': 512}. Best is trial 35 with value: 0.02839106135070324.
[I 2025-03-12 00:55:05,943] Trial 38 finished with value: 0.03411335125565529 and parameters: {'head_size': 6, 'num_heads': 6, 'ff_dim': 128, 'num_transformer_blocks': 2, 'mlp_units_1': 192, 'mlp_units_2': 128, 'dropout': 0.21417063499139719, 'mlp_dropout': 0.22292398617104447, 'learning_rate': 0.0003132011403688856, 'batch_size': 512}. Best is trial 35 with value: 0.02839106135070324.
[I 2025-03-12 01:05:25,337] Trial 39 finished with value: 0.030625879764556885 and parameters: {'head_size': 8, 'num_heads': 5, 'ff_dim': 48, 'num_transformer_blocks': 2, 'mlp_units_1': 512, 'mlp_units_2': 160, 'dropout': 0.29239154492670744, 'mlp_dropout': 0.31702833945419495, 'learning_rate': 0.0005019039832567045, 'batch_size': 512}. Best is trial 35 with value: 0.02839106135070324.
[I 2025-03-12 01:09:57,151] Trial 40 finished with value: 0.02951359562575817 and parameters: {'head_size': 2, 'num_heads': 7, 'ff_dim': 64, 'num_transformer_blocks': 1, 'mlp_units_1': 448, 'mlp_units_2': 192, 'dropout': 0.1045562525969402, 'mlp_dropout': 0.2755329259519199, 'learning_rate': 0.006138019804798145, 'batch_size': 512}. Best is trial 35 with value: 0.02839106135070324.
[I 2025-03-12 01:16:04,146] Trial 41 finished with value: 0.029776914045214653 and parameters: {'head_size': 5, 'num_heads': 4, 'ff_dim': 80, 'num_transformer_blocks': 3, 'mlp_units_1': 192, 'mlp_units_2': 128, 'dropout': 0.3819409433283779, 'mlp_dropout': 0.37188933166951943, 'learning_rate': 0.002459243191301529, 'batch_size': 256}. Best is trial 35 with value: 0.02839106135070324.
[I 2025-03-12 01:25:22,610] Trial 42 finished with value: 0.03116985410451889 and parameters: {'head_size': 4, 'num_heads': 5, 'ff_dim': 96, 'num_transformer_blocks': 4, 'mlp_units_1': 128, 'mlp_units_2': 96, 'dropout': 0.4536887092019561, 'mlp_dropout': 0.42503655628809284, 'learning_rate': 0.003950231025949111, 'batch_size': 512}. Best is trial 35 with value: 0.02839106135070324.
[I 2025-03-12 01:29:23,668] Trial 43 finished with value: 0.04509191960096359 and parameters: {'head_size': 5, 'num_heads': 3, 'ff_dim': 112, 'num_transformer_blocks': 3, 'mlp_units_1': 64, 'mlp_units_2': 64, 'dropout': 0.47751253092441504, 'mlp_dropout': 0.396621978488132, 'learning_rate': 0.007697542079573137, 'batch_size': 256}. Best is trial 35 with value: 0.02839106135070324.
[I 2025-03-12 01:33:48,950] Trial 44 finished with value: 0.042382024228572845 and parameters: {'head_size': 4, 'num_heads': 2, 'ff_dim': 96, 'num_transformer_blocks': 2, 'mlp_units_1': 192, 'mlp_units_2': 96, 'dropout': 0.21530397409013324, 'mlp_dropout': 0.34070777928317936, 'learning_rate': 0.0044699336632103015, 'batch_size': 128}. Best is trial 35 with value: 0.02839106135070324.
[I 2025-03-12 01:43:46,387] Trial 45 finished with value: 0.031117362901568413 and parameters: {'head_size': 3, 'num_heads': 4, 'ff_dim': 128, 'num_transformer_blocks': 4, 'mlp_units_1': 256, 'mlp_units_2': 128, 'dropout': 0.4380749728425086, 'mlp_dropout': 0.3858125179821881, 'learning_rate': 0.001195521332887574, 'batch_size': 256}. Best is trial 35 with value: 0.02839106135070324.
[I 2025-03-12 01:59:26,621] Trial 46 finished with value: 0.029919784516096115 and parameters: {'head_size': 6, 'num_heads': 5, 'ff_dim': 48, 'num_transformer_blocks': 5, 'mlp_units_1': 128, 'mlp_units_2': 96, 'dropout': 0.14915052761898084, 'mlp_dropout': 0.4122595445230069, 'learning_rate': 0.002132326666499074, 'batch_size': 256}. Best is trial 35 with value: 0.02839106135070324.
[I 2025-03-12 02:03:30,564] Trial 47 finished with value: 0.041861340403556824 and parameters: {'head_size': 5, 'num_heads': 3, 'ff_dim': 80, 'num_transformer_blocks': 2, 'mlp_units_1': 256, 'mlp_units_2': 32, 'dropout': 0.30546609313289846, 'mlp_dropout': 0.24495425349689604, 'learning_rate': 0.007338266004041235, 'batch_size': 512}. Best is trial 35 with value: 0.02839106135070324.
[I 2025-03-12 02:20:40,796] Trial 48 finished with value: 0.034356288611888885 and parameters: {'head_size': 3, 'num_heads': 8, 'ff_dim': 16, 'num_transformer_blocks': 4, 'mlp_units_1': 320, 'mlp_units_2': 64, 'dropout': 0.260223387574575, 'mlp_dropout': 0.3067440450588247, 'learning_rate': 0.0008696915590316849, 'batch_size': 256}. Best is trial 35 with value: 0.02839106135070324.
[I 2025-03-12 02:27:08,752] Trial 49 finished with value: 0.034317802637815475 and parameters: {'head_size': 2, 'num_heads': 4, 'ff_dim': 32, 'num_transformer_blocks': 3, 'mlp_units_1': 192, 'mlp_units_2': 160, 'dropout': 0.39990779964896, 'mlp_dropout': 0.15980307136486463, 'learning_rate': 0.0028306248266396715, 'batch_size': 128}. Best is trial 35 with value: 0.02839106135070324.

Mejores hiperparámetros: {'head_size': 5, 'num_heads': 5, 'ff_dim': 112, 'num_transformer_blocks': 2, 'mlp_units_1': 192, 'mlp_units_2': 128, 'dropout': 0.2933459854281062, 'mlp_dropout': 0.3522227742199008, 'learning_rate': 0.002180590014884393, 'batch_size': 512}

### Forescasting

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer, Conv1D, BatchNormalization, MaxPooling1D, Bidirectional, LSTM, Dropout, Dense
from tensorflow.keras.optimizers import Adam

# Definir la función objetivo para Optuna
def objective(trial):
    # Hiperparámetros a optimizar
    filters = trial.suggest_categorical("filters", [32, 64, 128])
    kernel_size = trial.suggest_int("kernel_size", 2, 5)
    lstm_units_1 = trial.suggest_categorical("lstm_units_1", [64, 128, 256])
    lstm_units_2 = trial.suggest_categorical("lstm_units_2", [32, 64, 128])
    lstm_units_3 = trial.suggest_categorical("lstm_units_3", [16, 32, 64])
    dropout_lstm = trial.suggest_float("dropout_lstm", 0.1, 0.5)
    dropout_dense = trial.suggest_float("dropout_dense", 0.1, 0.5)
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-4, 1e-2)
    batch_size = trial.suggest_categorical("batch_size", [128, 256, 512])  # 🔹 Optimización del batch size

    # Construcción del modelo
    model = Sequential()
    model.add(InputLayer((X_train_windowed.shape[1], X_train_windowed.shape[2])))

    # CNN
    model.add(Conv1D(filters=filters, kernel_size=kernel_size, padding='same', activation='relu'))
    model.add(BatchNormalization())  
    model.add(MaxPooling1D(pool_size=2))

    # BiLSTM
    model.add(Bidirectional(LSTM(lstm_units_1, return_sequences=True)))
    model.add(Bidirectional(LSTM(lstm_units_2, return_sequences=True)))
    model.add(Dropout(dropout_lstm))
    model.add(Bidirectional(LSTM(lstm_units_3, return_sequences=False)))

    # Normalización y Dropout
    model.add(BatchNormalization())
    model.add(Dropout(dropout_dense))

    # Capas Densas
    model.add(Dense(16, activation='relu'))
    model.add(Dense(1, activation='relu'))

    # Compilar el modelo
    model.compile(
        loss=tf.keras.losses.MeanSquaredError(),
        optimizer=Adam(learning_rate=learning_rate),
        metrics=[tf.keras.metrics.RootMeanSquaredError()]
    )

    # Entrenar el modelo con validación
    history = model.fit(
        X_train_windowed, y_train_windowed,
        epochs=100,  # Se puede detener antes con Early Stopping
        batch_size=batch_size,  # 🔹 Batch size optimizado
        validation_data=(X_val_windowed, y_val_windowed),  # 🔹 Validación en cada época
        callbacks=[early_stop],  # 🔹 Early Stopping activado
        verbose=0
    )

    # Obtener la mejor pérdida de validación
    val_loss = min(history.history['val_loss'])
    return val_loss  # Optuna minimizará este valor

# Crear el estudio de optimización
Forecasting_study = optuna.create_study(direction="minimize")
Forecasting_study.optimize(objective, n_trials=50, n_jobs=-1)  # Ejecutar 50 pruebas

# Imprimir los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", Forecasting_study.best_params)

[I 2025-03-12 05:35:50,225] A new study created in memory with name: no-name-7b53bf29-4e75-408e-8534-cb384d67add5
[I 2025-03-12 05:40:51,302] Trial 1 finished with value: 0.10972427576780319 and parameters: {'filters': 64, 'kernel_size': 2, 'lstm_units_1': 256, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.23069405568410684, 'dropout_dense': 0.1555943975788619, 'learning_rate': 0.00919904200937645, 'batch_size': 128}. Best is trial 1 with value: 0.10972427576780319.
[I 2025-03-12 05:49:22,920] Trial 4 finished with value: 0.1219572126865387 and parameters: {'filters': 64, 'kernel_size': 5, 'lstm_units_1': 256, 'lstm_units_2': 128, 'lstm_units_3': 16, 'dropout_lstm': 0.27869011858723536, 'dropout_dense': 0.21369646828833366, 'learning_rate': 0.007644977299868267, 'batch_size': 512}. Best is trial 1 with value: 0.10972427576780319.
[I 2025-03-12 05:59:51,434] Trial 5 finished with value: 0.17393772304058075 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 64, 'dropout_lstm': 0.3879620611975271, 'dropout_dense': 0.37821183154718563, 'learning_rate': 0.0016172629123434468, 'batch_size': 512}. Best is trial 1 with value: 0.10972427576780319.
[I 2025-03-12 06:06:30,710] Trial 6 finished with value: 0.15386639535427094 and parameters: {'filters': 32, 'kernel_size': 2, 'lstm_units_1': 256, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.21249332615706884, 'dropout_dense': 0.3609786108646118, 'learning_rate': 0.0012409962468799894, 'batch_size': 256}. Best is trial 1 with value: 0.10972427576780319.
[I 2025-03-12 06:09:38,809] Trial 7 finished with value: 0.14149479568004608 and parameters: {'filters': 32, 'kernel_size': 3, 'lstm_units_1': 64, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.3118165551294648, 'dropout_dense': 0.2716076909153316, 'learning_rate': 0.0036677809671808686, 'batch_size': 256}. Best is trial 1 with value: 0.10972427576780319.
[I 2025-03-12 06:14:03,225] Trial 8 finished with value: 0.2232665717601776 and parameters: {'filters': 128, 'kernel_size': 4, 'lstm_units_1': 256, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.26023979026863553, 'dropout_dense': 0.42711767311078075, 'learning_rate': 0.0005786158305451466, 'batch_size': 512}. Best is trial 1 with value: 0.10972427576780319.
[I 2025-03-12 06:19:13,144] Trial 9 finished with value: 0.4285130500793457 and parameters: {'filters': 128, 'kernel_size': 5, 'lstm_units_1': 128, 'lstm_units_2': 64, 'lstm_units_3': 64, 'dropout_lstm': 0.3771947858950788, 'dropout_dense': 0.2851178385907707, 'learning_rate': 0.0002528451241746655, 'batch_size': 128}. Best is trial 1 with value: 0.10972427576780319.
[I 2025-03-12 06:22:59,204] Trial 10 finished with value: 0.13116298615932465 and parameters: {'filters': 128, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 32, 'lstm_units_3': 64, 'dropout_lstm': 0.43395161353983325, 'dropout_dense': 0.43312573983437264, 'learning_rate': 0.00996738305188534, 'batch_size': 128}. Best is trial 1 with value: 0.10972427576780319.
[I 2025-03-12 06:35:21,166] Trial 11 finished with value: 0.4314676821231842 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 128, 'lstm_units_2': 64, 'lstm_units_3': 64, 'dropout_lstm': 0.480539940711012, 'dropout_dense': 0.19002859299888503, 'learning_rate': 0.00013720106448110786, 'batch_size': 128}. Best is trial 1 with value: 0.10972427576780319.
[I 2025-03-12 06:41:10,100] Trial 12 finished with value: 0.1489601880311966 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.479669131337103, 'dropout_dense': 0.33103113941990137, 'learning_rate': 0.006038870341589885, 'batch_size': 256}. Best is trial 1 with value: 0.10972427576780319.
[I 2025-03-12 06:45:56,052] Trial 2 finished with value: 0.03198991343379021 and parameters: {'filters': 128, 'kernel_size': 5, 'lstm_units_1': 64, 'lstm_units_2': 128, 'lstm_units_3': 32, 'dropout_lstm': 0.2296487901920799, 'dropout_dense': 0.4520958795594442, 'learning_rate': 0.0003312273559992512, 'batch_size': 512}. Best is trial 2 with value: 0.03198991343379021.
[I 2025-03-12 07:01:39,349] Trial 14 finished with value: 0.1551758050918579 and parameters: {'filters': 64, 'kernel_size': 2, 'lstm_units_1': 64, 'lstm_units_2': 128, 'lstm_units_3': 32, 'dropout_lstm': 0.12401498228195376, 'dropout_dense': 0.49810794143934295, 'learning_rate': 0.000527487733329405, 'batch_size': 128}. Best is trial 2 with value: 0.03198991343379021.

### Photovoltaic

In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv1D, MaxPooling1D, Bidirectional, GRU, MultiHeadAttention
from tensorflow.keras.layers import Flatten, Dropout, Dense
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import mean_squared_error

# Definir la función objetivo para Optuna
def objective(trial):
    # Hiperparámetros a optimizar
    filters_1 = trial.suggest_categorical("filters_1", [32, 64, 128])
    filters_2 = trial.suggest_categorical("filters_2", [64, 128, 256])
    kernel_size = trial.suggest_int("kernel_size", 2, 5)
    gru_units = trial.suggest_categorical("gru_units", [32, 64, 128])
    num_heads = trial.suggest_categorical("num_heads", [2, 4, 8])
    dropout_rate = trial.suggest_float("dropout_rate", 0.2, 0.5)
    dense_units_1 = trial.suggest_categorical("dense_units_1", [32, 64, 128])
    dense_units_2 = trial.suggest_categorical("dense_units_2", [16, 32, 64])
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-4, 1e-2)
    batch_size = trial.suggest_categorical("batch_size", [128, 256, 512])

    # Definir el modelo
    inputs = Input(shape=(X_train_windowed.shape[1], X_train_windowed.shape[2]))

    # Primera capa CNN
    x = Conv1D(filters=filters_1, kernel_size=kernel_size, padding='same', activation='relu')(inputs)
    x = MaxPooling1D(pool_size=2)(x)

    # Segunda capa CNN
    x = Conv1D(filters=filters_2, kernel_size=kernel_size, padding='same', activation='relu')(x)
    x = MaxPooling1D(pool_size=2)(x)

    # Capa BiGRU
    x = Bidirectional(GRU(gru_units, return_sequences=True))(x)

    # Atención MultiHead
    attention = MultiHeadAttention(num_heads=num_heads, key_dim=128)(x, x)

    # Aplanar y Dropout
    x = Flatten()(attention)
    x = Dropout(dropout_rate)(x)
    x = Dense(dense_units_1, activation="relu", kernel_regularizer=l2(0.01))(x)
    x = Dense(dense_units_2, activation="relu")(x)

    # Capa de salida
    outputs = Dense(1, activation="linear")(x)

    # Construcción del modelo
    model = Model(inputs=inputs, outputs=outputs)

    # Compilar el modelo
    model.compile(
        loss=tf.keras.losses.MeanSquaredError(),
        optimizer=Adam(learning_rate=learning_rate),
        metrics=[tf.keras.metrics.RootMeanSquaredError()]
    )

    # Early Stopping
    early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True, verbose=1)

    # Entrenar el modelo
    history = model.fit(
        X_train_windowed, y_train_windowed,
        epochs=100,  # Se detendrá con Early Stopping
        batch_size=batch_size,
        validation_data=(X_val_windowed, y_val_windowed),
        callbacks=[early_stop],
        verbose=0
    )

    # Obtener la mejor pérdida de validación
    val_loss = min(history.history['val_loss'])
    return val_loss  # Optuna minimizará este valor

# Crear el estudio de optimización
Photovoltaic_study = optuna.create_study(direction="minimize")
Photovoltaic_study.optimize(objective, n_trials=50, n_jobs=-1)  # Ejecutar 50 pruebas

# Imprimir los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", Photovoltaic_study.best_params)