# Conjunto de datos completo sin clusterización

In [1]:
#Importaciones
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

#Lectura de datos
datos = pd.read_excel('03_Clusterizacion.xlsx')
datos.head(24)

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,Cluster GMM
0,2022-09-01 00:00:00,0.000000,19,7,77,0,4,15,0,Noche,Noche
1,2022-09-01 01:00:00,0.000000,19,7,82,0,4,16,1,Noche,Noche
2,2022-09-01 02:00:00,0.000000,18,9,85,0,3,16,2,Noche,Noche
3,2022-09-01 03:00:00,0.000000,18,11,87,0,3,16,3,Noche,Noche
4,2022-09-01 04:00:00,0.000000,18,11,88,0,3,16,4,Noche,Noche
5,2022-09-01 05:00:00,0.000000,17,15,86,0,3,14,5,Noche,Noche
6,2022-09-01 06:00:00,0.000000,18,47,89,0,3,16,6,Nublado,Lluvioso
7,2022-09-01 07:00:00,6.584959,18,51,95,0,4,17,7,Nublado,Lluvioso
8,2022-09-01 08:00:00,560.422022,18,47,100,0,3,18,8,Nublado,Lluvioso
9,2022-09-01 09:00:00,7720.582326,18,5,100,1,4,18,9,Nublado,Lluvioso
10,2022-09-01 10:00:00,9433.109309,19,5,93,2,4,18,10,Nublado,Lluvioso
11,2022-09-01 11:00:00,22189.147406,20,5,79,2,4,17,11,Nublado,Lluvioso
12,2022-09-01 12:00:00,29196.986647,22,5,64,6,3,15,12,Nublado,Lluvioso
13,2022-09-01 13:00:00,25478.471342,23,5,51,11,3,13,13,Soleado,Lluvioso
14,2022-09-01 14:00:00,29057.585772,25,3,41,12,1,11,14,Soleado,Lluvioso
15,2022-09-01 15:00:00,30000.000000,26,0,35,11,1,9,15,Soleado,Soleado
16,2022-09-01 16:00:00,28062.328964,27,0,33,8,1,9,16,Soleado,Soleado
17,2022-09-01 17:00:00,28786.629243,28,0,34,5,1,11,17,Soleado,Soleado
18,2022-09-01 18:00:00,29900.303971,27,0,37,3,2,11,18,Soleado,Soleado
19,2022-09-01 19:00:00,18282.505369,26,0,41,2,3,12,19,Soleado,Soleado
20,2022-09-01 20:00:00,3411.083740,24,2,48,0,3,12,20,Nublado,Lluvioso
21,2022-09-01 21:00:00,382.187718,22,6,55,0,3,13,21,Nublado,Lluvioso
22,2022-09-01 22:00:00,0.000000,21,6,61,0,4,13,22,Noche,Noche
23,2022-09-01 23:00:00,0.000000,20,6,68,0,4,14,23,Noche,Noche

In [2]:
datos["Generacion_prev_hour"] = datos["Generación"].shift(1)
datos["Generacion_prev_day"] = datos["Generación"].shift(24)
datos = datos.dropna(how="any", axis= 0)

Definimos X y y

In [3]:
datos_dia = datos[datos["Cluster KMeans"] == "Nublado"].copy()
datos_dia.head(10)

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day
30,2022-09-02 06:00:00,0.000000,17,7,91,0,4,15,6,Nublado,Lluvioso,0.000000,0.000000
31,2022-09-02 07:00:00,0.000000,17,7,94,0,3,16,7,Nublado,Lluvioso,0.000000,6.584959
32,2022-09-02 08:00:00,438.814997,16,5,97,0,3,15,8,Nublado,Lluvioso,0.000000,560.422022
33,2022-09-02 09:00:00,5908.000884,17,0,93,1,2,16,9,Nublado,Lluvioso,438.814997,7720.582326
34,2022-09-02 10:00:00,5030.740421,18,0,85,2,2,15,10,Nublado,Lluvioso,5908.000884,9433.109309
39,2022-09-02 15:00:00,24647.568577,26,7,33,5,4,8,15,Nublado,Lluvioso,28500.000000,30000.000000
40,2022-09-02 16:00:00,25500.000000,27,7,34,4,4,9,16,Nublado,Lluvioso,24647.568577,28062.328964
41,2022-09-02 17:00:00,24281.956494,28,7,36,2,4,12,17,Nublado,Lluvioso,25500.000000,28786.629243
42,2022-09-02 18:00:00,22733.515002,26,7,39,1,4,12,18,Nublado,Lluvioso,24281.956494,29900.303971
43,2022-09-02 19:00:00,11972.590689,25,7,44,1,4,12,19,Nublado,Lluvioso,22733.515002,18282.505369

In [4]:
columns = datos_dia.drop(columns=["Fecha", "Generación", "Cluster KMeans", "Cluster GMM"]).columns

In [5]:
X = datos_dia[columns]
X

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
30,17,7,91,0,4,15,6,0.000000,0.000000
31,17,7,94,0,3,16,7,0.000000,6.584959
32,16,5,97,0,3,15,8,0.000000,560.422022
33,17,0,93,1,2,16,9,438.814997,7720.582326
34,18,0,85,2,2,15,10,5908.000884,9433.109309
...,...,...,...,...,...,...,...,...,...
18273,14,0,87,1,4,11,8,67.000000,7302.000000
18274,15,0,83,2,4,12,9,7356.000000,18014.000000
18275,17,0,71,4,3,12,10,17638.000000,23010.000000
18276,19,0,60,5,3,11,11,23339.000000,26156.000000
18278,23,0,44,7,4,10,13,26277.000000,25653.000000

In [6]:
y = datos_dia[['Generación']]
y

         Generación
30         0.000000
31         0.000000
32       438.814997
33      5908.000884
34      5030.740421
...             ...
18273   7356.000000
18274  17638.000000
18275  23339.000000
18276  26323.000000
18278  25598.000000

[5214 rows x 1 columns]

Dividimos entrenamiento, validación y prueba

In [7]:
train_size = int(0.7 * len(X))
val_size = int(0.85 * len(X))

In [8]:
# Entrenamiento, validación y prueba, 75, 15 y 15
X_train, y_train =  X.iloc[:train_size, :], y.iloc[:train_size, :]
X_val, y_val = X.iloc[train_size:val_size, :], y.iloc[train_size:val_size, :]
X_test, y_test = X.iloc[val_size:, :],  y.iloc[val_size:,:]

print(f'X_train: {len(X_train)}, y_train: {len(y_train)}')
print(f'X_val: {len(X_val)}, y_val: {len(y_val)}')
print(f'X_test: {len(X_test)}, y_test: {len(y_test)}')

X_train: 3649, y_train: 3649
X_val: 782, y_val: 782
X_test: 783, y_test: 783

## Escalar con MinMaxScaler

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
x_scaler = MinMaxScaler().fit(X_train)
x_scaler

MinMaxScaler()

In [11]:
X_train_scaled = x_scaler.transform(X_train)
print(X_train_scaled)
print(X_train_scaled.shape)

[[5.00000000e-01 7.77777778e-02 9.04255319e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [5.00000000e-01 7.77777778e-02 9.36170213e-01 ... 6.66666667e-02
  0.00000000e+00 2.19498623e-04]
 [4.68750000e-01 5.55555556e-02 9.68085106e-01 ... 1.33333333e-01
  0.00000000e+00 1.86807341e-02]
 ...
 [2.50000000e-01 1.11111111e-02 9.78723404e-01 ... 6.66666667e-02
  0.00000000e+00 0.00000000e+00]
 [2.18750000e-01 0.00000000e+00 1.00000000e+00 ... 1.33333333e-01
  0.00000000e+00 5.96666667e-03]
 [1.87500000e-01 0.00000000e+00 1.00000000e+00 ... 2.00000000e-01
  9.83333333e-03 3.62200000e-01]]
(3649, 9)

In [12]:
X_train_scaled_df = pd.DataFrame(X_train_scaled, index=X_train.index, columns=X_train.columns)
X_train_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
30,0.50000,0.077778,0.904255,0.000000,0.666667,0.789474,0.000000,0.000000,0.000000
31,0.50000,0.077778,0.936170,0.000000,0.333333,0.842105,0.066667,0.000000,0.000219
32,0.46875,0.055556,0.968085,0.000000,0.333333,0.789474,0.133333,0.000000,0.018681
33,0.50000,0.000000,0.925532,0.083333,0.000000,0.842105,0.200000,0.014627,0.257353
34,0.53125,0.000000,0.840426,0.166667,0.000000,0.789474,0.266667,0.196933,0.314437
...,...,...,...,...,...,...,...,...,...
12958,0.53125,0.000000,0.446809,0.000000,0.333333,0.368421,1.000000,0.000000,0.000000
12967,0.28125,0.011111,0.978723,0.000000,1.000000,0.473684,0.000000,0.000000,0.000000
12968,0.25000,0.011111,0.978723,0.000000,1.000000,0.473684,0.066667,0.000000,0.000000
12969,0.21875,0.000000,1.000000,0.000000,0.333333,0.421053,0.133333,0.000000,0.005967
12970,0.18750,0.000000,1.000000,0.083333,0.333333,0.368421,0.200000,0.009833,0.362200

In [13]:
X_val_scaled = x_scaler.transform(X_val)
print(X_val_scaled)
print(X_val_scaled.shape)

[[0.28125    0.         0.82978723 ... 0.26666667 0.31593333 0.63086667]
 [0.375      0.         0.67021277 ... 0.33333333 0.65066667 0.66426667]
 [0.46875    0.         0.54255319 ... 0.4        0.67886667 0.6496    ]
 ...
 [0.75       0.02222222 0.43617021 ... 0.86666667 0.34693333 0.1592    ]
 [0.6875     0.06666667 0.5106383  ... 0.93333333 0.20373333 0.0115    ]
 [0.46875    0.07777778 0.87234043 ... 0.         0.         0.        ]]
(782, 9)

In [14]:
X_val_scaled_df = pd.DataFrame(X_val_scaled, index=X_val.index, columns=X_val.columns)
X_val_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
12971,0.28125,0.000000,0.829787,0.166667,0.333333,0.368421,0.266667,0.315933,0.630867
12972,0.37500,0.000000,0.670213,0.166667,0.333333,0.368421,0.333333,0.650667,0.664267
12973,0.46875,0.000000,0.542553,0.250000,0.333333,0.368421,0.400000,0.678867,0.649600
12974,0.53125,0.000000,0.457447,0.250000,0.333333,0.368421,0.466667,0.656667,0.798233
12981,0.53125,0.000000,0.436170,0.000000,0.666667,0.368421,0.933333,0.042467,0.000000
...,...,...,...,...,...,...,...,...,...
16383,0.78125,0.000000,0.382979,0.750000,0.666667,0.631579,0.533333,0.900000,0.362167
16387,0.78125,0.000000,0.382979,0.166667,0.666667,0.631579,0.800000,0.379967,0.348467
16388,0.75000,0.022222,0.436170,0.000000,1.000000,0.684211,0.866667,0.346933,0.159200
16389,0.68750,0.066667,0.510638,0.000000,0.333333,0.684211,0.933333,0.203733,0.011500
16399,0.46875,0.077778,0.872340,0.000000,1.000000,0.736842,0.000000,0.000000,0.000000

In [15]:
X_test_scaled = x_scaler.transform(X_test)
print(X_test_scaled)
print(X_test_scaled.shape)

[[0.46875    0.06666667 0.87234043 ... 0.06666667 0.         0.06736667]
 [0.46875    0.02222222 0.86170213 ... 0.13333333 0.0214     0.4988    ]
 [0.5        0.02222222 0.80851064 ... 0.2        0.2268     0.8451    ]
 ...
 [0.5        0.         0.69148936 ... 0.26666667 0.58793333 0.767     ]
 [0.5625     0.         0.57446809 ... 0.33333333 0.77796667 0.87186667]
 [0.6875     0.         0.40425532 ... 0.46666667 0.8759     0.8551    ]]
(783, 9)

In [16]:
X_test_scaled_df = pd.DataFrame(X_test_scaled, index=X_test.index, columns=X_test.columns)
X_test_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
16400,0.46875,0.066667,0.872340,0.000000,1.000000,0.736842,0.066667,0.000000,0.067367
16401,0.46875,0.022222,0.861702,0.083333,1.000000,0.736842,0.133333,0.021400,0.498800
16402,0.50000,0.022222,0.808511,0.166667,1.000000,0.736842,0.200000,0.226800,0.845100
16403,0.59375,0.022222,0.702128,0.166667,1.000000,0.736842,0.266667,0.350033,0.895933
16404,0.65625,0.022222,0.606383,0.583333,0.333333,0.736842,0.333333,0.438233,0.900000
...,...,...,...,...,...,...,...,...,...
18273,0.40625,0.000000,0.861702,0.083333,0.666667,0.578947,0.133333,0.002233,0.243400
18274,0.43750,0.000000,0.819149,0.166667,0.666667,0.631579,0.200000,0.245200,0.600467
18275,0.50000,0.000000,0.691489,0.333333,0.333333,0.631579,0.266667,0.587933,0.767000
18276,0.56250,0.000000,0.574468,0.416667,0.333333,0.578947,0.333333,0.777967,0.871867
18278,0.68750,0.000000,0.404255,0.583333,0.666667,0.526316,0.466667,0.875900,0.855100

In [17]:
x_scaller_all = MinMaxScaler().fit(X)
print(x_scaller_all)

MinMaxScaler()

In [18]:
X_scaled = x_scaller_all.transform(X)
print(X_scaled)
print(X_scaled.shape)

[[4.32432432e-01 7.77777778e-02 9.06250000e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [4.32432432e-01 7.77777778e-02 9.37500000e-01 ... 6.66666667e-02
  0.00000000e+00 2.19498623e-04]
 [4.05405405e-01 5.55555556e-02 9.68750000e-01 ... 1.33333333e-01
  0.00000000e+00 1.86807341e-02]
 ...
 [4.32432432e-01 0.00000000e+00 6.97916667e-01 ... 2.66666667e-01
  5.87933333e-01 7.67000000e-01]
 [4.86486486e-01 0.00000000e+00 5.83333333e-01 ... 3.33333333e-01
  7.77966667e-01 8.71866667e-01]
 [5.94594595e-01 0.00000000e+00 4.16666667e-01 ... 4.66666667e-01
  8.75900000e-01 8.55100000e-01]]
(5214, 9)

In [19]:
X_scaled_df = pd.DataFrame(X_scaled, index=X.index, columns=X.columns)
X_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
30,0.432432,0.077778,0.906250,0.000000,0.666667,0.75,0.000000,0.000000,0.000000
31,0.432432,0.077778,0.937500,0.000000,0.333333,0.80,0.066667,0.000000,0.000219
32,0.405405,0.055556,0.968750,0.000000,0.333333,0.75,0.133333,0.000000,0.018681
33,0.432432,0.000000,0.927083,0.083333,0.000000,0.80,0.200000,0.014627,0.257353
34,0.459459,0.000000,0.843750,0.166667,0.000000,0.75,0.266667,0.196933,0.314437
...,...,...,...,...,...,...,...,...,...
18273,0.351351,0.000000,0.864583,0.083333,0.666667,0.55,0.133333,0.002233,0.243400
18274,0.378378,0.000000,0.822917,0.166667,0.666667,0.60,0.200000,0.245200,0.600467
18275,0.432432,0.000000,0.697917,0.333333,0.333333,0.60,0.266667,0.587933,0.767000
18276,0.486486,0.000000,0.583333,0.416667,0.333333,0.55,0.333333,0.777967,0.871867
18278,0.594595,0.000000,0.416667,0.583333,0.666667,0.50,0.466667,0.875900,0.855100

In [20]:
y_scaler = MinMaxScaler().fit(y_train)
print(y_scaler)

MinMaxScaler()

In [21]:
y_train_scaled = y_scaler.transform(y_train)
print(y_train_scaled)
print(y_train_scaled.shape)

[[0.        ]
 [0.        ]
 [0.01462717]
 ...
 [0.        ]
 [0.00983333]
 [0.31593333]]
(3649, 1)

In [22]:
y_train_scaled_df = pd.DataFrame(y_train_scaled, index=y_train.index, columns=y_train.columns)
y_train_scaled_df

       Generación
30       0.000000
31       0.000000
32       0.014627
33       0.196933
34       0.167691
...           ...
12958    0.000000
12967    0.000000
12968    0.000000
12969    0.009833
12970    0.315933

[3649 rows x 1 columns]

In [23]:
y_val_scaled = y_scaler.transform(y_val)
print(y_val_scaled)
print(y_val_scaled.shape)

[[6.50666667e-01]
 [6.78866667e-01]
 [6.56666667e-01]
 [6.34033333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.17000000e-02]
 [4.02500000e-01]
 [6.29733333e-01]
 [6.02466667e-01]
 [3.92200000e-01]
 [4.24333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.01333333e-02]
 [3.76966667e-01]
 [7.10300000e-01]
 [7.51233333e-01]
 [7.85666667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.57333333e-02]
 [4.93300000e-01]
 [8.19466667e-01]
 [8.34700000e-01]
 [8.20833333e-01]
 [7.17400000e-01]
 [8.18666667e-01]
 [6.90233333e-01]
 [4.11033333e-01]
 [4.34666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.32000000e-02]
 [5.93533333e-01]
 [6.08633333e-01]
 [8.79666667e-01]
 [6.04733333e-01]
 [1.12600000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32066667e-01]
 [2.87266667e-01]
 [8.49266667e-01]
 [8.96300000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.34133333e-01]
 [9.95633333e-01]
 [8.73600000e-01]
 [5.62600000e-01]
 [4.62666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.04733333e-01]
 [1.12600000e-01]
 [0.00000000e+00]
 [2.69333333e-02]
 [4.75066667e-01]
 [5.05100000e-01]
 [7.07666667e-01]
 [7.24233333e-01]
 [7.01633333e-01]
 [6.87333333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.85666667e-02]
 [4.76400000e-01]
 [4.86900000e-01]
 [7.03733333e-01]
 [7.16300000e-01]
 [6.92800000e-01]
 [6.66866667e-01]
 [4.91366667e-01]
 [9.59666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.94666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.79000000e-02]
 [5.37166667e-01]
 [5.50066667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.35333333e-02]
 [1.42433333e-01]
 [1.70400000e-01]
 [6.15766667e-01]
 [6.26766667e-01]
 [6.28100000e-01]
 [6.09866667e-01]
 [9.53333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.99333333e-02]
 [4.15466667e-01]
 [4.86900000e-01]
 [7.03733333e-01]
 [7.21466667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.68666667e-02]
 [3.79866667e-01]
 [4.05700000e-01]
 [5.93666667e-01]
 [1.34566667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.32000000e-02]
 [6.09333333e-01]
 [6.15400000e-01]
 [8.61400000e-01]
 [8.16733333e-01]
 [6.21266667e-01]
 [1.01333333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.02733333e-01]
 [7.33566667e-01]
 [9.86300000e-01]
 [9.94966667e-01]
 [9.92933333e-01]
 [8.74533333e-01]
 [4.33266667e-01]
 [4.10333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.32000000e-02]
 [5.95633333e-01]
 [6.29866667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.06333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.00000000e-04]
 [4.15466667e-01]
 [4.44233333e-01]
 [8.68733333e-01]
 [8.07700000e-01]
 [5.96633333e-01]
 [1.10966667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.66666667e-05]
 [1.89933333e-01]
 [6.10200000e-01]
 [7.91700000e-01]
 [8.05833333e-01]
 [7.12233333e-01]
 [6.85733333e-01]
 [6.81133333e-01]
 [7.68600000e-01]
 [9.80400000e-01]
 [7.70233333e-01]
 [4.56866667e-01]
 [1.07900000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.56133333e-01]
 [4.50066667e-01]
 [6.51266667e-01]
 [9.75433333e-01]
 [9.28733333e-01]
 [9.71900000e-01]
 [9.31933333e-01]
 [5.67633333e-01]
 [6.32233333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.74833333e-01]
 [6.28000000e-01]
 [7.55433333e-01]
 [7.36500000e-01]
 [7.29200000e-01]
 [6.37000000e-01]
 [7.18033333e-01]
 [5.17733333e-01]
 [1.03866667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.66666667e-04]
 [0.00000000e+00]
 [6.66666667e-05]
 [5.93533333e-01]
 [6.18800000e-01]
 [8.85000000e-01]
 [8.95366667e-01]
 [8.79966667e-01]
 [8.78133333e-01]
 [0.00000000e+00]
 [4.00000000e-04]
 [5.93533333e-01]
 [6.08633333e-01]
 [9.83666667e-02]
 [6.66666667e-05]
 [0.00000000e+00]
 [1.06333333e-02]
 [7.41066667e-01]
 [7.40600000e-01]
 [7.27733333e-01]
 [7.02333333e-01]
 [5.67033333e-01]
 [1.54833333e-01]
 [1.13333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.33000000e-02]
 [3.42366667e-01]
 [8.38633333e-01]
 [9.25600000e-01]
 [9.35966667e-01]
 [9.38166667e-01]
 [0.00000000e+00]
 [3.52166667e-01]
 [8.19466667e-01]
 [9.29666667e-01]
 [0.00000000e+00]
 [1.32333333e-02]
 [2.79033333e-01]
 [6.55566667e-01]
 [7.40466667e-01]
 [1.23333333e-03]
 [1.43233333e-01]
 [1.40000000e-03]
 [0.00000000e+00]
 [9.19733333e-01]
 [8.85233333e-01]
 [7.12900000e-01]
 [1.93533333e-01]
 [1.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.06333333e-02]
 [2.73866667e-01]
 [7.52966667e-01]
 [7.50966667e-01]
 [6.56566667e-01]
 [6.55966667e-01]
 [6.14533333e-01]
 [0.00000000e+00]
 [1.38333333e-02]
 [3.42366667e-01]
 [8.19466667e-01]
 [9.25600000e-01]
 [9.35966667e-01]
 [1.73333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.19666667e-02]
 [2.73866667e-01]
 [6.63866667e-01]
 [7.43800000e-01]
 [1.76666667e-03]
 [0.00000000e+00]
 [3.10300000e-01]
 [7.40766667e-01]
 [9.27233333e-01]
 [1.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.34333333e-02]
 [2.91733333e-01]
 [7.18000000e-01]
 [7.64600000e-01]
 [7.68100000e-01]
 [7.65933333e-01]
 [7.58566667e-01]
 [7.55666667e-01]
 [6.59333333e-01]
 [7.54133333e-01]
 [7.20366667e-01]
 [6.26533333e-01]
 [1.58300000e-01]
 [1.40000000e-03]
 [0.00000000e+00]
 [2.83333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.01000000e-02]
 [7.48133333e-01]
 [7.90333333e-02]
 [0.00000000e+00]
 [2.79333333e-02]
 [3.94066667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.38000000e-02]
 [2.01066667e-01]
 [4.30800000e-01]
 [4.64833333e-01]
 [4.58433333e-01]
 [4.54800000e-01]
 [7.52700000e-01]
 [7.62066667e-01]
 [7.59900000e-01]
 [9.37666667e-01]
 [9.01433333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.10666667e-02]
 [4.37533333e-01]
 [8.85433333e-01]
 [2.49433333e-01]
 [0.00000000e+00]
 [3.64000000e-02]
 [3.85233333e-01]
 [8.97466667e-01]
 [6.85333333e-01]
 [2.01966667e-01]
 [0.00000000e+00]
 [2.15666667e-02]
 [0.00000000e+00]
 [2.30666667e-02]
 [2.81900000e-01]
 [5.97866667e-01]
 [7.57933333e-01]
 [9.64766667e-01]
 [9.81133333e-01]
 [9.63200000e-01]
 [9.37400000e-01]
 [9.37700000e-01]
 [9.21500000e-01]
 [0.00000000e+00]
 [3.00666667e-02]
 [4.26866667e-01]
 [4.10000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.46000000e-02]
 [4.65733333e-01]
 [8.82200000e-01]
 [9.89600000e-01]
 [0.00000000e+00]
 [4.58333333e-02]
 [4.38600000e-01]
 [8.90033333e-01]
 [9.74766667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.05666667e-02]
 [4.22800000e-01]
 [7.70600000e-01]
 [8.59000000e-01]
 [9.42933333e-01]
 [2.73700000e-01]
 [9.46666667e-03]
 [7.20566667e-01]
 [6.79966667e-01]
 [5.74900000e-01]
 [2.18966667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.27333333e-02]
 [0.00000000e+00]
 [4.67666667e-02]
 [3.91000000e-01]
 [6.52300000e-01]
 [6.32733333e-01]
 [2.85100000e-01]
 [9.70000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.62000000e-02]
 [3.79400000e-01]
 [0.00000000e+00]
 [4.92333333e-02]
 [3.97033333e-01]
 [8.50133333e-01]
 [8.45200000e-01]
 [8.39266667e-01]
 [7.20000000e-01]
 [6.84566667e-01]
 [5.74900000e-01]
 [2.98200000e-01]
 [1.05000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.05666667e-02]
 [3.93466667e-01]
 [6.52300000e-01]
 [7.27966667e-01]
 [7.46533333e-01]
 [7.53633333e-01]
 [7.46500000e-01]
 [7.46100000e-01]
 [7.41400000e-01]
 [7.23333333e-01]
 [6.80400000e-01]
 [5.75633333e-01]
 [2.28066667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.93333333e-02]
 [3.28866667e-01]
 [5.70766667e-01]
 [7.19233333e-01]
 [7.46533333e-01]
 [6.60366667e-01]
 [6.50233333e-01]
 [7.46100000e-01]
 [7.41166667e-01]
 [6.29900000e-01]
 [5.94966667e-01]
 [5.82866667e-01]
 [2.26866667e-01]
 [7.63333333e-03]
 [0.00000000e+00]
 [9.36033333e-01]
 [8.99866667e-01]
 [5.74666667e-02]
 [8.66500000e-01]
 [9.17300000e-01]
 [0.00000000e+00]
 [5.69333333e-02]
 [4.74933333e-01]
 [0.00000000e+00]
 [8.79000000e-02]
 [4.69800000e-01]
 [7.27633333e-01]
 [5.77333333e-01]
 [2.26266667e-01]
 [1.72666667e-02]
 [0.00000000e+00]
 [8.16666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.16333333e-02]
 [6.95666667e-01]
 [3.56766667e-01]
 [3.35000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.23966667e-01]
 [3.38000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.24166667e-01]
 [4.55966667e-01]
 [3.94000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.71000000e-02]
 [5.83100000e-01]
 [0.00000000e+00]
 [7.76333333e-02]
 [5.28933333e-01]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.21533333e-01]
 [0.00000000e+00]
 [7.79333333e-02]
 [5.26466667e-01]
 [9.40466667e-01]
 [9.21400000e-01]
 [8.56933333e-01]
 [6.90300000e-01]
 [6.94800000e-01]
 [3.18100000e-01]
 [2.86666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.33333333e-03]
 [4.65666667e-02]
 [7.42000000e-02]
 [8.20000000e-02]
 [8.50000000e-02]
 [8.47666667e-02]
 [8.45333333e-02]
 [8.44333333e-02]
 [8.40333333e-02]
 [9.64666667e-02]
 [7.80000000e-02]
 [6.91000000e-02]
 [1.18933333e-01]
 [1.11666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.42333333e-02]
 [4.01966667e-01]
 [5.76600000e-01]
 [6.37700000e-01]
 [9.39166667e-01]
 [9.14933333e-01]
 [3.96400000e-01]
 [3.34666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.93666667e-02]
 [5.16633333e-01]
 [8.24633333e-01]
 [5.73933333e-01]
 [5.94400000e-01]
 [5.94600000e-01]
 [5.91666667e-01]
 [5.92500000e-01]
 [5.87833333e-01]
 [9.12000000e-01]
 [8.67033333e-01]
 [7.66066667e-01]
 [3.58066667e-01]
 [3.01000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.50000000e-02]
 [4.14800000e-01]
 [6.60433333e-01]
 [5.73933333e-01]
 [5.93733333e-01]
 [5.93833333e-01]
 [9.39700000e-01]
 [9.37200000e-01]
 [9.31833333e-01]
 [9.15333333e-01]
 [8.69733333e-01]
 [7.66066667e-01]
 [2.85400000e-01]
 [2.41000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.02333333e-02]
 [5.16633333e-01]
 [8.24900000e-01]
 [9.11033333e-01]
 [9.44466667e-01]
 [9.44500000e-01]
 [9.40966667e-01]
 [9.39266667e-01]
 [9.34466667e-01]
 [2.74366667e-01]
 [2.60033333e-01]
 [2.31266667e-01]
 [1.94666667e-01]
 [1.64000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.17866667e-01]
 [8.29166667e-01]
 [9.15400000e-01]
 [9.44733333e-01]
 [9.12000000e-01]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.46133333e-01]
 [8.40400000e-01]
 [9.17433333e-01]
 [9.47766667e-01]
 [0.00000000e+00]
 [8.25000000e-02]
 [5.39233333e-01]
 [8.24700000e-01]
 [9.11100000e-01]
 [9.41333333e-01]
 [9.48033333e-01]
 [8.13533333e-01]
 [4.57200000e-01]
 [4.96666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.18166667e-01]
 [8.30233333e-01]
 [9.11033333e-01]
 [9.44333333e-01]
 [7.00066667e-01]
 [4.08500000e-01]
 [4.69000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.81666667e-02]
 [5.21533333e-01]
 [8.27466667e-01]
 [9.11033333e-01]
 [9.48200000e-01]
 [9.41766667e-01]
 [9.36533333e-01]
 [6.73133333e-01]
 [9.12000000e-01]
 [6.24066667e-01]
 [5.01733333e-01]
 [3.64933333e-01]
 [3.01000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.21333333e-02]
 [5.18833333e-01]
 [8.27000000e-01]
 [9.11233333e-01]
 [8.55500000e-01]
 [9.41933333e-01]
 [9.33866667e-01]
 [8.21300000e-01]
 [7.80066667e-01]
 [5.63466667e-01]
 [4.56366667e-01]
 [3.40666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.71666667e-02]
 [3.60533333e-01]
 [5.79133333e-01]
 [5.85166667e-01]
 [6.07233333e-01]
 [6.03966667e-01]
 [5.94433333e-01]
 [5.88066667e-01]
 [5.90700000e-01]
 [4.46866667e-01]
 [4.23133333e-01]
 [3.83533333e-01]
 [3.29333333e-01]
 [2.31666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.54666667e-02]
 [4.35333333e-01]
 [7.98266667e-01]
 [8.94266667e-01]
 [9.26166667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.59666667e-02]
 [4.37000000e-01]
 [7.98366667e-01]
 [8.97400000e-01]
 [9.27600000e-01]
 [9.21233333e-01]
 [9.18966667e-01]
 [2.87333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.35333333e-01]
 [8.01333333e-01]
 [8.94866667e-01]
 [9.24766667e-01]
 [9.21233333e-01]
 [9.18966667e-01]
 [0.00000000e+00]
 [3.93666667e-02]
 [3.98566667e-01]
 [8.03900000e-01]
 [8.94266667e-01]
 [0.00000000e+00]
 [3.30333333e-02]
 [3.24500000e-01]
 [5.35133333e-01]
 [0.00000000e+00]
 [6.73666667e-02]
 [5.15066667e-01]
 [8.49400000e-01]
 [0.00000000e+00]
 [6.73666667e-02]
 [5.15066667e-01]
 [8.49400000e-01]
 [8.46033333e-01]
 [8.59966667e-01]
 [8.00666667e-01]
 [7.70200000e-01]
 [3.89333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.09666667e-02]
 [4.37133333e-01]
 [7.95400000e-01]
 [8.97400000e-01]
 [9.30400000e-01]
 [0.00000000e+00]
 [3.08333333e-02]
 [2.51400000e-01]
 [4.96333333e-01]
 [5.67933333e-01]
 [6.47633333e-01]
 [6.30766667e-01]
 [6.51766667e-01]
 [7.19033333e-01]
 [7.40133333e-01]
 [6.64433333e-01]
 [2.87466667e-01]
 [1.19000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.64666667e-01]
 [8.06500000e-01]
 [8.96166667e-01]
 [9.25000000e-01]
 [9.24933333e-01]
 [8.27066667e-01]
 [9.15533333e-01]
 [8.20566667e-01]
 [6.51200000e-01]
 [5.56433333e-01]
 [5.66766667e-01]
 [3.28733333e-01]
 [5.51000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.87666667e-02]
 [2.30066667e-01]
 [4.55966667e-01]
 [6.44833333e-01]
 [6.65833333e-01]
 [6.64366667e-01]
 [6.62500000e-01]
 [6.60866667e-01]
 [5.76833333e-01]
 [3.14633333e-01]
 [3.01600000e-01]
 [4.34866667e-01]
 [3.04900000e-01]
 [3.72000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.40333333e-02]
 [1.79900000e-01]
 [4.45933333e-01]
 [3.23633333e-01]
 [2.70000000e-01]
 [2.01200000e-01]
 [2.51800000e-01]
 [3.47666667e-01]
 [1.97800000e-01]
 [1.15000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.68333333e-02]
 [1.82600000e-01]
 [3.02933333e-01]
 [3.23700000e-01]
 [4.05000000e-01]
 [3.21633333e-01]
 [4.03566667e-01]
 [3.48466667e-01]
 [1.59200000e-01]
 [1.15000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.73666667e-02]
 [4.98800000e-01]
 [8.45100000e-01]
 [8.95933333e-01]
 [9.00000000e-01]
 [8.86300000e-01]
 [9.00000000e-01]
 [8.04800000e-01]
 [3.46933333e-01]
 [2.03733333e-01]
 [1.49000000e-02]
 [0.00000000e+00]]
(782, 1)

In [24]:
y_val_scaled_df = pd.DataFrame(y_val_scaled, index=y_val.index, columns=y_val.columns)
y_val_scaled_df

       Generación
12971    0.650667
12972    0.678867
12973    0.656667
12974    0.634033
12981    0.000000
...           ...
16383    0.804800
16387    0.346933
16388    0.203733
16389    0.014900
16399    0.000000

[782 rows x 1 columns]

In [25]:
y_test_scaled = y_scaler.transform(y_test)
print(y_test_scaled)
print(y_test_scaled.shape)

[[2.14000000e-02]
 [2.26800000e-01]
 [3.50033333e-01]
 [4.38233333e-01]
 [5.17866667e-01]
 [2.55666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.79666667e-02]
 [2.78633333e-01]
 [4.04633333e-01]
 [3.96600000e-01]
 [3.95833333e-01]
 [3.86166667e-01]
 [5.20300000e-01]
 [4.55600000e-01]
 [3.93566667e-01]
 [2.66166667e-01]
 [2.36933333e-01]
 [2.46166667e-01]
 [2.48333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.20333333e-02]
 [2.95566667e-01]
 [4.52433333e-01]
 [5.00800000e-01]
 [4.54266667e-01]
 [2.79633333e-01]
 [2.82066667e-01]
 [2.80133333e-01]
 [2.70033333e-01]
 [4.37733333e-01]
 [2.42166667e-01]
 [2.97333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.84000000e-02]
 [2.61400000e-01]
 [5.28433333e-01]
 [5.05033333e-01]
 [3.92000000e-01]
 [4.46200000e-01]
 [8.93633333e-01]
 [7.99433333e-01]
 [3.90766667e-01]
 [4.55000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.93000000e-02]
 [3.93100000e-01]
 [7.95400000e-01]
 [9.24766667e-01]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [9.00500000e-01]
 [9.24766667e-01]
 [0.00000000e+00]
 [4.35333333e-01]
 [7.95400000e-01]
 [8.96833333e-01]
 [9.24766667e-01]
 [9.37500000e-01]
 [7.85400000e-01]
 [3.59033333e-01]
 [3.83666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.49000000e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [9.33400000e-01]
 [8.52400000e-01]
 [1.78666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.93000000e-02]
 [1.40800000e-01]
 [2.47800000e-01]
 [3.81700000e-01]
 [3.92633333e-01]
 [3.94533333e-01]
 [4.66566667e-01]
 [4.48600000e-01]
 [5.12533333e-01]
 [5.03500000e-01]
 [6.21466667e-01]
 [7.75366667e-01]
 [1.92633333e-01]
 [1.78666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.38333333e-02]
 [4.69166667e-01]
 [8.33500000e-01]
 [8.16000000e-01]
 [6.67466667e-01]
 [6.60733333e-01]
 [6.64166667e-01]
 [6.88000000e-01]
 [6.62833333e-01]
 [6.58766667e-01]
 [6.36333333e-01]
 [8.15333333e-01]
 [4.41033333e-01]
 [4.64000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [8.94266667e-01]
 [9.24766667e-01]
 [9.23966667e-01]
 [9.25500000e-01]
 [9.15766667e-01]
 [9.10633333e-01]
 [8.99166667e-01]
 [8.67500000e-01]
 [7.71733333e-01]
 [3.93133333e-01]
 [3.19000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.43333333e-02]
 [4.39333333e-01]
 [7.95400000e-01]
 [8.94266667e-01]
 [9.24766667e-01]
 [9.21233333e-01]
 [8.61733333e-01]
 [7.70200000e-01]
 [4.02500000e-01]
 [3.19000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.49000000e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [8.94266667e-01]
 [9.31433333e-01]
 [9.24466667e-01]
 [9.15533333e-01]
 [9.10633333e-01]
 [9.00833333e-01]
 [8.61766667e-01]
 [7.73533333e-01]
 [3.93266667e-01]
 [3.19000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.58666667e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [7.16600000e-01]
 [7.40700000e-01]
 [5.51500000e-01]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [8.97400000e-01]
 [9.73900000e-01]
 [9.24566667e-01]
 [9.50366667e-01]
 [9.40766667e-01]
 [9.15500000e-01]
 [8.97933333e-01]
 [7.70200000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.38900000e-01]
 [7.95400000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.01333333e-02]
 [2.97733333e-01]
 [7.97666667e-01]
 [8.92133333e-01]
 [2.11666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.68666667e-02]
 [4.04933333e-01]
 [7.88133333e-01]
 [8.82633333e-01]
 [0.00000000e+00]
 [2.79000000e-02]
 [3.97200000e-01]
 [7.90900000e-01]
 [0.00000000e+00]
 [2.82000000e-02]
 [4.01833333e-01]
 [7.97833333e-01]
 [0.00000000e+00]
 [2.41666667e-02]
 [3.93333333e-01]
 [8.23766667e-01]
 [9.00666667e-01]
 [9.26133333e-01]
 [3.41100000e-01]
 [1.93333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.08000000e-02]
 [3.21433333e-01]
 [7.44300000e-01]
 [8.14833333e-01]
 [8.34400000e-01]
 [8.19566667e-01]
 [8.20200000e-01]
 [0.00000000e+00]
 [2.10000000e-02]
 [3.20100000e-01]
 [6.98633333e-01]
 [9.21966667e-01]
 [0.00000000e+00]
 [2.20666667e-02]
 [3.70033333e-01]
 [7.77866667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.40666667e-02]
 [3.77433333e-01]
 [7.84366667e-01]
 [9.24733333e-01]
 [9.35033333e-01]
 [9.05133333e-01]
 [0.00000000e+00]
 [2.28000000e-02]
 [3.40100000e-01]
 [7.78033333e-01]
 [8.86700000e-01]
 [9.26266667e-01]
 [6.40000000e-01]
 [2.28866667e-01]
 [5.33333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.38000000e-02]
 [3.74066667e-01]
 [7.80300000e-01]
 [8.81166667e-01]
 [9.25566667e-01]
 [6.45466667e-01]
 [2.28866667e-01]
 [7.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.06666667e-02]
 [2.83600000e-01]
 [6.43000000e-01]
 [7.04933333e-01]
 [7.41166667e-01]
 [7.39366667e-01]
 [7.27166667e-01]
 [7.26000000e-01]
 [9.05766667e-01]
 [9.07400000e-01]
 [8.90533333e-01]
 [7.13766667e-01]
 [1.52666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.38166667e-01]
 [7.77400000e-01]
 [8.85766667e-01]
 [9.23933333e-01]
 [9.30766667e-01]
 [9.24666667e-01]
 [9.19000000e-01]
 [6.03566667e-01]
 [3.52733333e-01]
 [7.50000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.99333333e-02]
 [3.41533333e-01]
 [7.73633333e-01]
 [9.07933333e-01]
 [9.37200000e-01]
 [9.37400000e-01]
 [9.06800000e-01]
 [5.94366667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.63333333e-01]
 [7.73633333e-01]
 [8.95666667e-01]
 [9.39000000e-01]
 [9.42600000e-01]
 [9.48766667e-01]
 [7.39966667e-01]
 [5.75833333e-01]
 [2.85466667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.74333333e-02]
 [3.84800000e-01]
 [8.13333333e-01]
 [9.17600000e-01]
 [9.38200000e-01]
 [9.34533333e-01]
 [9.24633333e-01]
 [9.16733333e-01]
 [9.43433333e-01]
 [9.25966667e-01]
 [8.90533333e-01]
 [6.74700000e-01]
 [2.71400000e-01]
 [9.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.74000000e-02]
 [3.83966667e-01]
 [8.16733333e-01]
 [9.14666667e-01]
 [9.40133333e-01]
 [9.33866667e-01]
 [9.32600000e-01]
 [6.02600000e-01]
 [2.77466667e-01]
 [8.63333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.84333333e-02]
 [3.84966667e-01]
 [8.08000000e-01]
 [7.33100000e-01]
 [7.46000000e-01]
 [7.52033333e-01]
 [5.51133333e-01]
 [2.46333333e-01]
 [6.23333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.14333333e-02]
 [2.73366667e-01]
 [6.37833333e-01]
 [7.21900000e-01]
 [7.56166667e-01]
 [7.46266667e-01]
 [7.46633333e-01]
 [5.15266667e-01]
 [1.83066667e-01]
 [9.96666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.46000000e-02]
 [2.85633333e-01]
 [9.27366667e-01]
 [6.06666667e-01]
 [7.76666667e-02]
 [4.00000000e-04]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.52000000e-02]
 [2.73033333e-01]
 [9.27566667e-01]
 [5.23400000e-01]
 [0.00000000e+00]
 [7.29566667e-01]
 [2.75333333e-01]
 [7.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.98300000e-01]
 [8.33866667e-01]
 [8.81166667e-01]
 [9.62066667e-01]
 [5.98633333e-01]
 [1.88466667e-01]
 [4.73333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.99666667e-01]
 [8.33866667e-01]
 [8.81166667e-01]
 [0.00000000e+00]
 [1.32666667e-02]
 [4.06533333e-01]
 [8.33866667e-01]
 [2.34266667e-01]
 [7.83333333e-03]
 [0.00000000e+00]
 [1.39333333e-02]
 [3.30833333e-01]
 [7.73633333e-01]
 [8.81166667e-01]
 [9.02433333e-01]
 [2.10933333e-01]
 [0.00000000e+00]
 [1.44333333e-02]
 [3.70966667e-01]
 [8.09266667e-01]
 [9.07600000e-01]
 [9.53733333e-01]
 [9.31633333e-01]
 [9.30366667e-01]
 [6.07300000e-01]
 [1.83066667e-01]
 [5.33333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.35200000e-01]
 [7.74566667e-01]
 [9.60833333e-01]
 [6.48400000e-01]
 [2.28866667e-01]
 [6.96666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.38666667e-02]
 [2.64666667e-01]
 [6.18900000e-01]
 [7.96200000e-01]
 [8.29766667e-01]
 [5.97933333e-01]
 [5.74700000e-01]
 [2.05966667e-01]
 [4.26666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.30833333e-01]
 [6.96266667e-01]
 [7.06233333e-01]
 [8.29766667e-01]
 [5.57333333e-01]
 [4.02866667e-01]
 [3.13033333e-01]
 [1.28166667e-01]
 [4.23333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.93333333e-03]
 [1.78433333e-01]
 [3.79433333e-01]
 [3.75233333e-01]
 [3.54066667e-01]
 [1.92900000e-01]
 [1.67666667e-02]
 [3.33333333e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.00000000e-04]
 [2.86666667e-02]
 [6.97000000e-02]
 [8.04000000e-02]
 [8.28000000e-02]
 [8.28333333e-02]
 [8.04666667e-02]
 [7.58666667e-02]
 [5.74000000e-02]
 [1.67666667e-02]
 [3.33333333e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.26666667e-03]
 [9.30666667e-02]
 [3.39300000e-01]
 [3.83733333e-01]
 [3.90233333e-01]
 [2.74900000e-01]
 [5.11933333e-01]
 [4.20900000e-01]
 [3.76766667e-01]
 [6.52000000e-02]
 [1.00000000e-04]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.30000000e-03]
 [1.54933333e-01]
 [3.28166667e-01]
 [5.02700000e-01]
 [5.86100000e-01]
 [4.40233333e-01]
 [5.66333333e-01]
 [2.12300000e-01]
 [6.03000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.13333333e-03]
 [1.88500000e-01]
 [6.96900000e-01]
 [5.36066667e-01]
 [4.37866667e-01]
 [3.77233333e-01]
 [2.66866667e-01]
 [8.25666667e-02]
 [2.68533333e-01]
 [3.12933333e-01]
 [4.77433333e-01]
 [6.67000000e-02]
 [5.01333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.96666667e-03]
 [1.77100000e-01]
 [3.93700000e-01]
 [5.02500000e-01]
 [6.47000000e-01]
 [3.82966667e-01]
 [3.78000000e-01]
 [3.83566667e-01]
 [4.38633333e-01]
 [5.06533333e-01]
 [5.61666667e-01]
 [3.48500000e-01]
 [8.61333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.80000000e-03]
 [2.94566667e-01]
 [7.83200000e-01]
 [5.00333333e-01]
 [6.83066667e-01]
 [5.24566667e-01]
 [8.94100000e-01]
 [8.00000000e-01]
 [6.40133333e-01]
 [1.37500000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.95566667e-01]
 [8.06100000e-01]
 [8.52600000e-01]
 [5.25600000e-01]
 [4.98400000e-01]
 [5.84866667e-01]
 [7.04733333e-01]
 [1.30100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.73333333e-03]
 [2.98800000e-01]
 [7.79066667e-01]
 [8.98533333e-01]
 [9.48700000e-01]
 [0.00000000e+00]
 [5.70000000e-03]
 [3.06733333e-01]
 [8.07833333e-01]
 [9.19166667e-01]
 [9.24300000e-01]
 [8.98133333e-01]
 [8.89033333e-01]
 [9.23800000e-01]
 [9.13700000e-01]
 [9.08666667e-01]
 [8.72366667e-01]
 [6.23966667e-01]
 [1.30100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.73333333e-03]
 [2.98633333e-01]
 [7.87133333e-01]
 [8.93433333e-01]
 [9.12233333e-01]
 [9.02866667e-01]
 [8.43033333e-01]
 [6.48733333e-01]
 [1.30100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.60000000e-03]
 [2.94566667e-01]
 [7.76166667e-01]
 [8.93433333e-01]
 [9.13266667e-01]
 [9.01833333e-01]
 [8.92866667e-01]
 [9.18500000e-01]
 [8.98700000e-01]
 [8.97766667e-01]
 [8.44533333e-01]
 [6.39566667e-01]
 [1.30100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.86666667e-03]
 [2.35633333e-01]
 [6.19466667e-01]
 [7.35333333e-01]
 [7.29766667e-01]
 [7.18500000e-01]
 [7.14300000e-01]
 [8.21900000e-01]
 [8.08066667e-01]
 [7.15266667e-01]
 [5.39566667e-01]
 [3.49433333e-01]
 [7.28666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.80000000e-03]
 [2.94566667e-01]
 [7.83200000e-01]
 [8.97600000e-01]
 [9.12233333e-01]
 [9.00266667e-01]
 [8.92866667e-01]
 [9.13233333e-01]
 [8.09666667e-01]
 [5.72233333e-01]
 [6.07633333e-01]
 [3.05733333e-01]
 [5.46333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.63333333e-03]
 [2.15000000e-01]
 [7.74333333e-01]
 [8.93433333e-01]
 [9.12233333e-01]
 [8.98133333e-01]
 [9.13233333e-01]
 [8.06333333e-01]
 [8.04666667e-01]
 [5.39566667e-01]
 [2.62066667e-01]
 [7.28666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.93333333e-03]
 [2.88766667e-01]
 [7.75733333e-01]
 [6.45166667e-01]
 [6.57400000e-01]
 [6.46866667e-01]
 [8.97500000e-01]
 [9.14166667e-01]
 [8.99200000e-01]
 [4.99600000e-01]
 [4.78266667e-01]
 [3.27833333e-01]
 [9.33666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.70000000e-03]
 [2.50900000e-01]
 [7.80300000e-01]
 [9.22300000e-01]
 [9.05033333e-01]
 [8.92166667e-01]
 [7.82100000e-01]
 [8.68366667e-01]
 [9.14033333e-01]
 [8.74466667e-01]
 [8.31300000e-01]
 [5.14600000e-01]
 [5.67000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.60000000e-03]
 [2.60266667e-01]
 [8.07900000e-01]
 [9.17700000e-01]
 [9.27500000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.70000000e-03]
 [2.93166667e-01]
 [8.13733333e-01]
 [9.19500000e-01]
 [9.26933333e-01]
 [9.22000000e-01]
 [0.00000000e+00]
 [2.26666667e-03]
 [2.75633333e-01]
 [7.94333333e-01]
 [9.03866667e-01]
 [9.07400000e-01]
 [8.98733333e-01]
 [0.00000000e+00]
 [2.23333333e-03]
 [2.51233333e-01]
 [7.08300000e-01]
 [8.33333333e-01]
 [9.10633333e-01]
 [9.03566667e-01]
 [0.00000000e+00]
 [2.46666667e-03]
 [2.53400000e-01]
 [7.06433333e-01]
 [8.33366667e-01]
 [9.10633333e-01]
 [0.00000000e+00]
 [2.63333333e-03]
 [2.55600000e-01]
 [7.08300000e-01]
 [0.00000000e+00]
 [2.23333333e-03]
 [2.62266667e-01]
 [7.08300000e-01]
 [8.30033333e-01]
 [8.34533333e-01]
 [0.00000000e+00]
 [2.23333333e-03]
 [2.32966667e-01]
 [5.81266667e-01]
 [7.39900000e-01]
 [8.51400000e-01]
 [0.00000000e+00]
 [4.43333333e-03]
 [2.47100000e-01]
 [5.77166667e-01]
 [7.70533333e-01]
 [5.15100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.56666667e-03]
 [2.38433333e-01]
 [5.76833333e-01]
 [7.49866667e-01]
 [8.57533333e-01]
 [8.71666667e-01]
 [8.51933333e-01]
 [8.49533333e-01]
 [8.38900000e-01]
 [8.40766667e-01]
 [6.19133333e-01]
 [4.17800000e-01]
 [4.33666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.43333333e-03]
 [1.98000000e-01]
 [5.41133333e-01]
 [6.99333333e-01]
 [8.47766667e-01]
 [7.96533333e-01]
 [8.54333333e-01]
 [8.54066667e-01]
 [8.42000000e-01]
 [8.43133333e-01]
 [7.60066667e-01]
 [4.76266667e-01]
 [4.14000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.35666667e-01]
 [5.97333333e-01]
 [7.50633333e-01]
 [8.56600000e-01]
 [8.69633333e-01]
 [8.49933333e-01]
 [8.51833333e-01]
 [5.26033333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.36666667e-03]
 [2.41600000e-01]
 [0.00000000e+00]
 [2.23333333e-03]
 [2.45200000e-01]
 [5.87933333e-01]
 [7.77966667e-01]
 [8.77433333e-01]
 [8.53266667e-01]]
(783, 1)

In [26]:
y_test_scaled_df = pd.DataFrame(y_test_scaled, index=y_test.index, columns=y_test.columns)
y_test_scaled_df

       Generación
16400    0.021400
16401    0.226800
16402    0.350033
16403    0.438233
16404    0.517867
...           ...
18273    0.245200
18274    0.587933
18275    0.777967
18276    0.877433
18278    0.853267

[783 rows x 1 columns]

In [27]:
y_scaller_all = MinMaxScaler().fit(y)
print(y_scaller_all)

MinMaxScaler()

In [28]:
y_scaled = y_scaller_all.transform(y)
print(y_scaled)
print(y_scaled.shape)

[[0.        ]
 [0.        ]
 [0.01462717]
 ...
 [0.77796667]
 [0.87743333]
 [0.85326667]]
(5214, 1)

In [29]:
y_scaled_df = pd.DataFrame(y_scaled, index=y.index, columns=y.columns)
y_scaled_df

       Generación
30       0.000000
31       0.000000
32       0.014627
33       0.196933
34       0.167691
...           ...
18273    0.245200
18274    0.587933
18275    0.777967
18276    0.877433
18278    0.853267

[5214 rows x 1 columns]

## Preparación para Redes Neuronales

In [30]:
import numpy as np

def create_sliding_window_with_index(data_X, data_y, lookback):
    X, y, indices = [], [], []
    
    # Asegurar que `data_y` tiene los mismos índices que `data_X`
    data_y = data_y.reindex(data_X.index)

    max_index = len(data_X) - lookback

    for i in range(max_index):
        X.append(data_X.iloc[i:i + lookback].values)  # Ventana de entrada
        
        # Obtener el índice correcto en `data_y`
        y_index = data_X.index[i + lookback]

        # Extraer el valor correspondiente de `data_y`
        if y_index in data_y.index:
            y_value = data_y.loc[y_index]
            if isinstance(y_value, pd.Series):  # Si devuelve una serie, extraer el valor
                y_value = y_value.iloc[0]
        else:
            y_value = np.nan  # Si no está, asignamos NaN

        y.append(y_value)
        indices.append(y_index)  # 🔹 Guardamos el índice original de `data_y`

    # Convertimos `X` en un array y `y` en DataFrame conservando sus índices originales
    X_array = np.array(X)
    y_df = pd.DataFrame(y, index=indices, columns=['y'])  # 🔹 Conservamos los índices originales

    return X_array, y_df

In [31]:
lookback = 48  # Puedes ajustar a 24, 72, etc.

# Aplicar la ventana deslizante a cada conjunto
X_train_windowed, y_train_windowed = create_sliding_window_with_index(X_train_scaled_df, y_train_scaled_df, lookback)
X_val_windowed, y_val_windowed = create_sliding_window_with_index(X_val_scaled_df, y_val_scaled_df, lookback)
X_test_windowed, y_test_windowed = create_sliding_window_with_index(X_test_scaled_df, y_test_scaled_df, lookback)

In [32]:
print(f'X_train: {X_train_windowed.shape}, y_train: {y_train_windowed.shape}')
print(f'X_val: {X_val_windowed.shape}, y_val: {y_val_windowed.shape}')
print(f'X_test: {X_test_windowed.shape}, y_test: {y_test_windowed.shape}')

X_train: (3601, 48, 9), y_train: (3601, 1)
X_val: (734, 48, 9), y_val: (734, 1)
X_test: (735, 48, 9), y_test: (735, 1)

## Optuna

In [33]:
from lightgbm import LGBMRegressor
import lightgbm as lgb
from sklearn.ensemble import RandomForestRegressor
import optuna
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import seaborn as sns
from sklearn.metrics import mean_absolute_percentage_error as mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error as mean_absolute_error
from sklearn.metrics import mean_squared_error as mean_squared_error
from sklearn.metrics import r2_score as r2_score
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping

### Optimización de LightGBM

In [34]:
# import optuna
import numpy as np
import pandas as pd
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_squared_error

# Definir la función de optimización
def objective(trial):
    # Espacio de búsqueda para los hiperparámetros
    num_leaves = trial.suggest_int('num_leaves', 10, 1000)
    subsample = trial.suggest_float('subsample', 0.1, 1.0)
    colsample_bytree = trial.suggest_float('colsample_bytree', 0.1, 1.0)
    min_data_in_leaf = trial.suggest_int('min_data_in_leaf', 10, 100)

    # Modelo LightGBM con los hiperparámetros sugeridos
    model = LGBMRegressor(
        num_leaves=num_leaves,
        subsample=subsample,
        colsample_bytree=colsample_bytree,
        min_data_in_leaf=min_data_in_leaf,
        random_state=42
    )

    # Entrenamos el modelo con los datos de entrenamiento
    model.fit(X_train_scaled_df, y_train_scaled_df)

    # Predicciones en el conjunto de validación
    y_pred = model.predict(X_val_scaled_df)
    rmse = mean_squared_error(y_val_scaled_df, y_pred)

    return rmse  # Optuna minimizará este valor

# Ejecutar la optimización con 50 iteraciones
LightGBM_study = optuna.create_study(direction="minimize")
LightGBM_study.optimize(objective, n_trials=50, n_jobs=-1)

# Obtener los mejores hiperparámetros
best_params = LightGBM_study.best_params
print("Mejores hiperparámetros:", best_params)

[I 2025-03-11 21:30:02,773] A new study created in memory with name: no-name-c7cc6fa1-4d78-405b-a08f-62bb04bf7af7
[I 2025-03-11 21:30:05,041] Trial 1 finished with value: 0.014343138831026028 and parameters: {'num_leaves': 826, 'subsample': 0.4113629776985105, 'colsample_bytree': 0.12421653820549444, 'min_data_in_leaf': 55}. Best is trial 1 with value: 0.014343138831026028.
[I 2025-03-11 21:30:05,217] Trial 7 finished with value: 0.00976090659763726 and parameters: {'num_leaves': 397, 'subsample': 0.6390782077948541, 'colsample_bytree': 0.45934163887949353, 'min_data_in_leaf': 94}. Best is trial 7 with value: 0.00976090659763726.
[I 2025-03-11 21:30:05,924] Trial 6 finished with value: 0.009761726564227113 and parameters: {'num_leaves': 729, 'subsample': 0.43301340471536287, 'colsample_bytree': 0.7224846095452567, 'min_data_in_leaf': 99}. Best is trial 7 with value: 0.00976090659763726.
[I 2025-03-11 21:30:07,140] Trial 5 finished with value: 0.010985165612611848 and parameters: {'num_leaves': 557, 'subsample': 0.7128683528487201, 'colsample_bytree': 0.2580057479512166, 'min_data_in_leaf': 33}. Best is trial 7 with value: 0.00976090659763726.
[I 2025-03-11 21:30:07,808] Trial 9 finished with value: 0.010217522785588856 and parameters: {'num_leaves': 277, 'subsample': 0.8452704083543662, 'colsample_bytree': 0.9466051803466266, 'min_data_in_leaf': 92}. Best is trial 7 with value: 0.00976090659763726.
[I 2025-03-11 21:30:08,221] Trial 10 finished with value: 0.009518229977647532 and parameters: {'num_leaves': 328, 'subsample': 0.9285041943100638, 'colsample_bytree': 0.6264465517315534, 'min_data_in_leaf': 84}. Best is trial 10 with value: 0.009518229977647532.
[I 2025-03-11 21:30:08,474] Trial 4 finished with value: 0.01001035411934257 and parameters: {'num_leaves': 587, 'subsample': 0.13395349578403745, 'colsample_bytree': 0.7329382720348574, 'min_data_in_leaf': 44}. Best is trial 10 with value: 0.009518229977647532.
[I 2025-03-11 21:30:08,918] Trial 8 finished with value: 0.009378976895183216 and parameters: {'num_leaves': 193, 'subsample': 0.46270715525666173, 'colsample_bytree': 0.46923472973289104, 'min_data_in_leaf': 53}. Best is trial 8 with value: 0.009378976895183216.
[I 2025-03-11 21:30:10,560] Trial 14 finished with value: 0.010028527427778433 and parameters: {'num_leaves': 80, 'subsample': 0.7293851690224779, 'colsample_bytree': 0.9143858423906723, 'min_data_in_leaf': 98}. Best is trial 8 with value: 0.009378976895183216.
[I 2025-03-11 21:30:10,689] Trial 11 finished with value: 0.010381048566948754 and parameters: {'num_leaves': 389, 'subsample': 0.49343848876524554, 'colsample_bytree': 0.9555108197541933, 'min_data_in_leaf': 60}. Best is trial 8 with value: 0.009378976895183216.
[I 2025-03-11 21:30:11,027] Trial 15 finished with value: 0.009976238731220114 and parameters: {'num_leaves': 926, 'subsample': 0.24757933188821882, 'colsample_bytree': 0.9599547319435578, 'min_data_in_leaf': 100}. Best is trial 8 with value: 0.009378976895183216.
[I 2025-03-11 21:30:11,464] Trial 2 finished with value: 0.00983616577410532 and parameters: {'num_leaves': 727, 'subsample': 0.12010165372777601, 'colsample_bytree': 0.5251361293824734, 'min_data_in_leaf': 31}. Best is trial 8 with value: 0.009378976895183216.
[I 2025-03-11 21:30:11,608] Trial 0 finished with value: 0.009781835506858138 and parameters: {'num_leaves': 390, 'subsample': 0.7491773354332687, 'colsample_bytree': 0.7009424213265285, 'min_data_in_leaf': 27}. Best is trial 8 with value: 0.009378976895183216.
[I 2025-03-11 21:30:11,994] Trial 3 finished with value: 0.009631916528633435 and parameters: {'num_leaves': 661, 'subsample': 0.11055297937505244, 'colsample_bytree': 0.8182765275780909, 'min_data_in_leaf': 22}. Best is trial 8 with value: 0.009378976895183216.
[I 2025-03-11 21:30:12,201] Trial 13 finished with value: 0.009812251541750163 and parameters: {'num_leaves': 591, 'subsample': 0.33178366234272727, 'colsample_bytree': 0.5985477448382892, 'min_data_in_leaf': 54}. Best is trial 8 with value: 0.009378976895183216.
[I 2025-03-11 21:30:13,137] Trial 16 finished with value: 0.00976383280466421 and parameters: {'num_leaves': 481, 'subsample': 0.6460982030932808, 'colsample_bytree': 0.4555673646001803, 'min_data_in_leaf': 95}. Best is trial 8 with value: 0.009378976895183216.
[I 2025-03-11 21:30:14,218] Trial 18 finished with value: 0.009637188280908754 and parameters: {'num_leaves': 79, 'subsample': 0.9751281757734529, 'colsample_bytree': 0.4823442809778532, 'min_data_in_leaf': 73}. Best is trial 8 with value: 0.009378976895183216.
[I 2025-03-11 21:30:14,414] Trial 17 finished with value: 0.009975080640513547 and parameters: {'num_leaves': 39, 'subsample': 0.2234957334291403, 'colsample_bytree': 0.3611834945559639, 'min_data_in_leaf': 11}. Best is trial 8 with value: 0.009378976895183216.
[I 2025-03-11 21:30:14,724] Trial 19 finished with value: 0.009912100565386802 and parameters: {'num_leaves': 51, 'subsample': 0.8845281040861275, 'colsample_bytree': 0.37837329289646304, 'min_data_in_leaf': 74}. Best is trial 8 with value: 0.009378976895183216.
[I 2025-03-11 21:30:14,846] Trial 12 finished with value: 0.009321112971070147 and parameters: {'num_leaves': 708, 'subsample': 0.3584326593589673, 'colsample_bytree': 0.4904780669222326, 'min_data_in_leaf': 27}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:15,029] Trial 20 finished with value: 0.009515433043345584 and parameters: {'num_leaves': 101, 'subsample': 0.8822905889579714, 'colsample_bytree': 0.4004445072897066, 'min_data_in_leaf': 70}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:15,040] Trial 21 finished with value: 0.009941815884579236 and parameters: {'num_leaves': 114, 'subsample': 0.9995950546415492, 'colsample_bytree': 0.38047480015269897, 'min_data_in_leaf': 75}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:15,437] Trial 22 finished with value: 0.01002197213319055 and parameters: {'num_leaves': 98, 'subsample': 0.9104309090463715, 'colsample_bytree': 0.38644913829425787, 'min_data_in_leaf': 76}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:16,730] Trial 23 finished with value: 0.009670097653181223 and parameters: {'num_leaves': 134, 'subsample': 0.9805624595448221, 'colsample_bytree': 0.3538387935944355, 'min_data_in_leaf': 71}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:17,039] Trial 25 finished with value: 0.010055326894799425 and parameters: {'num_leaves': 206, 'subsample': 0.981608346374713, 'colsample_bytree': 0.5956209133486179, 'min_data_in_leaf': 77}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:17,268] Trial 26 finished with value: 0.009626179375922502 and parameters: {'num_leaves': 215, 'subsample': 0.5953443663548845, 'colsample_bytree': 0.6251042059203761, 'min_data_in_leaf': 80}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:17,999] Trial 27 finished with value: 0.010765199466542447 and parameters: {'num_leaves': 185, 'subsample': 0.5497929591084346, 'colsample_bytree': 0.2462683007161739, 'min_data_in_leaf': 42}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:18,043] Trial 28 finished with value: 0.010683946774060782 and parameters: {'num_leaves': 228, 'subsample': 0.5374090725719918, 'colsample_bytree': 0.2569111090588483, 'min_data_in_leaf': 43}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:18,313] Trial 29 finished with value: 0.010765199466542447 and parameters: {'num_leaves': 214, 'subsample': 0.34642772060509147, 'colsample_bytree': 0.26282345037467436, 'min_data_in_leaf': 42}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:18,429] Trial 30 finished with value: 0.010683946774060782 and parameters: {'num_leaves': 208, 'subsample': 0.5445883900513333, 'colsample_bytree': 0.2601648001737442, 'min_data_in_leaf': 43}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:19,549] Trial 31 finished with value: 0.010858954825777938 and parameters: {'num_leaves': 197, 'subsample': 0.559203661599444, 'colsample_bytree': 0.2553548818805337, 'min_data_in_leaf': 46}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:20,233] Trial 32 finished with value: 0.010788320591894567 and parameters: {'num_leaves': 277, 'subsample': 0.580577661415031, 'colsample_bytree': 0.23972022657138953, 'min_data_in_leaf': 41}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:20,313] Trial 33 finished with value: 0.010780667018320261 and parameters: {'num_leaves': 198, 'subsample': 0.5148709189639616, 'colsample_bytree': 0.26397527023546474, 'min_data_in_leaf': 44}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:20,743] Trial 34 finished with value: 0.009742727839520989 and parameters: {'num_leaves': 981, 'subsample': 0.36274541386184944, 'colsample_bytree': 0.2893669477076762, 'min_data_in_leaf': 64}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:21,075] Trial 35 finished with value: 0.009788362434440449 and parameters: {'num_leaves': 898, 'subsample': 0.3798121778818888, 'colsample_bytree': 0.5310473699991193, 'min_data_in_leaf': 60}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:21,239] Trial 36 finished with value: 0.009593483355286632 and parameters: {'num_leaves': 881, 'subsample': 0.7879199686381313, 'colsample_bytree': 0.5341873461043949, 'min_data_in_leaf': 64}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:21,296] Trial 37 finished with value: 0.009567991570542764 and parameters: {'num_leaves': 996, 'subsample': 0.44791215147703406, 'colsample_bytree': 0.5229923123610258, 'min_data_in_leaf': 66}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:21,610] Trial 38 finished with value: 0.009999585190840444 and parameters: {'num_leaves': 392, 'subsample': 0.8155387654477757, 'colsample_bytree': 0.541770526265186, 'min_data_in_leaf': 86}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:22,599] Trial 41 finished with value: 0.009512557621744896 and parameters: {'num_leaves': 342, 'subsample': 0.8355320132948398, 'colsample_bytree': 0.5287467954752333, 'min_data_in_leaf': 85}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:22,855] Trial 40 finished with value: 0.009584339105561215 and parameters: {'num_leaves': 356, 'subsample': 0.8065116043304794, 'colsample_bytree': 0.6679710960203025, 'min_data_in_leaf': 65}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:23,074] Trial 39 finished with value: 0.009761513846879342 and parameters: {'num_leaves': 351, 'subsample': 0.7773565654624017, 'colsample_bytree': 0.5285152584771478, 'min_data_in_leaf': 58}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:23,280] Trial 42 finished with value: 0.009659456327393946 and parameters: {'num_leaves': 339, 'subsample': 0.8182883710887973, 'colsample_bytree': 0.661463684553964, 'min_data_in_leaf': 85}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:23,466] Trial 44 finished with value: 0.009659905956966358 and parameters: {'num_leaves': 387, 'subsample': 0.2851480898330218, 'colsample_bytree': 0.6868726850208561, 'min_data_in_leaf': 86}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:23,799] Trial 43 finished with value: 0.009518229977647532 and parameters: {'num_leaves': 392, 'subsample': 0.27852044336218945, 'colsample_bytree': 0.6638064506655342, 'min_data_in_leaf': 84}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:24,039] Trial 24 finished with value: 0.010697894650068126 and parameters: {'num_leaves': 215, 'subsample': 0.9745317719676712, 'colsample_bytree': 0.3312884331031419, 'min_data_in_leaf': 11}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:24,796] Trial 48 finished with value: 0.009897071042400262 and parameters: {'num_leaves': 480, 'subsample': 0.9116811032776733, 'colsample_bytree': 0.7795098929617703, 'min_data_in_leaf': 86}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:24,908] Trial 49 finished with value: 0.009897071042400262 and parameters: {'num_leaves': 456, 'subsample': 0.9180347266481114, 'colsample_bytree': 0.7745625109875779, 'min_data_in_leaf': 86}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:26,002] Trial 45 finished with value: 0.010021642289392398 and parameters: {'num_leaves': 783, 'subsample': 0.29826150805554486, 'colsample_bytree': 0.6583671696040109, 'min_data_in_leaf': 22}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:26,092] Trial 46 finished with value: 0.009927309280578691 and parameters: {'num_leaves': 461, 'subsample': 0.665809155798995, 'colsample_bytree': 0.6779306030469033, 'min_data_in_leaf': 25}. Best is trial 12 with value: 0.009321112971070147.
[I 2025-03-11 21:30:26,523] Trial 47 finished with value: 0.009854985874897509 and parameters: {'num_leaves': 764, 'subsample': 0.25073218311353174, 'colsample_bytree': 0.4367077989412645, 'min_data_in_leaf': 22}. Best is trial 12 with value: 0.009321112971070147.

Mejores hiperparámetros: {'num_leaves': 708, 'subsample': 0.3584326593589673, 'colsample_bytree': 0.4904780669222326, 'min_data_in_leaf': 27}

### Random Forest

In [35]:
def objective(trial):
    # Definir los hiperparámetros a optimizar
    n_estimators = trial.suggest_int("n_estimators", 100, 500, step=50)
    max_depth = trial.suggest_int("max_depth", 10, 50, step=5)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
    min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 10)
    bootstrap = trial.suggest_categorical("bootstrap", [True, False])

    # Definir el modelo con los hiperparámetros actuales
    RF_model = RandomForestRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        bootstrap=bootstrap,
        criterion="squared_error",
        random_state=0
    )

    # Entrenar el modelo
    RF_model.fit(X_train_scaled_df, y_train_scaled_df)

    # Predicciones en el conjunto de validación
    y_pred = RF_model.predict(X_val_scaled_df)
    rmse = mean_squared_error(y_val_scaled_df, y_pred)

    return rmse  # Optuna minimizará este valor

# Crear el estudio de optimización
RF_study = optuna.create_study(direction="minimize")
RF_study.optimize(objective, n_trials=50, n_jobs=-1)  # Ejecutar 50 pruebas

# Imprimir los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", RF_study.best_params)

[I 2025-03-11 21:30:26,602] A new study created in memory with name: no-name-b624b924-029c-4e3e-8cf3-7fa9bd36de9f
[I 2025-03-11 21:30:45,890] Trial 5 finished with value: 0.010791807895324695 and parameters: {'n_estimators': 250, 'max_depth': 50, 'min_samples_split': 8, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:30:47,152] Trial 4 finished with value: 0.01105918170256387 and parameters: {'n_estimators': 250, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:30:47,771] Trial 3 finished with value: 0.017960573324511436 and parameters: {'n_estimators': 150, 'max_depth': 45, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:30:49,336] Trial 0 finished with value: 0.01084451583013472 and parameters: {'n_estimators': 300, 'max_depth': 25, 'min_samples_split': 20, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:30:50,013] Trial 2 finished with value: 0.010852258130041228 and parameters: {'n_estimators': 300, 'max_depth': 45, 'min_samples_split': 20, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:00,006] Trial 12 finished with value: 0.01089318515801608 and parameters: {'n_estimators': 150, 'max_depth': 20, 'min_samples_split': 17, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:01,790] Trial 1 finished with value: 0.010819711990007407 and parameters: {'n_estimators': 500, 'max_depth': 25, 'min_samples_split': 9, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:04,873] Trial 7 finished with value: 0.010860151080945391 and parameters: {'n_estimators': 500, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:07,313] Trial 6 finished with value: 0.010909514475481101 and parameters: {'n_estimators': 450, 'max_depth': 30, 'min_samples_split': 14, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:09,015] Trial 11 finished with value: 0.011013637999381246 and parameters: {'n_estimators': 250, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:14,666] Trial 10 finished with value: 0.010833522397939454 and parameters: {'n_estimators': 350, 'max_depth': 40, 'min_samples_split': 12, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:14,799] Trial 13 finished with value: 0.01305946262508716 and parameters: {'n_estimators': 150, 'max_depth': 50, 'min_samples_split': 14, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:19,526] Trial 16 finished with value: 0.015342429737633428 and parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 17, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:24,411] Trial 9 finished with value: 0.017736159250203998 and parameters: {'n_estimators': 250, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:31,680] Trial 14 finished with value: 0.013433951172077303 and parameters: {'n_estimators': 350, 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:33,417] Trial 15 finished with value: 0.010828476535711654 and parameters: {'n_estimators': 400, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:35,539] Trial 8 finished with value: 0.014385920757504007 and parameters: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:50,868] Trial 20 finished with value: 0.010819094037914131 and parameters: {'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:51,711] Trial 18 finished with value: 0.012980717687403264 and parameters: {'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 2, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:52,620] Trial 17 finished with value: 0.01438604770169501 and parameters: {'n_estimators': 400, 'max_depth': 50, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:54,596] Trial 19 finished with value: 0.01438604770169501 and parameters: {'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:31:56,803] Trial 21 finished with value: 0.010819094037914131 and parameters: {'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:32:07,700] Trial 22 finished with value: 0.010800370150214362 and parameters: {'n_estimators': 450, 'max_depth': 35, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:32:08,623] Trial 26 finished with value: 0.010866546232015358 and parameters: {'n_estimators': 200, 'max_depth': 50, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:32:09,870] Trial 24 finished with value: 0.010929583234737025 and parameters: {'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:32:10,608] Trial 27 finished with value: 0.010940252599214714 and parameters: {'n_estimators': 200, 'max_depth': 35, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:32:14,252] Trial 23 finished with value: 0.010818945850148615 and parameters: {'n_estimators': 500, 'max_depth': 35, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:32:21,851] Trial 25 finished with value: 0.010819094037914131 and parameters: {'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:32:26,690] Trial 29 finished with value: 0.010913968683135386 and parameters: {'n_estimators': 350, 'max_depth': 35, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:32:33,171] Trial 28 finished with value: 0.011079762799402851 and parameters: {'n_estimators': 450, 'max_depth': 30, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.010791807895324695.
[I 2025-03-11 21:32:43,262] Trial 32 finished with value: 0.010767257960981309 and parameters: {'n_estimators': 450, 'max_depth': 40, 'min_samples_split': 5, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:32:45,907] Trial 33 finished with value: 0.010767257960981309 and parameters: {'n_estimators': 450, 'max_depth': 45, 'min_samples_split': 7, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:32:48,078] Trial 30 finished with value: 0.011079762799402851 and parameters: {'n_estimators': 450, 'max_depth': 40, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:32:50,369] Trial 34 finished with value: 0.010767257960981309 and parameters: {'n_estimators': 450, 'max_depth': 45, 'min_samples_split': 6, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:32:51,319] Trial 31 finished with value: 0.011079762799402851 and parameters: {'n_estimators': 450, 'max_depth': 40, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:32:56,493] Trial 35 finished with value: 0.010767257960981309 and parameters: {'n_estimators': 450, 'max_depth': 45, 'min_samples_split': 6, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:33:01,815] Trial 36 finished with value: 0.010767257960981309 and parameters: {'n_estimators': 450, 'max_depth': 45, 'min_samples_split': 6, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:33:06,916] Trial 37 finished with value: 0.010767257960981309 and parameters: {'n_estimators': 450, 'max_depth': 45, 'min_samples_split': 7, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:33:08,951] Trial 40 finished with value: 0.010775329089845447 and parameters: {'n_estimators': 300, 'max_depth': 45, 'min_samples_split': 8, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:33:11,707] Trial 42 finished with value: 0.010775329089845447 and parameters: {'n_estimators': 300, 'max_depth': 45, 'min_samples_split': 8, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:33:12,050] Trial 41 finished with value: 0.010775329089845447 and parameters: {'n_estimators': 300, 'max_depth': 45, 'min_samples_split': 8, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:33:16,409] Trial 38 finished with value: 0.010767257960981309 and parameters: {'n_estimators': 450, 'max_depth': 45, 'min_samples_split': 7, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:33:19,192] Trial 39 finished with value: 0.010782807699328305 and parameters: {'n_estimators': 450, 'max_depth': 45, 'min_samples_split': 8, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:33:30,986] Trial 43 finished with value: 0.010772690173951147 and parameters: {'n_estimators': 500, 'max_depth': 45, 'min_samples_split': 8, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:33:35,393] Trial 44 finished with value: 0.010772690173951147 and parameters: {'n_estimators': 500, 'max_depth': 45, 'min_samples_split': 8, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:33:39,208] Trial 45 finished with value: 0.010772690173951147 and parameters: {'n_estimators': 500, 'max_depth': 45, 'min_samples_split': 8, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:33:40,232] Trial 46 finished with value: 0.010772690173951147 and parameters: {'n_estimators': 500, 'max_depth': 45, 'min_samples_split': 9, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:33:41,915] Trial 47 finished with value: 0.010772690173951147 and parameters: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 9, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:33:42,355] Trial 48 finished with value: 0.010772690173951147 and parameters: {'n_estimators': 500, 'max_depth': 45, 'min_samples_split': 5, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.
[I 2025-03-11 21:33:43,329] Trial 49 finished with value: 0.010772690173951147 and parameters: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 5, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 32 with value: 0.010767257960981309.

Mejores hiperparámetros: {'n_estimators': 450, 'max_depth': 40, 'min_samples_split': 5, 'min_samples_leaf': 6, 'bootstrap': True}

### CTNET

In [36]:
def compile_and_fit(model, xtrain=X_train_windowed, ytrain=y_train_windowed, learning_rate=0.0001):
    model.compile(loss=[tf.keras.losses.MeanSquaredError()],
                  optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                  metrics=[tf.keras.metrics.RootMeanSquaredError(), tf.keras.metrics.MeanAbsolutePercentageError(), tf.keras.metrics.MeanAbsoluteError()])
    
    history = model.fit(xtrain, ytrain, epochs=50,
                        batch_size=512, validation_split=0.2, verbose=1)
    return history

def Loss(train_loss, valid_loss):
    plt.plot(train_loss)
    plt.plot(valid_loss)
    plt.rcParams["figure.figsize"] = (15, 3)
    plt.title('Model Losses')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(['Train Loss', 'Validation Loss'], loc='upper left')
    plt.savefig('out/loss_plot.png')
    plt.show()

def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    x = layers.LayerNormalization()(inputs)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=128, kernel_size=2, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(norm_x, norm_x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    return norm_x

# Construir modelo con hiperparámetros sugeridos
def build_model(input_shape, head_size, num_heads, ff_dim, num_transformer_blocks, mlp_units, dropout, mlp_dropout):
    inputs = tf.keras.Input(shape=input_shape)
    x = inputs

    for _ in range(num_transformer_blocks):
        x = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)

    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(x, x)
    x = layers.LayerNormalization(epsilon=1e-6)(x)
    x = layers.GlobalAveragePooling1D(data_format="channels_first")(x)
    
    for units in mlp_units:
        x = layers.Dense(units, activation="relu")(x)

    x = layers.Dropout(mlp_dropout)(x)
    outputs = layers.Dense(1)(x)
    return tf.keras.Model(inputs, outputs)

In [34]:
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [38]:
# Definir la función objetivo para Optuna
def objective(trial):
    try:
        # Hiperparámetros a optimizar
        head_size = trial.suggest_int("head_size", 2, 8)
        num_heads = trial.suggest_int("num_heads", 2, 8)
        ff_dim = trial.suggest_int("ff_dim", 16, 128, step=16)
        num_transformer_blocks = trial.suggest_int("num_transformer_blocks", 1, 5)
        mlp_units = [trial.suggest_int("mlp_units_1", 64, 512, step=64),
                     trial.suggest_int("mlp_units_2", 32, 256, step=32)]
        dropout = trial.suggest_float("dropout", 0.1, 0.5)
        mlp_dropout = trial.suggest_float("mlp_dropout", 0.1, 0.5)
        learning_rate = trial.suggest_loguniform("learning_rate", 1e-4, 1e-2)
        batch_size = trial.suggest_categorical("batch_size", [128, 256, 512])

        # Construir el modelo
        model = build_model(
            input_shape=(X_train_windowed.shape[1], X_train_windowed.shape[2]),
            head_size=head_size,
            num_heads=num_heads,
            ff_dim=ff_dim,
            num_transformer_blocks=num_transformer_blocks,
            mlp_units=mlp_units,
            dropout=dropout,
            mlp_dropout=mlp_dropout
        )

        # Compilar el modelo
        model.compile(
            loss=tf.keras.losses.MeanSquaredError(),
            optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
            metrics=[tf.keras.metrics.RootMeanSquaredError()]
        )

        # Definir Early Stopping para evitar sobreajuste y consumo innecesario de GPU
        early_stop = tf.keras.callbacks.EarlyStopping(
            monitor="val_loss",
            patience=15,  # 🔹 Detener si no mejora en 15 epochs
            restore_best_weights=True,
            verbose=1
        )

        # Entrenar el modelo con GPU
        history = model.fit(
            X_train_windowed, y_train_windowed,
            epochs=100,
            batch_size=batch_size,
            validation_data=(X_val_windowed, y_val_windowed),
            callbacks=[early_stop],
            verbose=0
        )

        # Obtener la mejor pérdida de validación
        val_loss = min(history.history["val_loss"])
        return val_loss  # Minimizar el error MSE

    except Exception as e:
        print(f"🚨 Error en Optuna: {e}")
        return np.inf  # Si falla, devolver un valor alto para que Optuna lo ignore

# Crear el estudio de optimización con paralelización
CTNET_study = optuna.create_study(direction="minimize")
CTNET_study.optimize(objective, n_trials=50, n_jobs=-1)  # 🔥 Usa 4 hilos para evitar saturación de VRAM

# Imprimir los mejores hiperparámetros encontrados
print("✅ Mejores hiperparámetros:", CTNET_study.best_params)

[I 2025-03-11 21:33:43,908] A new study created in memory with name: no-name-2b26bac5-3084-4f1b-99b8-a57253ec5a4a

Epoch 23: early stopping
Restoring model weights from the end of the best epoch: 8.

[I 2025-03-11 21:38:26,765] Trial 5 finished with value: 0.13148528337478638 and parameters: {'head_size': 5, 'num_heads': 5, 'ff_dim': 112, 'num_transformer_blocks': 1, 'mlp_units_1': 256, 'mlp_units_2': 256, 'dropout': 0.1464609051576174, 'mlp_dropout': 0.31120598758948154, 'learning_rate': 0.002300860263595248, 'batch_size': 256}. Best is trial 5 with value: 0.13148528337478638.

Epoch 47: early stopping
Restoring model weights from the end of the best epoch: 32.

[I 2025-03-11 21:58:27,589] Trial 0 finished with value: 0.0580473318696022 and parameters: {'head_size': 4, 'num_heads': 3, 'ff_dim': 112, 'num_transformer_blocks': 1, 'mlp_units_1': 448, 'mlp_units_2': 224, 'dropout': 0.28870658692025264, 'mlp_dropout': 0.4301413362929669, 'learning_rate': 0.000753151615081156, 'batch_size': 128}. Best is trial 0 with value: 0.0580473318696022.

Epoch 17: early stopping
Restoring model weights from the end of the best epoch: 2.

[I 2025-03-11 22:17:42,653] Trial 2 finished with value: 0.12630531191825867 and parameters: {'head_size': 6, 'num_heads': 6, 'ff_dim': 16, 'num_transformer_blocks': 5, 'mlp_units_1': 192, 'mlp_units_2': 96, 'dropout': 0.41138767119689734, 'mlp_dropout': 0.4224716659543518, 'learning_rate': 0.0009710611793073988, 'batch_size': 512}. Best is trial 0 with value: 0.0580473318696022.

Epoch 17: early stopping
Restoring model weights from the end of the best epoch: 2.

[I 2025-03-11 22:20:58,159] Trial 6 finished with value: 0.1299431174993515 and parameters: {'head_size': 7, 'num_heads': 8, 'ff_dim': 32, 'num_transformer_blocks': 5, 'mlp_units_1': 192, 'mlp_units_2': 224, 'dropout': 0.4983016978955346, 'mlp_dropout': 0.4203513350619533, 'learning_rate': 0.0034960881732847993, 'batch_size': 512}. Best is trial 0 with value: 0.0580473318696022.

Epoch 17: early stopping
Restoring model weights from the end of the best epoch: 2.

[I 2025-03-11 22:28:27,373] Trial 7 finished with value: 0.13108006119728088 and parameters: {'head_size': 4, 'num_heads': 3, 'ff_dim': 128, 'num_transformer_blocks': 4, 'mlp_units_1': 320, 'mlp_units_2': 224, 'dropout': 0.12216308678380834, 'mlp_dropout': 0.4472227784469156, 'learning_rate': 0.002188887171910549, 'batch_size': 128}. Best is trial 0 with value: 0.0580473318696022.

Epoch 41: early stopping
Restoring model weights from the end of the best epoch: 26.

[I 2025-03-11 22:50:59,361] Trial 11 finished with value: 0.05894818902015686 and parameters: {'head_size': 6, 'num_heads': 5, 'ff_dim': 64, 'num_transformer_blocks': 1, 'mlp_units_1': 64, 'mlp_units_2': 96, 'dropout': 0.21593840914990384, 'mlp_dropout': 0.2674418967344234, 'learning_rate': 0.0013858756701135154, 'batch_size': 256}. Best is trial 0 with value: 0.0580473318696022.

Epoch 45: early stopping
Restoring model weights from the end of the best epoch: 30.

[I 2025-03-11 22:51:34,124] Trial 4 finished with value: 0.07548952847719193 and parameters: {'head_size': 7, 'num_heads': 6, 'ff_dim': 80, 'num_transformer_blocks': 3, 'mlp_units_1': 256, 'mlp_units_2': 224, 'dropout': 0.28843205193110566, 'mlp_dropout': 0.3155521375862558, 'learning_rate': 0.001884599380717185, 'batch_size': 256}. Best is trial 0 with value: 0.0580473318696022.

Epoch 40: early stopping
Restoring model weights from the end of the best epoch: 25.

[I 2025-03-11 22:53:44,427] Trial 10 finished with value: 0.0624203123152256 and parameters: {'head_size': 6, 'num_heads': 2, 'ff_dim': 128, 'num_transformer_blocks': 1, 'mlp_units_1': 448, 'mlp_units_2': 64, 'dropout': 0.4476055162642856, 'mlp_dropout': 0.41471638456954807, 'learning_rate': 0.0004244598200146454, 'batch_size': 128}. Best is trial 0 with value: 0.0580473318696022.

Restoring model weights from the end of the best epoch: 99.

[I 2025-03-11 23:11:37,203] Trial 12 finished with value: 0.11080221831798553 and parameters: {'head_size': 5, 'num_heads': 3, 'ff_dim': 32, 'num_transformer_blocks': 1, 'mlp_units_1': 64, 'mlp_units_2': 32, 'dropout': 0.20232676762646903, 'mlp_dropout': 0.38604962698945855, 'learning_rate': 0.00013336628793757179, 'batch_size': 512}. Best is trial 0 with value: 0.0580473318696022.

Restoring model weights from the end of the best epoch: 98.

[I 2025-03-11 23:24:53,318] Trial 8 finished with value: 0.1187548115849495 and parameters: {'head_size': 7, 'num_heads': 3, 'ff_dim': 32, 'num_transformer_blocks': 3, 'mlp_units_1': 64, 'mlp_units_2': 224, 'dropout': 0.39912338167713635, 'mlp_dropout': 0.25528877666579786, 'learning_rate': 0.00015503400718734788, 'batch_size': 512}. Best is trial 0 with value: 0.0580473318696022.

Epoch 32: early stopping
Restoring model weights from the end of the best epoch: 17.

[I 2025-03-11 23:41:05,723] Trial 14 finished with value: 0.12665022909641266 and parameters: {'head_size': 6, 'num_heads': 5, 'ff_dim': 32, 'num_transformer_blocks': 2, 'mlp_units_1': 128, 'mlp_units_2': 192, 'dropout': 0.33416677017115803, 'mlp_dropout': 0.10451192248416868, 'learning_rate': 0.004227232088122692, 'batch_size': 128}. Best is trial 0 with value: 0.0580473318696022.

Epoch 46: early stopping
Restoring model weights from the end of the best epoch: 31.

[I 2025-03-11 23:42:38,240] Trial 3 finished with value: 0.0622117780148983 and parameters: {'head_size': 8, 'num_heads': 3, 'ff_dim': 96, 'num_transformer_blocks': 4, 'mlp_units_1': 320, 'mlp_units_2': 96, 'dropout': 0.17806210511155085, 'mlp_dropout': 0.4552215818504237, 'learning_rate': 0.00043300802862175327, 'batch_size': 128}. Best is trial 0 with value: 0.0580473318696022.

Epoch 21: early stopping
Restoring model weights from the end of the best epoch: 6.

[I 2025-03-11 23:57:17,241] Trial 17 finished with value: 0.13012170791625977 and parameters: {'head_size': 2, 'num_heads': 2, 'ff_dim': 96, 'num_transformer_blocks': 2, 'mlp_units_1': 512, 'mlp_units_2': 160, 'dropout': 0.32970545088930425, 'mlp_dropout': 0.11172696891391537, 'learning_rate': 0.0077178127345578825, 'batch_size': 128}. Best is trial 0 with value: 0.0580473318696022.

Epoch 47: early stopping
Restoring model weights from the end of the best epoch: 32.

[I 2025-03-12 00:02:33,610] Trial 13 finished with value: 0.05512185022234917 and parameters: {'head_size': 3, 'num_heads': 4, 'ff_dim': 112, 'num_transformer_blocks': 2, 'mlp_units_1': 192, 'mlp_units_2': 160, 'dropout': 0.47748391402531964, 'mlp_dropout': 0.18066226632718926, 'learning_rate': 0.0016453081825454632, 'batch_size': 128}. Best is trial 13 with value: 0.05512185022234917.

Epoch 16: early stopping
Restoring model weights from the end of the best epoch: 1.

[I 2025-03-12 00:03:45,430] Trial 19 finished with value: 0.1299910843372345 and parameters: {'head_size': 4, 'num_heads': 4, 'ff_dim': 64, 'num_transformer_blocks': 2, 'mlp_units_1': 512, 'mlp_units_2': 160, 'dropout': 0.255927258229169, 'mlp_dropout': 0.23783941324198482, 'learning_rate': 0.009720756359542003, 'batch_size': 256}. Best is trial 13 with value: 0.05512185022234917.

Epoch 61: early stopping
Restoring model weights from the end of the best epoch: 46.

[I 2025-03-12 00:20:14,965] Trial 1 finished with value: 0.054574742913246155 and parameters: {'head_size': 4, 'num_heads': 4, 'ff_dim': 112, 'num_transformer_blocks': 5, 'mlp_units_1': 512, 'mlp_units_2': 256, 'dropout': 0.22279281658407324, 'mlp_dropout': 0.4841314918013644, 'learning_rate': 0.0013263816449141145, 'batch_size': 256}. Best is trial 1 with value: 0.054574742913246155.

Epoch 46: early stopping
Restoring model weights from the end of the best epoch: 31.

[I 2025-03-12 00:42:34,419] Trial 18 finished with value: 0.12884877622127533 and parameters: {'head_size': 2, 'num_heads': 4, 'ff_dim': 80, 'num_transformer_blocks': 2, 'mlp_units_1': 512, 'mlp_units_2': 128, 'dropout': 0.2413453328061067, 'mlp_dropout': 0.1938203382156508, 'learning_rate': 0.009653241011355774, 'batch_size': 256}. Best is trial 1 with value: 0.054574742913246155.

Epoch 59: early stopping
Restoring model weights from the end of the best epoch: 44.

[I 2025-03-12 00:53:36,980] Trial 9 finished with value: 0.05711197480559349 and parameters: {'head_size': 6, 'num_heads': 8, 'ff_dim': 64, 'num_transformer_blocks': 5, 'mlp_units_1': 256, 'mlp_units_2': 224, 'dropout': 0.2635363471099744, 'mlp_dropout': 0.47828680685958114, 'learning_rate': 0.0007247286307921849, 'batch_size': 256}. Best is trial 1 with value: 0.054574742913246155.

Epoch 65: early stopping
Restoring model weights from the end of the best epoch: 50.

[I 2025-03-12 00:57:37,792] Trial 15 finished with value: 0.059092726558446884 and parameters: {'head_size': 5, 'num_heads': 7, 'ff_dim': 64, 'num_transformer_blocks': 3, 'mlp_units_1': 384, 'mlp_units_2': 128, 'dropout': 0.3054182038255029, 'mlp_dropout': 0.2037791755601589, 'learning_rate': 0.0005207844053326504, 'batch_size': 256}. Best is trial 1 with value: 0.054574742913246155.

Epoch 35: early stopping
Restoring model weights from the end of the best epoch: 20.

[I 2025-03-12 01:11:02,438] Trial 21 finished with value: 0.0567672960460186 and parameters: {'head_size': 3, 'num_heads': 4, 'ff_dim': 112, 'num_transformer_blocks': 2, 'mlp_units_1': 384, 'mlp_units_2': 160, 'dropout': 0.263374076642843, 'mlp_dropout': 0.1819737550576494, 'learning_rate': 0.0007010310419994547, 'batch_size': 128}. Best is trial 1 with value: 0.054574742913246155.

Epoch 48: early stopping
Restoring model weights from the end of the best epoch: 33.

[I 2025-03-12 01:14:02,444] Trial 16 finished with value: 0.06360657513141632 and parameters: {'head_size': 2, 'num_heads': 2, 'ff_dim': 80, 'num_transformer_blocks': 5, 'mlp_units_1': 192, 'mlp_units_2': 224, 'dropout': 0.4747026941696614, 'mlp_dropout': 0.38602473116104474, 'learning_rate': 0.0007214470844172036, 'batch_size': 256}. Best is trial 1 with value: 0.054574742913246155.

Epoch 58: early stopping
Restoring model weights from the end of the best epoch: 43.

[I 2025-03-12 01:20:19,013] Trial 20 finished with value: 0.056842658668756485 and parameters: {'head_size': 3, 'num_heads': 4, 'ff_dim': 64, 'num_transformer_blocks': 2, 'mlp_units_1': 448, 'mlp_units_2': 128, 'dropout': 0.24454379089904782, 'mlp_dropout': 0.21447860569030527, 'learning_rate': 0.0007853508804578507, 'batch_size': 256}. Best is trial 1 with value: 0.054574742913246155.

Epoch 48: early stopping
Restoring model weights from the end of the best epoch: 33.

[I 2025-03-12 01:43:56,025] Trial 22 finished with value: 0.05839434638619423 and parameters: {'head_size': 2, 'num_heads': 4, 'ff_dim': 112, 'num_transformer_blocks': 2, 'mlp_units_1': 384, 'mlp_units_2': 128, 'dropout': 0.36703298334624684, 'mlp_dropout': 0.17785430507604488, 'learning_rate': 0.0007271400474320339, 'batch_size': 128}. Best is trial 1 with value: 0.054574742913246155.

Epoch 30: early stopping
Restoring model weights from the end of the best epoch: 15.

[I 2025-03-12 03:12:02,023] Trial 28 finished with value: 0.061728838831186295 and parameters: {'head_size': 3, 'num_heads': 4, 'ff_dim': 112, 'num_transformer_blocks': 4, 'mlp_units_1': 384, 'mlp_units_2': 160, 'dropout': 0.3623671809892266, 'mlp_dropout': 0.15390971829552672, 'learning_rate': 0.0003006058834530594, 'batch_size': 128}. Best is trial 1 with value: 0.054574742913246155.

Epoch 31: early stopping
Restoring model weights from the end of the best epoch: 16.

[I 2025-03-12 03:23:54,170] Trial 29 finished with value: 0.05883881077170372 and parameters: {'head_size': 3, 'num_heads': 4, 'ff_dim': 112, 'num_transformer_blocks': 4, 'mlp_units_1': 384, 'mlp_units_2': 192, 'dropout': 0.35997046751456185, 'mlp_dropout': 0.16018946019120867, 'learning_rate': 0.00025098777728302716, 'batch_size': 128}. Best is trial 1 with value: 0.054574742913246155.

Epoch 69: early stopping
Restoring model weights from the end of the best epoch: 54.

[I 2025-03-12 03:25:13,384] Trial 23 finished with value: 0.05633736029267311 and parameters: {'head_size': 2, 'num_heads': 4, 'ff_dim': 96, 'num_transformer_blocks': 4, 'mlp_units_1': 384, 'mlp_units_2': 128, 'dropout': 0.3634633699674429, 'mlp_dropout': 0.1783255164734182, 'learning_rate': 0.0005491526258757525, 'batch_size': 256}. Best is trial 1 with value: 0.054574742913246155.

Epoch 38: early stopping
Restoring model weights from the end of the best epoch: 23.

[I 2025-03-12 03:27:21,296] Trial 26 finished with value: 0.0660378634929657 and parameters: {'head_size': 3, 'num_heads': 4, 'ff_dim': 112, 'num_transformer_blocks': 4, 'mlp_units_1': 384, 'mlp_units_2': 256, 'dropout': 0.3790429491710655, 'mlp_dropout': 0.352683574440523, 'learning_rate': 0.0002794290505625246, 'batch_size': 128}. Best is trial 1 with value: 0.054574742913246155.

Epoch 54: early stopping
Restoring model weights from the end of the best epoch: 39.

[I 2025-03-12 03:31:21,904] Trial 24 finished with value: 0.060225166380405426 and parameters: {'head_size': 3, 'num_heads': 7, 'ff_dim': 112, 'num_transformer_blocks': 4, 'mlp_units_1': 384, 'mlp_units_2': 256, 'dropout': 0.4986074216140291, 'mlp_dropout': 0.4977772787379526, 'learning_rate': 0.0006230564525093356, 'batch_size': 256}. Best is trial 1 with value: 0.054574742913246155.

Epoch 38: early stopping
Restoring model weights from the end of the best epoch: 23.

[I 2025-03-12 03:35:47,046] Trial 25 finished with value: 0.05705545097589493 and parameters: {'head_size': 3, 'num_heads': 6, 'ff_dim': 112, 'num_transformer_blocks': 4, 'mlp_units_1': 384, 'mlp_units_2': 256, 'dropout': 0.3596039244085, 'mlp_dropout': 0.16302721166629558, 'learning_rate': 0.0004246193458002673, 'batch_size': 128}. Best is trial 1 with value: 0.054574742913246155.

Epoch 40: early stopping
Restoring model weights from the end of the best epoch: 25.

[I 2025-03-12 04:53:01,433] Trial 30 finished with value: 0.0661107525229454 and parameters: {'head_size': 3, 'num_heads': 6, 'ff_dim': 96, 'num_transformer_blocks': 4, 'mlp_units_1': 384, 'mlp_units_2': 192, 'dropout': 0.1690219533263954, 'mlp_dropout': 0.15747748338029166, 'learning_rate': 0.00027169567110988345, 'batch_size': 128}. Best is trial 1 with value: 0.054574742913246155.

Epoch 27: early stopping
Restoring model weights from the end of the best epoch: 12.

[I 2025-03-12 05:02:13,707] Trial 31 finished with value: 0.06732448935508728 and parameters: {'head_size': 3, 'num_heads': 6, 'ff_dim': 96, 'num_transformer_blocks': 3, 'mlp_units_1': 128, 'mlp_units_2': 192, 'dropout': 0.17324835675529807, 'mlp_dropout': 0.15290012983271967, 'learning_rate': 0.0013853111952285458, 'batch_size': 128}. Best is trial 1 with value: 0.054574742913246155.

Epoch 31: early stopping
Restoring model weights from the end of the best epoch: 16.

[I 2025-03-12 05:29:10,135] Trial 32 finished with value: 0.054570332169532776 and parameters: {'head_size': 3, 'num_heads': 5, 'ff_dim': 96, 'num_transformer_blocks': 3, 'mlp_units_1': 128, 'mlp_units_2': 256, 'dropout': 0.17198806110691728, 'mlp_dropout': 0.3490576988607602, 'learning_rate': 0.0016551122149173678, 'batch_size': 128}. Best is trial 32 with value: 0.054570332169532776.

Epoch 64: early stopping
Restoring model weights from the end of the best epoch: 49.

[I 2025-03-12 06:16:51,796] Trial 27 finished with value: 0.05769399181008339 and parameters: {'head_size': 3, 'num_heads': 6, 'ff_dim': 96, 'num_transformer_blocks': 4, 'mlp_units_1': 192, 'mlp_units_2': 256, 'dropout': 0.3739310752267635, 'mlp_dropout': 0.15246057694421083, 'learning_rate': 0.0002528129134589697, 'batch_size': 128}. Best is trial 32 with value: 0.054570332169532776.

Epoch 58: early stopping
Restoring model weights from the end of the best epoch: 43.

[I 2025-03-12 06:20:47,445] Trial 34 finished with value: 0.05704028531908989 and parameters: {'head_size': 4, 'num_heads': 5, 'ff_dim': 96, 'num_transformer_blocks': 3, 'mlp_units_1': 128, 'mlp_units_2': 192, 'dropout': 0.4407563751925661, 'mlp_dropout': 0.49835848159186585, 'learning_rate': 0.001202511576078255, 'batch_size': 256}. Best is trial 32 with value: 0.054570332169532776.

Epoch 57: early stopping
Restoring model weights from the end of the best epoch: 42.

[I 2025-03-12 06:27:41,719] Trial 35 finished with value: 0.05580049380660057 and parameters: {'head_size': 4, 'num_heads': 6, 'ff_dim': 96, 'num_transformer_blocks': 3, 'mlp_units_1': 128, 'mlp_units_2': 192, 'dropout': 0.4369260664032254, 'mlp_dropout': 0.13516912153116944, 'learning_rate': 0.001413938659347211, 'batch_size': 256}. Best is trial 32 with value: 0.054570332169532776.

Epoch 47: early stopping
Restoring model weights from the end of the best epoch: 32.

[I 2025-03-12 06:28:18,499] Trial 33 finished with value: 0.057858120650053024 and parameters: {'head_size': 4, 'num_heads': 6, 'ff_dim': 96, 'num_transformer_blocks': 4, 'mlp_units_1': 128, 'mlp_units_2': 256, 'dropout': 0.4203642265045819, 'mlp_dropout': 0.35753675086349995, 'learning_rate': 0.0013558655752775061, 'batch_size': 256}. Best is trial 32 with value: 0.054570332169532776.

Epoch 17: early stopping
Restoring model weights from the end of the best epoch: 2.

[I 2025-03-12 07:06:53,883] Trial 43 finished with value: 0.13036158680915833 and parameters: {'head_size': 4, 'num_heads': 5, 'ff_dim': 128, 'num_transformer_blocks': 3, 'mlp_units_1': 192, 'mlp_units_2': 192, 'dropout': 0.11184690594977276, 'mlp_dropout': 0.2888121692413763, 'learning_rate': 0.0031102677113141286, 'batch_size': 512}. Best is trial 32 with value: 0.054570332169532776.

Epoch 17: early stopping
Restoring model weights from the end of the best epoch: 2.

[I 2025-03-12 07:09:27,430] Trial 42 finished with value: 0.1283719688653946 and parameters: {'head_size': 4, 'num_heads': 7, 'ff_dim': 128, 'num_transformer_blocks': 3, 'mlp_units_1': 128, 'mlp_units_2': 256, 'dropout': 0.4323670312648127, 'mlp_dropout': 0.340795173097195, 'learning_rate': 0.0029921799047970786, 'batch_size': 512}. Best is trial 32 with value: 0.054570332169532776.

Epoch 16: early stopping
Restoring model weights from the end of the best epoch: 1.

[I 2025-03-12 07:17:31,439] Trial 41 finished with value: 0.1288255751132965 and parameters: {'head_size': 4, 'num_heads': 5, 'ff_dim': 128, 'num_transformer_blocks': 5, 'mlp_units_1': 448, 'mlp_units_2': 32, 'dropout': 0.14056230341484466, 'mlp_dropout': 0.28173177379571945, 'learning_rate': 0.0033223797103196554, 'batch_size': 512}. Best is trial 32 with value: 0.054570332169532776.

Epoch 16: early stopping
Restoring model weights from the end of the best epoch: 1.

[I 2025-03-12 07:55:12,997] Trial 44 finished with value: 0.126102477312088 and parameters: {'head_size': 5, 'num_heads': 7, 'ff_dim': 80, 'num_transformer_blocks': 3, 'mlp_units_1': 256, 'mlp_units_2': 224, 'dropout': 0.47126339725463834, 'mlp_dropout': 0.1161281477046666, 'learning_rate': 0.0017796205219734484, 'batch_size': 512}. Best is trial 32 with value: 0.054570332169532776.

Epoch 56: early stopping
Restoring model weights from the end of the best epoch: 41.

[I 2025-03-12 08:03:46,756] Trial 37 finished with value: 0.05449604615569115 and parameters: {'head_size': 4, 'num_heads': 5, 'ff_dim': 128, 'num_transformer_blocks': 3, 'mlp_units_1': 128, 'mlp_units_2': 64, 'dropout': 0.4286343216371147, 'mlp_dropout': 0.13353655841776407, 'learning_rate': 0.0013069899308779398, 'batch_size': 256}. Best is trial 37 with value: 0.05449604615569115.

Epoch 84: early stopping
Restoring model weights from the end of the best epoch: 69.

[I 2025-03-12 08:10:29,083] Trial 36 finished with value: 0.0535263866186142 and parameters: {'head_size': 4, 'num_heads': 5, 'ff_dim': 96, 'num_transformer_blocks': 3, 'mlp_units_1': 448, 'mlp_units_2': 192, 'dropout': 0.43412882914440787, 'mlp_dropout': 0.13725848204376, 'learning_rate': 0.0012921595968464045, 'batch_size': 256}. Best is trial 36 with value: 0.0535263866186142.

Epoch 19: early stopping
Restoring model weights from the end of the best epoch: 4.

[I 2025-03-12 08:33:27,366] Trial 46 finished with value: 0.12822362780570984 and parameters: {'head_size': 5, 'num_heads': 5, 'ff_dim': 80, 'num_transformer_blocks': 3, 'mlp_units_1': 192, 'mlp_units_2': 224, 'dropout': 0.47574289353122723, 'mlp_dropout': 0.12960660128210394, 'learning_rate': 0.0019500478102417785, 'batch_size': 256}. Best is trial 36 with value: 0.0535263866186142.

Epoch 46: early stopping
Restoring model weights from the end of the best epoch: 31.

[I 2025-03-12 09:01:25,102] Trial 40 finished with value: 0.05336686596274376 and parameters: {'head_size': 4, 'num_heads': 5, 'ff_dim': 128, 'num_transformer_blocks': 3, 'mlp_units_1': 128, 'mlp_units_2': 64, 'dropout': 0.10435760102849667, 'mlp_dropout': 0.27390486046392415, 'learning_rate': 0.001055563359247843, 'batch_size': 256}. Best is trial 40 with value: 0.05336686596274376.

Epoch 47: early stopping
Restoring model weights from the end of the best epoch: 32.

[I 2025-03-12 09:29:40,126] Trial 39 finished with value: 0.05854278802871704 and parameters: {'head_size': 4, 'num_heads': 5, 'ff_dim': 128, 'num_transformer_blocks': 5, 'mlp_units_1': 128, 'mlp_units_2': 64, 'dropout': 0.44492215659872614, 'mlp_dropout': 0.3448178351758703, 'learning_rate': 0.0011928781621243308, 'batch_size': 256}. Best is trial 40 with value: 0.05336686596274376.

Epoch 83: early stopping
Restoring model weights from the end of the best epoch: 68.

[I 2025-03-12 09:37:18,743] Trial 38 finished with value: 0.056671809405088425 and parameters: {'head_size': 4, 'num_heads': 5, 'ff_dim': 128, 'num_transformer_blocks': 3, 'mlp_units_1': 448, 'mlp_units_2': 160, 'dropout': 0.43351363110931096, 'mlp_dropout': 0.12951041187650542, 'learning_rate': 0.001254894054272666, 'batch_size': 256}. Best is trial 40 with value: 0.05336686596274376.

Epoch 42: early stopping
Restoring model weights from the end of the best epoch: 27.

[I 2025-03-12 10:01:58,722] Trial 49 finished with value: 0.058442361652851105 and parameters: {'head_size': 5, 'num_heads': 5, 'ff_dim': 128, 'num_transformer_blocks': 3, 'mlp_units_1': 320, 'mlp_units_2': 64, 'dropout': 0.4693898152436289, 'mlp_dropout': 0.22297445625430318, 'learning_rate': 0.0009915106396364741, 'batch_size': 256}. Best is trial 40 with value: 0.05336686596274376.

Epoch 47: early stopping
Restoring model weights from the end of the best epoch: 32.

[I 2025-03-12 10:02:47,655] Trial 47 finished with value: 0.06081370264291763 and parameters: {'head_size': 5, 'num_heads': 5, 'ff_dim': 80, 'num_transformer_blocks': 3, 'mlp_units_1': 320, 'mlp_units_2': 224, 'dropout': 0.2112399493121858, 'mlp_dropout': 0.2315680293504741, 'learning_rate': 0.0010169942551153026, 'batch_size': 256}. Best is trial 40 with value: 0.05336686596274376.

Epoch 64: early stopping
Restoring model weights from the end of the best epoch: 49.

[I 2025-03-12 10:08:37,297] Trial 45 finished with value: 0.055296391248703 and parameters: {'head_size': 5, 'num_heads': 5, 'ff_dim': 80, 'num_transformer_blocks': 3, 'mlp_units_1': 192, 'mlp_units_2': 224, 'dropout': 0.46408960121891457, 'mlp_dropout': 0.12571740680220642, 'learning_rate': 0.0017791790013173883, 'batch_size': 256}. Best is trial 40 with value: 0.05336686596274376.

Epoch 87: early stopping
Restoring model weights from the end of the best epoch: 72.

[I 2025-03-12 10:26:38,096] Trial 48 finished with value: 0.056557804346084595 and parameters: {'head_size': 5, 'num_heads': 5, 'ff_dim': 128, 'num_transformer_blocks': 3, 'mlp_units_1': 192, 'mlp_units_2': 64, 'dropout': 0.4624707266085965, 'mlp_dropout': 0.1246582197948072, 'learning_rate': 0.0009942796951539427, 'batch_size': 256}. Best is trial 40 with value: 0.05336686596274376.

✅ Mejores hiperparámetros: {'head_size': 4, 'num_heads': 5, 'ff_dim': 128, 'num_transformer_blocks': 3, 'mlp_units_1': 128, 'mlp_units_2': 64, 'dropout': 0.10435760102849667, 'mlp_dropout': 0.27390486046392415, 'learning_rate': 0.001055563359247843, 'batch_size': 256}

### Forescasting

In [39]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer, Conv1D, BatchNormalization, MaxPooling1D, Bidirectional, LSTM, Dropout, Dense
from tensorflow.keras.optimizers import Adam

# Definir la función objetivo para Optuna
def objective(trial):
    # Hiperparámetros a optimizar
    filters = trial.suggest_categorical("filters", [32, 64, 128])
    kernel_size = trial.suggest_int("kernel_size", 2, 5)
    lstm_units_1 = trial.suggest_categorical("lstm_units_1", [64, 128, 256])
    lstm_units_2 = trial.suggest_categorical("lstm_units_2", [32, 64, 128])
    lstm_units_3 = trial.suggest_categorical("lstm_units_3", [16, 32, 64])
    dropout_lstm = trial.suggest_float("dropout_lstm", 0.1, 0.5)
    dropout_dense = trial.suggest_float("dropout_dense", 0.1, 0.5)
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-4, 1e-2)
    batch_size = trial.suggest_categorical("batch_size", [128, 256, 512])  # 🔹 Optimización del batch size

    # Construcción del modelo
    model = Sequential()
    model.add(InputLayer((X_train_windowed.shape[1], X_train_windowed.shape[2])))

    # CNN
    model.add(Conv1D(filters=filters, kernel_size=kernel_size, padding='same', activation='relu'))
    model.add(BatchNormalization())  
    model.add(MaxPooling1D(pool_size=2))

    # BiLSTM
    model.add(Bidirectional(LSTM(lstm_units_1, return_sequences=True)))
    model.add(Bidirectional(LSTM(lstm_units_2, return_sequences=True)))
    model.add(Dropout(dropout_lstm))
    model.add(Bidirectional(LSTM(lstm_units_3, return_sequences=False)))

    # Normalización y Dropout
    model.add(BatchNormalization())
    model.add(Dropout(dropout_dense))

    # Capas Densas
    model.add(Dense(16, activation='relu'))
    model.add(Dense(1, activation='relu'))

    # Compilar el modelo
    model.compile(
        loss=tf.keras.losses.MeanSquaredError(),
        optimizer=Adam(learning_rate=learning_rate),
        metrics=[tf.keras.metrics.RootMeanSquaredError()]
    )

    # Entrenar el modelo con validación
    history = model.fit(
        X_train_windowed, y_train_windowed,
        epochs=100,  # Se puede detener antes con Early Stopping
        batch_size=batch_size,  # 🔹 Batch size optimizado
        validation_data=(X_val_windowed, y_val_windowed),  # 🔹 Validación en cada época
        callbacks=[early_stop],  # 🔹 Early Stopping activado
        verbose=0
    )

    # Obtener la mejor pérdida de validación
    val_loss = min(history.history['val_loss'])
    return val_loss  # Optuna minimizará este valor

# Crear el estudio de optimización
Forecasting_study = optuna.create_study(direction="minimize")
Forecasting_study.optimize(objective, n_trials=50, n_jobs=-1)  # Ejecutar 50 pruebas

# Imprimir los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", Forecasting_study.best_params)

[I 2025-03-12 10:26:38,337] A new study created in memory with name: no-name-a5035ae3-1b11-4241-9d35-28b61b8165fe

WARNING:tensorflow:5 out of the last 5033 calls to <function TensorFlowTrainer._make_function.<locals>.multi_step_on_iterator at 0x000001DD55863E50> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 5034 calls to <function TensorFlowTrainer._make_function.<locals>.multi_step_on_iterator at 0x000001DEC6837160> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

[I 2025-03-12 10:37:44,462] Trial 6 finished with value: 0.276267409324646 and parameters: {'filters': 64, 'kernel_size': 5, 'lstm_units_1': 256, 'lstm_units_2': 64, 'lstm_units_3': 64, 'dropout_lstm': 0.13685924874283406, 'dropout_dense': 0.17855295556451162, 'learning_rate': 0.0059779984678818895, 'batch_size': 128}. Best is trial 6 with value: 0.276267409324646.
[I 2025-03-12 10:43:32,753] Trial 8 finished with value: 0.2788870930671692 and parameters: {'filters': 128, 'kernel_size': 3, 'lstm_units_1': 128, 'lstm_units_2': 128, 'lstm_units_3': 32, 'dropout_lstm': 0.4449970723598019, 'dropout_dense': 0.4965017863116885, 'learning_rate': 0.00017166429477555824, 'batch_size': 512}. Best is trial 6 with value: 0.276267409324646.
[I 2025-03-12 10:51:11,328] Trial 9 finished with value: 0.27658557891845703 and parameters: {'filters': 128, 'kernel_size': 5, 'lstm_units_1': 64, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.15750743458769936, 'dropout_dense': 0.44497142075442353, 'learning_rate': 0.00031439061433952083, 'batch_size': 512}. Best is trial 6 with value: 0.276267409324646.
[I 2025-03-12 11:00:41,771] Trial 10 finished with value: 0.2788870930671692 and parameters: {'filters': 128, 'kernel_size': 2, 'lstm_units_1': 64, 'lstm_units_2': 128, 'lstm_units_3': 64, 'dropout_lstm': 0.15696130190087254, 'dropout_dense': 0.46824506937569466, 'learning_rate': 0.0019280595189686248, 'batch_size': 128}. Best is trial 6 with value: 0.276267409324646.
[I 2025-03-12 11:12:49,434] Trial 11 finished with value: 0.2788870930671692 and parameters: {'filters': 128, 'kernel_size': 5, 'lstm_units_1': 256, 'lstm_units_2': 64, 'lstm_units_3': 64, 'dropout_lstm': 0.16485055866464116, 'dropout_dense': 0.36896683383744944, 'learning_rate': 0.0006654486083719169, 'batch_size': 128}. Best is trial 6 with value: 0.276267409324646.
[I 2025-03-12 11:20:46,511] Trial 12 finished with value: 0.2381105273962021 and parameters: {'filters': 32, 'kernel_size': 5, 'lstm_units_1': 256, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.34575397981877154, 'dropout_dense': 0.30280933026830703, 'learning_rate': 0.009095764260051119, 'batch_size': 256}. Best is trial 12 with value: 0.2381105273962021.
[I 2025-03-12 11:30:00,185] Trial 13 finished with value: 0.2788870930671692 and parameters: {'filters': 128, 'kernel_size': 2, 'lstm_units_1': 128, 'lstm_units_2': 128, 'lstm_units_3': 16, 'dropout_lstm': 0.3050256832045498, 'dropout_dense': 0.4702099160742329, 'learning_rate': 0.00012522775984523217, 'batch_size': 128}. Best is trial 12 with value: 0.2381105273962021.
[I 2025-03-12 11:38:03,362] Trial 14 finished with value: 0.2788870930671692 and parameters: {'filters': 32, 'kernel_size': 5, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 32, 'dropout_lstm': 0.2802966864657664, 'dropout_dense': 0.31155275936846116, 'learning_rate': 0.0005784795835559993, 'batch_size': 512}. Best is trial 12 with value: 0.2381105273962021.
[I 2025-03-12 11:51:31,543] Trial 15 finished with value: 0.2788871228694916 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 32, 'dropout_lstm': 0.22153948412823277, 'dropout_dense': 0.24448111881523982, 'learning_rate': 0.0028187025092581415, 'batch_size': 256}. Best is trial 12 with value: 0.2381105273962021.
[I 2025-03-12 11:57:16,381] Trial 16 finished with value: 0.2788871228694916 and parameters: {'filters': 32, 'kernel_size': 3, 'lstm_units_1': 256, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.38132781917509617, 'dropout_dense': 0.2960027154634399, 'learning_rate': 0.0005982411924335564, 'batch_size': 256}. Best is trial 12 with value: 0.2381105273962021.
[I 2025-03-12 12:12:49,393] Trial 17 finished with value: 0.2788871228694916 and parameters: {'filters': 64, 'kernel_size': 4, 'lstm_units_1': 256, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.4904385050743337, 'dropout_dense': 0.10110559092276006, 'learning_rate': 0.009816922282711088, 'batch_size': 256}. Best is trial 12 with value: 0.2381105273962021.
[I 2025-03-12 12:23:55,353] Trial 18 finished with value: 0.2788870930671692 and parameters: {'filters': 64, 'kernel_size': 4, 'lstm_units_1': 256, 'lstm_units_2': 32, 'lstm_units_3': 64, 'dropout_lstm': 0.35450892564649317, 'dropout_dense': 0.1723598771556795, 'learning_rate': 0.00995778855321113, 'batch_size': 128}. Best is trial 12 with value: 0.2381105273962021.
[I 2025-03-12 12:36:30,518] Trial 19 finished with value: 0.2788871228694916 and parameters: {'filters': 64, 'kernel_size': 5, 'lstm_units_1': 256, 'lstm_units_2': 64, 'lstm_units_3': 64, 'dropout_lstm': 0.2386421237278561, 'dropout_dense': 0.2148505179249501, 'learning_rate': 0.0038210291104586354, 'batch_size': 256}. Best is trial 12 with value: 0.2381105273962021.
[I 2025-03-12 12:48:38,268] Trial 20 finished with value: 0.1679440289735794 and parameters: {'filters': 32, 'kernel_size': 5, 'lstm_units_1': 256, 'lstm_units_2': 32, 'lstm_units_3': 64, 'dropout_lstm': 0.3809733991849984, 'dropout_dense': 0.13351037382094552, 'learning_rate': 0.005084534519367966, 'batch_size': 256}. Best is trial 20 with value: 0.1679440289735794.
[I 2025-03-12 13:02:56,371] Trial 21 finished with value: 0.27028200030326843 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 256, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.3889114165660974, 'dropout_dense': 0.3894930571858165, 'learning_rate': 0.001727005496273444, 'batch_size': 256}. Best is trial 20 with value: 0.1679440289735794.
[I 2025-03-12 13:19:23,612] Trial 22 finished with value: 0.2788871228694916 and parameters: {'filters': 32, 'kernel_size': 5, 'lstm_units_1': 256, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.32426181881435934, 'dropout_dense': 0.10797622397013945, 'learning_rate': 0.004967499472093717, 'batch_size': 256}. Best is trial 20 with value: 0.1679440289735794.
[I 2025-03-12 13:35:15,859] Trial 23 finished with value: 0.2788871228694916 and parameters: {'filters': 32, 'kernel_size': 3, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 64, 'dropout_lstm': 0.43516664276786726, 'dropout_dense': 0.2994671954340515, 'learning_rate': 0.0015893881550447107, 'batch_size': 256}. Best is trial 20 with value: 0.1679440289735794.
[I 2025-03-12 14:05:52,363] Trial 24 finished with value: 0.2788871228694916 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 256, 'lstm_units_2': 32, 'lstm_units_3': 64, 'dropout_lstm': 0.4223056160792396, 'dropout_dense': 0.35118869362512367, 'learning_rate': 0.005835761637183487, 'batch_size': 256}. Best is trial 20 with value: 0.1679440289735794.
[I 2025-03-12 14:14:18,598] Trial 25 finished with value: 0.2788871228694916 and parameters: {'filters': 32, 'kernel_size': 5, 'lstm_units_1': 256, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.4985114341887428, 'dropout_dense': 0.23530259260014547, 'learning_rate': 0.0025444436878730276, 'batch_size': 256}. Best is trial 20 with value: 0.1679440289735794.
[I 2025-03-12 14:37:14,198] Trial 26 finished with value: 0.12756383419036865 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.27021202442223646, 'dropout_dense': 0.14752417764015302, 'learning_rate': 0.006990703865007253, 'batch_size': 256}. Best is trial 26 with value: 0.12756383419036865.
[I 2025-03-12 14:52:33,290] Trial 27 finished with value: 0.2788870930671692 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 128, 'lstm_units_2': 128, 'lstm_units_3': 16, 'dropout_lstm': 0.25784166763199207, 'dropout_dense': 0.17097128958279048, 'learning_rate': 0.0034710927703185076, 'batch_size': 512}. Best is trial 26 with value: 0.12756383419036865.
[I 2025-03-12 15:08:03,530] Trial 28 finished with value: 0.2626783847808838 and parameters: {'filters': 32, 'kernel_size': 5, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.3286098098226888, 'dropout_dense': 0.1516325048453208, 'learning_rate': 0.0073830151445035, 'batch_size': 256}. Best is trial 26 with value: 0.12756383419036865.
[I 2025-03-12 15:23:05,055] Trial 7 finished with value: 0.061776258051395416 and parameters: {'filters': 128, 'kernel_size': 5, 'lstm_units_1': 256, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.2656123683447598, 'dropout_dense': 0.26610313044390954, 'learning_rate': 0.0004928738324444311, 'batch_size': 512}. Best is trial 7 with value: 0.061776258051395416.
[I 2025-03-12 15:51:15,135] Trial 30 finished with value: 0.15070995688438416 and parameters: {'filters': 128, 'kernel_size': 4, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.20189910793044458, 'dropout_dense': 0.1416279072908859, 'learning_rate': 0.0009458858567753236, 'batch_size': 512}. Best is trial 7 with value: 0.061776258051395416.
[I 2025-03-12 16:04:15,631] Trial 0 finished with value: 0.05402800440788269 and parameters: {'filters': 128, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 32, 'dropout_lstm': 0.12850289949645297, 'dropout_dense': 0.3736924023288869, 'learning_rate': 0.0005232498319662458, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-12 16:04:33,855] Trial 31 finished with value: 0.21223695576190948 and parameters: {'filters': 128, 'kernel_size': 3, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.19637973750198257, 'dropout_dense': 0.20083046860805798, 'learning_rate': 0.000973255525677856, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-12 16:11:50,828] Trial 1 finished with value: 0.12106651812791824 and parameters: {'filters': 64, 'kernel_size': 5, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.39811274795810125, 'dropout_dense': 0.4368085624874348, 'learning_rate': 0.00017685484795457976, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-12 16:36:22,678] Trial 34 finished with value: 0.2618924081325531 and parameters: {'filters': 64, 'kernel_size': 5, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.12067756951626145, 'dropout_dense': 0.4176438722553284, 'learning_rate': 0.00027225111550195776, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-12 17:01:03,670] Trial 35 finished with value: 0.2757042348384857 and parameters: {'filters': 128, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.3018244620755729, 'dropout_dense': 0.33850499429246567, 'learning_rate': 0.0003708662710938731, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-12 17:19:28,492] Trial 36 finished with value: 0.2788870930671692 and parameters: {'filters': 64, 'kernel_size': 5, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.10008434552498675, 'dropout_dense': 0.4070567305487623, 'learning_rate': 0.00018347944058453038, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-12 17:51:24,528] Trial 37 finished with value: 0.17206579446792603 and parameters: {'filters': 64, 'kernel_size': 3, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.46347720539995735, 'dropout_dense': 0.2721977933203382, 'learning_rate': 0.0003716510780962632, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-12 18:43:39,681] Trial 38 finished with value: 0.2546774744987488 and parameters: {'filters': 128, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.2689122953248212, 'dropout_dense': 0.4335848955946331, 'learning_rate': 0.00010512248897675422, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-12 19:35:47,658] Trial 39 finished with value: 0.27822479605674744 and parameters: {'filters': 128, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.23983853576631184, 'dropout_dense': 0.3734326119664473, 'learning_rate': 0.00020752316871968732, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-12 20:09:22,176] Trial 40 finished with value: 0.2280530035495758 and parameters: {'filters': 128, 'kernel_size': 4, 'lstm_units_1': 128, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.18038715676142436, 'dropout_dense': 0.3332274194770236, 'learning_rate': 0.00045295007182712544, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-12 20:48:45,695] Trial 41 finished with value: 0.2788870930671692 and parameters: {'filters': 64, 'kernel_size': 2, 'lstm_units_1': 64, 'lstm_units_2': 128, 'lstm_units_3': 16, 'dropout_lstm': 0.2832647352215529, 'dropout_dense': 0.47507299806696357, 'learning_rate': 0.00026163020806955686, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-12 21:24:10,886] Trial 42 finished with value: 0.2788870930671692 and parameters: {'filters': 128, 'kernel_size': 5, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.1369439788474392, 'dropout_dense': 0.4921885668302584, 'learning_rate': 0.0012771936301803901, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-12 22:02:24,992] Trial 43 finished with value: 0.2788870930671692 and parameters: {'filters': 128, 'kernel_size': 3, 'lstm_units_1': 128, 'lstm_units_2': 128, 'lstm_units_3': 32, 'dropout_lstm': 0.40533245185253164, 'dropout_dense': 0.44136654656145, 'learning_rate': 0.0008009651719682326, 'batch_size': 128}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-12 22:30:33,132] Trial 44 finished with value: 0.2663516700267792 and parameters: {'filters': 128, 'kernel_size': 5, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.3548704989262126, 'dropout_dense': 0.2707294775628515, 'learning_rate': 0.0001439276112538799, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-12 22:59:04,739] Trial 45 finished with value: 0.2691326141357422 and parameters: {'filters': 64, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 32, 'dropout_lstm': 0.23448729438637902, 'dropout_dense': 0.4016955045555452, 'learning_rate': 0.0004877184941809708, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-12 23:38:48,101] Trial 46 finished with value: 0.2788870930671692 and parameters: {'filters': 128, 'kernel_size': 5, 'lstm_units_1': 128, 'lstm_units_2': 128, 'lstm_units_3': 16, 'dropout_lstm': 0.32464954182188277, 'dropout_dense': 0.3635406998326683, 'learning_rate': 0.00023651011343947756, 'batch_size': 128}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-13 00:09:21,425] Trial 47 finished with value: 0.2779022455215454 and parameters: {'filters': 128, 'kernel_size': 2, 'lstm_units_1': 64, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.15413788585344185, 'dropout_dense': 0.45355651753716053, 'learning_rate': 0.0007465356438198995, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-13 00:28:00,073] Trial 48 finished with value: 0.2669270932674408 and parameters: {'filters': 128, 'kernel_size': 4, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.2127847235709513, 'dropout_dense': 0.1286483914768902, 'learning_rate': 0.0011493583852345002, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-13 01:32:53,175] Trial 49 finished with value: 0.20190830528736115 and parameters: {'filters': 128, 'kernel_size': 4, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.263050653324047, 'dropout_dense': 0.20268674982543136, 'learning_rate': 0.0008881474667485811, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-13 03:46:30,978] Trial 5 finished with value: 0.05713530257344246 and parameters: {'filters': 128, 'kernel_size': 3, 'lstm_units_1': 128, 'lstm_units_2': 128, 'lstm_units_3': 64, 'dropout_lstm': 0.4994681308433927, 'dropout_dense': 0.4125659494846935, 'learning_rate': 0.00799344054708717, 'batch_size': 256}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-13 05:16:38,288] Trial 32 finished with value: 0.05816367268562317 and parameters: {'filters': 128, 'kernel_size': 3, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.10537779941173872, 'dropout_dense': 0.41383893439686764, 'learning_rate': 0.0003041236200675353, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-13 05:20:12,969] Trial 33 finished with value: 0.0746605396270752 and parameters: {'filters': 128, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.11313581006575732, 'dropout_dense': 0.40986277579143277, 'learning_rate': 0.00032153090733982474, 'batch_size': 512}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-13 05:46:20,925] Trial 3 finished with value: 0.06065262109041214 and parameters: {'filters': 64, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 64, 'dropout_lstm': 0.4741149653896666, 'dropout_dense': 0.20702235685302212, 'learning_rate': 0.0003093666426914163, 'batch_size': 256}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-13 05:49:07,506] Trial 4 finished with value: 0.06604864448308945 and parameters: {'filters': 128, 'kernel_size': 2, 'lstm_units_1': 64, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.42868809841629274, 'dropout_dense': 0.1695689796117576, 'learning_rate': 0.0001249530926744365, 'batch_size': 256}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-13 07:56:31,414] Trial 29 finished with value: 0.055881522595882416 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.19965236830700733, 'dropout_dense': 0.1292737180921132, 'learning_rate': 0.004638564027867132, 'batch_size': 256}. Best is trial 0 with value: 0.05402800440788269.
[I 2025-03-13 09:35:58,729] Trial 2 finished with value: 0.0736924484372139 and parameters: {'filters': 32, 'kernel_size': 3, 'lstm_units_1': 256, 'lstm_units_2': 64, 'lstm_units_3': 32, 'dropout_lstm': 0.3081115173371475, 'dropout_dense': 0.4372220309012945, 'learning_rate': 0.00011151621409795502, 'batch_size': 128}. Best is trial 0 with value: 0.05402800440788269.

Mejores hiperparámetros: {'filters': 128, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 32, 'dropout_lstm': 0.12850289949645297, 'dropout_dense': 0.3736924023288869, 'learning_rate': 0.0005232498319662458, 'batch_size': 512}

### Photovoltaic

In [35]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv1D, MaxPooling1D, Bidirectional, GRU, MultiHeadAttention
from tensorflow.keras.layers import Flatten, Dropout, Dense
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import mean_squared_error

# Definir la función objetivo para Optuna
def objective(trial):
    # Hiperparámetros a optimizar
    filters_1 = trial.suggest_categorical("filters_1", [32, 64, 128])
    filters_2 = trial.suggest_categorical("filters_2", [64, 128, 256])
    kernel_size = trial.suggest_int("kernel_size", 2, 5)
    gru_units = trial.suggest_categorical("gru_units", [32, 64, 128])
    num_heads = trial.suggest_categorical("num_heads", [2, 4, 8])
    dropout_rate = trial.suggest_float("dropout_rate", 0.2, 0.5)
    dense_units_1 = trial.suggest_categorical("dense_units_1", [32, 64, 128])
    dense_units_2 = trial.suggest_categorical("dense_units_2", [16, 32, 64])
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-4, 1e-2)
    batch_size = trial.suggest_categorical("batch_size", [128, 256, 512])

    # Definir el modelo
    inputs = Input(shape=(X_train_windowed.shape[1], X_train_windowed.shape[2]))

    # Primera capa CNN
    x = Conv1D(filters=filters_1, kernel_size=kernel_size, padding='same', activation='relu')(inputs)
    x = MaxPooling1D(pool_size=2)(x)

    # Segunda capa CNN
    x = Conv1D(filters=filters_2, kernel_size=kernel_size, padding='same', activation='relu')(x)
    x = MaxPooling1D(pool_size=2)(x)

    # Capa BiGRU
    x = Bidirectional(GRU(gru_units, return_sequences=True))(x)

    # Atención MultiHead
    attention = MultiHeadAttention(num_heads=num_heads, key_dim=128)(x, x)

    # Aplanar y Dropout
    x = Flatten()(attention)
    x = Dropout(dropout_rate)(x)
    x = Dense(dense_units_1, activation="relu", kernel_regularizer=l2(0.01))(x)
    x = Dense(dense_units_2, activation="relu")(x)

    # Capa de salida
    outputs = Dense(1, activation="linear")(x)

    # Construcción del modelo
    model = Model(inputs=inputs, outputs=outputs)

    # Compilar el modelo
    model.compile(
        loss=tf.keras.losses.MeanSquaredError(),
        optimizer=Adam(learning_rate=learning_rate),
        metrics=[tf.keras.metrics.RootMeanSquaredError()]
    )

    # Early Stopping
    early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True, verbose=1)

    # Entrenar el modelo
    history = model.fit(
        X_train_windowed, y_train_windowed,
        epochs=100,  # Se detendrá con Early Stopping
        batch_size=batch_size,
        validation_data=(X_val_windowed, y_val_windowed),
        callbacks=[early_stop],
        verbose=0
    )

    # Obtener la mejor pérdida de validación
    val_loss = min(history.history['val_loss'])
    return val_loss  # Optuna minimizará este valor

# Crear el estudio de optimización
Photovoltaic_study = optuna.create_study(direction="minimize")
Photovoltaic_study.optimize(objective, n_trials=50, n_j
                            obs=-1)  # Ejecutar 50 pruebas

# Imprimir los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", Photovoltaic_study.best_params)

[I 2025-03-13 10:17:18,108] A new study created in memory with name: no-name-560085e2-0501-46a3-88e2-468c9f1bd050

Epoch 40: early stopping
Restoring model weights from the end of the best epoch: 30.

[I 2025-03-13 10:46:36,165] Trial 0 finished with value: 0.06718964129686356 and parameters: {'filters_1': 32, 'filters_2': 256, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.25017037807866194, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.0010720966270651466, 'batch_size': 512}. Best is trial 0 with value: 0.06718964129686356.

Epoch 64: early stopping
Restoring model weights from the end of the best epoch: 54.

[I 2025-03-13 11:06:14,498] Trial 7 finished with value: 0.06049086153507233 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.20741041595352808, 'dense_units_1': 32, 'dense_units_2': 32, 'learning_rate': 0.0014519496005881705, 'batch_size': 512}. Best is trial 7 with value: 0.06049086153507233.

Epoch 68: early stopping
Restoring model weights from the end of the best epoch: 58.

[I 2025-03-13 11:13:37,878] Trial 4 finished with value: 0.053285859525203705 and parameters: {'filters_1': 128, 'filters_2': 256, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.25492363066842477, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.0016004979653859257, 'batch_size': 512}. Best is trial 4 with value: 0.053285859525203705.

Epoch 42: early stopping
Restoring model weights from the end of the best epoch: 32.

[I 2025-03-13 11:16:20,038] Trial 8 finished with value: 0.058984726667404175 and parameters: {'filters_1': 128, 'filters_2': 64, 'kernel_size': 3, 'gru_units': 32, 'num_heads': 8, 'dropout_rate': 0.4562635496605992, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.00237844876839247, 'batch_size': 512}. Best is trial 4 with value: 0.053285859525203705.

Epoch 35: early stopping
Restoring model weights from the end of the best epoch: 25.

[I 2025-03-13 11:19:28,867] Trial 2 finished with value: 0.05628131702542305 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 4, 'gru_units': 128, 'num_heads': 2, 'dropout_rate': 0.28251656068596487, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.002198535403942716, 'batch_size': 128}. Best is trial 4 with value: 0.053285859525203705.

Epoch 35: early stopping
Restoring model weights from the end of the best epoch: 25.

[I 2025-03-13 11:25:10,612] Trial 6 finished with value: 0.057108715176582336 and parameters: {'filters_1': 32, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 2, 'dropout_rate': 0.482203477750957, 'dense_units_1': 32, 'dense_units_2': 32, 'learning_rate': 0.00028002436731810744, 'batch_size': 128}. Best is trial 4 with value: 0.053285859525203705.

Epoch 55: early stopping
Restoring model weights from the end of the best epoch: 45.

[I 2025-03-13 11:26:23,181] Trial 3 finished with value: 0.05940507352352142 and parameters: {'filters_1': 64, 'filters_2': 256, 'kernel_size': 3, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.48434940765475354, 'dense_units_1': 128, 'dense_units_2': 16, 'learning_rate': 0.0009133071785186371, 'batch_size': 256}. Best is trial 4 with value: 0.053285859525203705.

Epoch 43: early stopping
Restoring model weights from the end of the best epoch: 33.

[I 2025-03-13 11:38:42,403] Trial 1 finished with value: 0.06141061708331108 and parameters: {'filters_1': 128, 'filters_2': 64, 'kernel_size': 3, 'gru_units': 128, 'num_heads': 2, 'dropout_rate': 0.2942028616688314, 'dense_units_1': 128, 'dense_units_2': 16, 'learning_rate': 0.0003453721447668308, 'batch_size': 128}. Best is trial 4 with value: 0.053285859525203705.

Epoch 45: early stopping
Restoring model weights from the end of the best epoch: 35.

[I 2025-03-13 11:51:05,943] Trial 9 finished with value: 0.05847669020295143 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 8, 'dropout_rate': 0.38235559626305454, 'dense_units_1': 128, 'dense_units_2': 16, 'learning_rate': 0.0010874473971381096, 'batch_size': 256}. Best is trial 4 with value: 0.053285859525203705.

Epoch 79: early stopping
Restoring model weights from the end of the best epoch: 69.

[I 2025-03-13 11:56:39,744] Trial 5 finished with value: 0.06905446201562881 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 4, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.2423166661903925, 'dense_units_1': 32, 'dense_units_2': 32, 'learning_rate': 0.00010528626283678403, 'batch_size': 256}. Best is trial 4 with value: 0.053285859525203705.

Epoch 11: early stopping
Restoring model weights from the end of the best epoch: 1.

[I 2025-03-13 12:00:16,816] Trial 16 finished with value: 1.589534044265747 and parameters: {'filters_1': 128, 'filters_2': 64, 'kernel_size': 5, 'gru_units': 128, 'num_heads': 2, 'dropout_rate': 0.4459276202019054, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.005539071189531835, 'batch_size': 512}. Best is trial 4 with value: 0.053285859525203705.

Epoch 65: early stopping
Restoring model weights from the end of the best epoch: 55.

[I 2025-03-13 12:08:17,152] Trial 13 finished with value: 0.05416964739561081 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 4, 'dropout_rate': 0.450688982606756, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.0016764180143462473, 'batch_size': 512}. Best is trial 4 with value: 0.053285859525203705.

Epoch 13: early stopping
Restoring model weights from the end of the best epoch: 3.

[I 2025-03-13 12:10:31,039] Trial 17 finished with value: 4.853669166564941 and parameters: {'filters_1': 128, 'filters_2': 256, 'kernel_size': 5, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.3511775004805796, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.009254224188857088, 'batch_size': 512}. Best is trial 4 with value: 0.053285859525203705.

Epoch 50: early stopping
Restoring model weights from the end of the best epoch: 40.

[I 2025-03-13 12:19:16,340] Trial 15 finished with value: 0.05954279378056526 and parameters: {'filters_1': 128, 'filters_2': 256, 'kernel_size': 4, 'gru_units': 64, 'num_heads': 2, 'dropout_rate': 0.4400479599550914, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.0006451263967834156, 'batch_size': 512}. Best is trial 4 with value: 0.053285859525203705.

Restoring model weights from the end of the best epoch: 93.

[I 2025-03-13 12:23:04,298] Trial 11 finished with value: 0.06032842770218849 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 4, 'dropout_rate': 0.22160336973282813, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.009437745760198122, 'batch_size': 512}. Best is trial 4 with value: 0.053285859525203705.

Epoch 28: early stopping
Restoring model weights from the end of the best epoch: 18.

[I 2025-03-13 12:26:08,323] Trial 12 finished with value: 0.06018030643463135 and parameters: {'filters_1': 128, 'filters_2': 64, 'kernel_size': 5, 'gru_units': 128, 'num_heads': 2, 'dropout_rate': 0.24438430772354253, 'dense_units_1': 32, 'dense_units_2': 32, 'learning_rate': 0.002702262845343923, 'batch_size': 128}. Best is trial 4 with value: 0.053285859525203705.

Epoch 51: early stopping
Restoring model weights from the end of the best epoch: 41.

[I 2025-03-13 12:33:28,965] Trial 14 finished with value: 0.054114822298288345 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.28801476451992913, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.002494168095433645, 'batch_size': 256}. Best is trial 4 with value: 0.053285859525203705.

Epoch 35: early stopping
Restoring model weights from the end of the best epoch: 25.

[I 2025-03-13 12:37:31,723] Trial 20 finished with value: 0.055144209414720535 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 4, 'dropout_rate': 0.40598241157122356, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.0037044879546028857, 'batch_size': 512}. Best is trial 4 with value: 0.053285859525203705.

Epoch 36: early stopping
Restoring model weights from the end of the best epoch: 26.

[I 2025-03-13 12:56:17,005] Trial 23 finished with value: 0.05555140599608421 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 4, 'dropout_rate': 0.39130119164719174, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.004021064307681732, 'batch_size': 512}. Best is trial 4 with value: 0.053285859525203705.

Epoch 41: early stopping
Restoring model weights from the end of the best epoch: 31.

[I 2025-03-13 12:56:33,794] Trial 22 finished with value: 0.0607791468501091 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 4, 'dropout_rate': 0.39369104173133684, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.0030895455819930787, 'batch_size': 512}. Best is trial 4 with value: 0.053285859525203705.

Epoch 81: early stopping
Restoring model weights from the end of the best epoch: 71.

[I 2025-03-13 12:58:58,663] Trial 10 finished with value: 0.061558570712804794 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.2784547618080423, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.00010853156699101708, 'batch_size': 128}. Best is trial 4 with value: 0.053285859525203705.

Epoch 51: early stopping
Restoring model weights from the end of the best epoch: 41.

[I 2025-03-13 13:01:23,596] Trial 21 finished with value: 0.05316260829567909 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 4, 'dropout_rate': 0.37577784298291944, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.0032403156004064317, 'batch_size': 512}. Best is trial 21 with value: 0.05316260829567909.

Epoch 39: early stopping
Restoring model weights from the end of the best epoch: 29.

[I 2025-03-13 13:04:32,805] Trial 18 finished with value: 0.05728919059038162 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 4, 'gru_units': 64, 'num_heads': 2, 'dropout_rate': 0.32091310651041544, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.004700720308716722, 'batch_size': 128}. Best is trial 21 with value: 0.05316260829567909.

Epoch 93: early stopping
Restoring model weights from the end of the best epoch: 83.

[I 2025-03-13 13:37:23,312] Trial 19 finished with value: 0.13560274243354797 and parameters: {'filters_1': 128, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 4, 'dropout_rate': 0.37281886030091116, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.00925196846317938, 'batch_size': 512}. Best is trial 21 with value: 0.05316260829567909.

Epoch 35: early stopping
Restoring model weights from the end of the best epoch: 25.

[I 2025-03-13 14:15:23,785] Trial 26 finished with value: 0.06389350444078445 and parameters: {'filters_1': 32, 'filters_2': 256, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.3058767725942023, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.0004585308900565235, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 40: early stopping
Restoring model weights from the end of the best epoch: 30.

[I 2025-03-13 14:28:05,257] Trial 29 finished with value: 0.0586593896150589 and parameters: {'filters_1': 32, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.3219625608092891, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.0006167259948569278, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 42: early stopping
Restoring model weights from the end of the best epoch: 32.

[I 2025-03-13 14:32:18,735] Trial 28 finished with value: 0.054666668176651 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.3220713031592074, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.0017124556531562618, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 59: early stopping
Restoring model weights from the end of the best epoch: 49.

[I 2025-03-13 14:36:29,223] Trial 24 finished with value: 0.05328763648867607 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.30337365727693777, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.0047036229607323645, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 43: early stopping
Restoring model weights from the end of the best epoch: 33.

[I 2025-03-13 14:37:55,391] Trial 27 finished with value: 0.06354814767837524 and parameters: {'filters_1': 32, 'filters_2': 256, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.30962168596813605, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.0005110517188757027, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 35: early stopping
Restoring model weights from the end of the best epoch: 25.

[I 2025-03-13 15:08:51,359] Trial 31 finished with value: 0.0661439523100853 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.3083422431195908, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.0005974088482107145, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 22: early stopping
Restoring model weights from the end of the best epoch: 12.

[I 2025-03-13 15:28:55,371] Trial 33 finished with value: 0.060830626636743546 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.3462901969821079, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.0016361378279412721, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 35: early stopping
Restoring model weights from the end of the best epoch: 25.

[I 2025-03-13 16:08:09,899] Trial 37 finished with value: 0.058637648820877075 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.2628242033917618, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.0009962955987946965, 'batch_size': 512}. Best is trial 21 with value: 0.05316260829567909.

Epoch 85: early stopping
Restoring model weights from the end of the best epoch: 75.

[I 2025-03-13 16:09:59,486] Trial 25 finished with value: 0.05436275154352188 and parameters: {'filters_1': 32, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.31054865000965526, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.004569949208168796, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 62: early stopping
Restoring model weights from the end of the best epoch: 52.

[I 2025-03-13 16:22:08,978] Trial 36 finished with value: 0.06240426003932953 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.3516934093976587, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.005127088508468209, 'batch_size': 512}. Best is trial 21 with value: 0.05316260829567909.

Epoch 17: early stopping
Restoring model weights from the end of the best epoch: 7.

[I 2025-03-13 16:23:20,555] Trial 38 finished with value: 0.6379314064979553 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.2658820377830926, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.0063157243400088865, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 52: early stopping
Restoring model weights from the end of the best epoch: 42.

[I 2025-03-13 16:47:05,794] Trial 32 finished with value: 0.06065543740987778 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.3132242352926463, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.005823401889481288, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 91: early stopping
Restoring model weights from the end of the best epoch: 81.

[I 2025-03-13 16:55:38,703] Trial 30 finished with value: 0.055711548775434494 and parameters: {'filters_1': 32, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.32998743505337635, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.006024064684024605, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 31: early stopping
Restoring model weights from the end of the best epoch: 21.

[I 2025-03-13 18:01:07,049] Trial 42 finished with value: 0.0727958083152771 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.22374882109874594, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.006685795408435754, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 67: early stopping
Restoring model weights from the end of the best epoch: 57.

[I 2025-03-13 18:13:42,637] Trial 35 finished with value: 0.1350439339876175 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.359864988957552, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.006139205108855434, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 43: early stopping
Restoring model weights from the end of the best epoch: 33.

[I 2025-03-13 18:23:05,599] Trial 40 finished with value: 0.05499822646379471 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.2619823554492441, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.005498316734564538, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 32: early stopping
Restoring model weights from the end of the best epoch: 22.

[I 2025-03-13 18:28:36,877] Trial 43 finished with value: 0.05540173128247261 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.2860276887763375, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.002067086753079442, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 30: early stopping
Restoring model weights from the end of the best epoch: 20.

[I 2025-03-13 18:32:37,021] Trial 44 finished with value: 0.0615743063390255 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 4, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.28556061903867846, 'dense_units_1': 128, 'dense_units_2': 16, 'learning_rate': 0.002168077558402345, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 47: early stopping
Restoring model weights from the end of the best epoch: 37.

[I 2025-03-13 18:34:26,458] Trial 39 finished with value: 0.059268951416015625 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.3492348969631551, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.005412260132111045, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 88: early stopping
Restoring model weights from the end of the best epoch: 78.

[I 2025-03-13 19:07:02,112] Trial 34 finished with value: 0.06234712153673172 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.3438242143472265, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.006825728635693266, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 43: early stopping
Restoring model weights from the end of the best epoch: 33.

[I 2025-03-13 19:33:27,654] Trial 48 finished with value: 0.06061360985040665 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 4, 'gru_units': 32, 'num_heads': 4, 'dropout_rate': 0.42068968866981615, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.0012823544125687204, 'batch_size': 512}. Best is trial 21 with value: 0.05316260829567909.

Epoch 41: early stopping
Restoring model weights from the end of the best epoch: 31.

[I 2025-03-13 19:33:29,888] Trial 49 finished with value: 0.058624267578125 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 4, 'dropout_rate': 0.49698126902837886, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.0012877155963457521, 'batch_size': 512}. Best is trial 21 with value: 0.05316260829567909.

Epoch 29: early stopping
Restoring model weights from the end of the best epoch: 19.

[I 2025-03-13 20:21:34,349] Trial 47 finished with value: 0.057761870324611664 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 4, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.2843282539993987, 'dense_units_1': 32, 'dense_units_2': 32, 'learning_rate': 0.002293020468594303, 'batch_size': 128}. Best is trial 21 with value: 0.05316260829567909.

Restoring model weights from the end of the best epoch: 95.

[I 2025-03-13 20:28:16,139] Trial 41 finished with value: 0.07533270120620728 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.2803025826807099, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.006578136680478497, 'batch_size': 256}. Best is trial 21 with value: 0.05316260829567909.

Epoch 34: early stopping
Restoring model weights from the end of the best epoch: 24.

[I 2025-03-13 20:30:22,636] Trial 46 finished with value: 0.057010967284440994 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 4, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.2907935947667643, 'dense_units_1': 32, 'dense_units_2': 16, 'learning_rate': 0.0021359368079330826, 'batch_size': 128}. Best is trial 21 with value: 0.05316260829567909.

Epoch 44: early stopping
Restoring model weights from the end of the best epoch: 34.

[I 2025-03-13 20:36:51,908] Trial 45 finished with value: 0.05312512069940567 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 4, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.28918099674260234, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.0020715275009286437, 'batch_size': 128}. Best is trial 45 with value: 0.05312512069940567.

Mejores hiperparámetros: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 4, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.28918099674260234, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.0020715275009286437, 'batch_size': 128}