# Optimización de Modelos Conjunto Soleado por GMM

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
#Importaciones
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

#Lectura de datos
datos = pd.read_excel('/content/drive/MyDrive/Tesina/03_Clusterizacion_CTNET.xlsx')
datos.head(24)

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM
0,2022-09-01 00:00:00,0.000000,19,77,0,0,Noche,Noche
1,2022-09-01 01:00:00,0.000000,19,82,0,1,Noche,Noche
2,2022-09-01 02:00:00,0.000000,18,85,0,2,Noche,Noche
3,2022-09-01 03:00:00,0.000000,18,87,0,3,Noche,Noche
4,2022-09-01 04:00:00,0.000000,18,88,0,4,Noche,Noche
5,2022-09-01 05:00:00,0.000000,17,86,0,5,Noche,Noche
6,2022-09-01 06:00:00,0.000000,18,89,0,6,Soleado,Lluvioso
7,2022-09-01 07:00:00,6.584959,18,95,0,7,Soleado,Lluvioso
8,2022-09-01 08:00:00,560.422022,18,100,0,8,Soleado,Lluvioso
9,2022-09-01 09:00:00,7720.582326,18,100,1,9,Soleado,Lluvioso
10,2022-09-01 10:00:00,9433.109309,19,93,2,10,Soleado,Lluvioso
11,2022-09-01 11:00:00,22189.147406,20,79,2,11,Soleado,Lluvioso
12,2022-09-01 12:00:00,29196.986647,22,64,6,12,Nublado,Soleado
13,2022-09-01 13:00:00,25478.471342,23,51,11,13,Nublado,Soleado
14,2022-09-01 14:00:00,29057.585772,25,41,12,14,Nublado,Soleado
15,2022-09-01 15:00:00,30000.000000,26,35,11,15,Nublado,Soleado
16,2022-09-01 16:00:00,28062.328964,27,33,8,16,Nublado,Soleado
17,2022-09-01 17:00:00,28786.629243,28,34,5,17,Nublado,Nublado
18,2022-09-01 18:00:00,29900.303971,27,37,3,18,Nublado,Nublado
19,2022-09-01 19:00:00,18282.505369,26,41,2,19,Nublado,Nublado
20,2022-09-01 20:00:00,3411.083740,24,48,0,20,Nublado,Nublado
21,2022-09-01 21:00:00,382.187718,22,55,0,21,Soleado,Lluvioso
22,2022-09-01 22:00:00,0.000000,21,61,0,22,Noche,Noche
23,2022-09-01 23:00:00,0.000000,20,68,0,23,Noche,Noche

In [3]:
datos["Generacion_prev_hour"] = datos["Generación"].shift(1)
datos["Generacion_prev_day"] = datos["Generación"].shift(24)
datos = datos.dropna(how="any", axis= 0)

Definimos X y y

In [4]:
datos_dia = datos[datos["Cluster KMeans"] == "Nublado"].copy()
datos_dia.head(10)

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day
36,2022-09-02 12:00:00,27523.885172,21,57,4,12,Nublado,Nublado,17036.043251,29196.986647
37,2022-09-02 13:00:00,20596.278869,23,45,5,13,Nublado,Nublado,27523.885172,25478.471342
38,2022-09-02 14:00:00,28500.000000,24,37,6,14,Nublado,Nublado,20596.278869,29057.585772
39,2022-09-02 15:00:00,24647.568577,26,33,5,15,Nublado,Nublado,28500.000000,30000.000000
40,2022-09-02 16:00:00,25500.000000,27,34,4,16,Nublado,Nublado,24647.568577,28062.328964
41,2022-09-02 17:00:00,24281.956494,28,36,2,17,Nublado,Nublado,25500.000000,28786.629243
42,2022-09-02 18:00:00,22733.515002,26,39,1,18,Nublado,Nublado,24281.956494,29900.303971
43,2022-09-02 19:00:00,11972.590689,25,44,1,19,Nublado,Nublado,22733.515002,18282.505369
60,2022-09-03 12:00:00,17723.695569,21,58,4,12,Nublado,Soleado,11246.659307,27523.885172
61,2022-09-03 13:00:00,20400.000000,23,48,5,13,Nublado,Nublado,17723.695569,20596.278869

In [5]:
columns = datos_dia.drop(columns=["Fecha", "Generación", "Cluster KMeans", "Cluster GMM"]).columns

In [6]:
X = datos_dia[columns]
X

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
36,21,57,4,12,17036.043251,29196.986647
37,23,45,5,13,27523.885172,25478.471342
38,24,37,6,14,20596.278869,29057.585772
39,26,33,5,15,28500.000000,30000.000000
40,27,34,4,16,24647.568577,28062.328964
...,...,...,...,...,...,...
18281,26,31,4,16,25562.000000,25385.000000
18282,26,32,2,17,25386.000000,22664.000000
18283,25,33,1,18,22872.000000,15736.000000
18284,23,38,0,19,15825.000000,1407.000000
18285,22,45,0,20,1450.000000,0.000000

In [7]:
y = datos_dia[['Generación']]
y

         Generación
36     27523.885172
37     20596.278869
38     28500.000000
39     24647.568577
40     25500.000000
...             ...
18281  25386.000000
18282  22872.000000
18283  15825.000000
18284   1450.000000
18285      0.000000

[6630 rows x 1 columns]

Dividimos entrenamiento, validación y prueba

In [8]:
train_size = int(0.7 * len(X))
val_size = int(0.85 * len(X))

In [9]:
# Entrenamiento, validación y prueba, 75, 15 y 15
X_train, y_train =  X.iloc[:train_size, :], y.iloc[:train_size, :]
X_val, y_val = X.iloc[train_size:val_size, :], y.iloc[train_size:val_size, :]
X_test, y_test = X.iloc[val_size:, :],  y.iloc[val_size:,:]

print(f'X_train: {len(X_train)}, y_train: {len(y_train)}')
print(f'X_val: {len(X_val)}, y_val: {len(y_val)}')
print(f'X_test: {len(X_test)}, y_test: {len(y_test)}')

X_train: 4641, y_train: 4641
X_val: 994, y_val: 994
X_test: 995, y_test: 995

## Escalar con MinMaxScaler

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [11]:
x_scaler = MinMaxScaler().fit(X_train)
x_scaler

MinMaxScaler()

In [12]:
X_train_scaled = x_scaler.transform(X_train)
print(X_train_scaled)
print(X_train_scaled.shape)

[[0.43333333 0.7761194  0.28571429 0.4        0.56786811 0.97323289]
 [0.5        0.59701493 0.35714286 0.46666667 0.91746284 0.84928238]
 [0.53333333 0.47761194 0.42857143 0.53333333 0.68654263 0.96858619]
 ...
 [0.53333333 0.08955224 0.28571429 0.4        0.89256667 0.71003333]
 [0.6        0.04477612 0.28571429 0.46666667 0.89183333 0.6942    ]
 [0.66666667 0.02985075 0.28571429 0.53333333 0.884      0.67946667]]
(4641, 6)

In [13]:
X_train_scaled_df = pd.DataFrame(X_train_scaled, index=X_train.index, columns=X_train.columns)
X_train_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
36,0.433333,0.776119,0.285714,0.400000,0.567868,0.973233
37,0.500000,0.597015,0.357143,0.466667,0.917463,0.849282
38,0.533333,0.477612,0.428571,0.533333,0.686543,0.968586
39,0.600000,0.417910,0.357143,0.600000,0.950000,1.000000
40,0.633333,0.432836,0.285714,0.666667,0.821586,0.935411
...,...,...,...,...,...,...
13283,0.266667,0.253731,0.142857,0.266667,0.261667,0.703733
13284,0.400000,0.149254,0.214286,0.333333,0.847233,0.716300
13285,0.533333,0.089552,0.285714,0.400000,0.892567,0.710033
13286,0.600000,0.044776,0.285714,0.466667,0.891833,0.694200
13287,0.666667,0.029851,0.285714,0.533333,0.884000,0.679467

In [14]:
X_val_scaled = x_scaler.transform(X_val)
print(X_val_scaled)
print(X_val_scaled.shape)

[[0.7        0.02985075 0.21428571 0.6        0.88153333 0.68466667]
 [0.76666667 0.02985075 0.14285714 0.66666667 0.89283333 0.6928    ]
 [0.8        0.01492537 0.07142857 0.73333333 0.89383333 0.66686667]
 ...
 [0.73333333 0.41791045 0.85714286 0.4        0.94243333 0.95253333]
 [0.8        0.29850746 1.         0.46666667 0.94176667 0.95486667]
 [0.83333333 0.2238806  0.85714286 0.53333333 0.93916667 0.97816667]]
(994, 6)

In [15]:
X_val_scaled_df = pd.DataFrame(X_val_scaled, index=X_val.index, columns=X_val.columns)
X_val_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
13288,0.700000,0.029851,0.214286,0.600000,0.881533,0.684667
13289,0.766667,0.029851,0.142857,0.666667,0.892833,0.692800
13290,0.800000,0.014925,0.071429,0.733333,0.893833,0.666867
13291,0.766667,0.014925,0.000000,0.800000,0.853433,0.491367
13292,0.700000,0.029851,0.000000,0.866667,0.514800,0.095967
...,...,...,...,...,...,...
15323,0.533333,0.805970,0.357143,0.266667,0.846533,0.940067
15324,0.633333,0.582090,0.642857,0.333333,0.911033,0.968733
15325,0.733333,0.417910,0.857143,0.400000,0.942433,0.952533
15326,0.800000,0.298507,1.000000,0.466667,0.941767,0.954867
15327,0.833333,0.223881,0.857143,0.533333,0.939167,0.978167

In [16]:
X_test_scaled = x_scaler.transform(X_test)
print(X_test_scaled)
print(X_test_scaled.shape)

[[0.9        0.1641791  0.64285714 0.6        0.93993333 0.95946667]
 [0.96666667 0.11940299 0.35714286 0.66666667 0.9288     0.94446667]
 [0.93333333 0.11940299 0.21428571 0.73333333 0.8208     0.89293333]
 ...
 [0.56666667 0.41791045 0.07142857 0.8        0.7624     0.52453333]
 [0.5        0.49253731 0.         0.86666667 0.5275     0.0469    ]
 [0.46666667 0.59701493 0.         0.93333333 0.04833333 0.        ]]
(995, 6)

In [17]:
X_test_scaled_df = pd.DataFrame(X_test_scaled, index=X_test.index, columns=X_test.columns)
X_test_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
15328,0.900000,0.164179,0.642857,0.600000,0.939933,0.959467
15329,0.966667,0.119403,0.357143,0.666667,0.928800,0.944467
15330,0.933333,0.119403,0.214286,0.733333,0.820800,0.892933
15331,0.900000,0.134328,0.142857,0.800000,0.788567,0.768000
15332,0.833333,0.179104,0.071429,0.866667,0.689433,0.349533
...,...,...,...,...,...,...
18281,0.600000,0.388060,0.285714,0.666667,0.852067,0.846167
18282,0.600000,0.402985,0.142857,0.733333,0.846200,0.755467
18283,0.566667,0.417910,0.071429,0.800000,0.762400,0.524533
18284,0.500000,0.492537,0.000000,0.866667,0.527500,0.046900
18285,0.466667,0.597015,0.000000,0.933333,0.048333,0.000000

In [18]:
x_scaller_all = MinMaxScaler().fit(X)
print(x_scaller_all)

MinMaxScaler()

In [19]:
X_scaled = x_scaller_all.transform(X)
print(X_scaled)
print(X_scaled.shape)

[[0.41935484 0.76056338 0.28571429 0.4        0.56786811 0.97323289]
 [0.48387097 0.5915493  0.35714286 0.46666667 0.91746284 0.84928238]
 [0.51612903 0.47887324 0.42857143 0.53333333 0.68654263 0.96858619]
 ...
 [0.5483871  0.42253521 0.07142857 0.8        0.7624     0.52453333]
 [0.48387097 0.49295775 0.         0.86666667 0.5275     0.0469    ]
 [0.4516129  0.5915493  0.         0.93333333 0.04833333 0.        ]]
(6630, 6)

In [20]:
X_scaled_df = pd.DataFrame(X_scaled, index=X.index, columns=X.columns)
X_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
36,0.419355,0.760563,0.285714,0.400000,0.567868,0.973233
37,0.483871,0.591549,0.357143,0.466667,0.917463,0.849282
38,0.516129,0.478873,0.428571,0.533333,0.686543,0.968586
39,0.580645,0.422535,0.357143,0.600000,0.950000,1.000000
40,0.612903,0.436620,0.285714,0.666667,0.821586,0.935411
...,...,...,...,...,...,...
18281,0.580645,0.394366,0.285714,0.666667,0.852067,0.846167
18282,0.580645,0.408451,0.142857,0.733333,0.846200,0.755467
18283,0.548387,0.422535,0.071429,0.800000,0.762400,0.524533
18284,0.483871,0.492958,0.000000,0.866667,0.527500,0.046900
18285,0.451613,0.591549,0.000000,0.933333,0.048333,0.000000

In [21]:
y_scaler = MinMaxScaler().fit(y_train)
print(y_scaler)

MinMaxScaler()

In [22]:
y_train_scaled = y_scaler.transform(y_train)
print(y_train_scaled)
print(y_train_scaled.shape)

[[0.91746284]
 [0.68654263]
 [0.95      ]
 ...
 [0.89183333]
 [0.884     ]
 [0.88153333]]
(4641, 1)

In [23]:
y_train_scaled_df = pd.DataFrame(y_train_scaled, index=y_train.index, columns=y_train.columns)
y_train_scaled_df

       Generación
36       0.917463
37       0.686543
38       0.950000
39       0.821586
40       0.850000
...           ...
13283    0.847233
13284    0.892567
13285    0.891833
13286    0.884000
13287    0.881533

[4641 rows x 1 columns]

In [24]:
y_val_scaled = y_scaler.transform(y_val)
print(y_val_scaled)
print(y_val_scaled.shape)

[[8.92833333e-01]
 [8.93833333e-01]
 [8.53433333e-01]
 [5.14800000e-01]
 [5.18333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.03733333e-01]
 [6.26766667e-01]
 [7.09333333e-01]
 [7.83833333e-01]
 [6.76500000e-01]
 [6.85366667e-01]
 [6.87533333e-01]
 [6.60733333e-01]
 [4.83800000e-01]
 [9.24333333e-02]
 [0.00000000e+00]
 [6.76500000e-01]
 [6.89666667e-01]
 [7.04466667e-01]
 [6.53366667e-01]
 [4.85666667e-01]
 [6.37866667e-01]
 [6.10033333e-01]
 [5.91933333e-01]
 [5.99333333e-01]
 [6.08266667e-01]
 [6.53366667e-01]
 [4.23333333e-01]
 [9.31666667e-02]
 [8.27966667e-01]
 [7.89800000e-01]
 [8.75533333e-01]
 [8.66100000e-01]
 [8.54000000e-01]
 [7.82533333e-01]
 [7.58700000e-01]
 [5.93666667e-01]
 [1.34566667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.95366667e-01]
 [8.78733333e-01]
 [8.57166667e-01]
 [8.45600000e-01]
 [8.68233333e-01]
 [8.61400000e-01]
 [8.16733333e-01]
 [6.21266667e-01]
 [1.01333333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.48333333e-01]
 [9.95633333e-01]
 [9.94466667e-01]
 [9.95933333e-01]
 [9.86300000e-01]
 [9.94966667e-01]
 [9.92933333e-01]
 [8.74533333e-01]
 [4.33266667e-01]
 [4.10333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.79666667e-01]
 [8.95366667e-01]
 [8.88700000e-01]
 [8.63266667e-01]
 [8.45600000e-01]
 [6.92400000e-01]
 [6.88233333e-01]
 [7.55933333e-01]
 [4.88400000e-01]
 [1.12600000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.79666667e-01]
 [8.98466667e-01]
 [7.95000000e-01]
 [7.71466667e-01]
 [6.76500000e-01]
 [6.89233333e-01]
 [6.07833333e-01]
 [4.00200000e-01]
 [3.87033333e-01]
 [9.06333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.98300000e-01]
 [8.68166667e-01]
 [8.62933333e-01]
 [8.52733333e-01]
 [8.66466667e-01]
 [8.47600000e-01]
 [6.41966667e-01]
 [4.83833333e-01]
 [9.58000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.24333333e-01]
 [7.97966667e-01]
 [8.61000000e-01]
 [8.58433333e-01]
 [8.62066667e-01]
 [8.68733333e-01]
 [8.07700000e-01]
 [5.96633333e-01]
 [6.85733333e-01]
 [6.81133333e-01]
 [7.68600000e-01]
 [9.80400000e-01]
 [9.75433333e-01]
 [9.28733333e-01]
 [9.71900000e-01]
 [9.31933333e-01]
 [5.67633333e-01]
 [6.32233333e-01]
 [8.27033333e-01]
 [6.72166667e-01]
 [1.34900000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.40666667e-01]
 [9.62433333e-01]
 [8.77033333e-01]
 [8.78666667e-01]
 [8.45600000e-01]
 [9.33600000e-01]
 [8.93933333e-01]
 [8.16733333e-01]
 [6.21266667e-01]
 [1.34900000e-01]
 [2.00000000e-04]
 [0.00000000e+00]
 [9.28266667e-01]
 [9.40400000e-01]
 [9.29966667e-01]
 [9.21166667e-01]
 [9.04100000e-01]
 [9.32766667e-01]
 [9.17500000e-01]
 [8.86200000e-01]
 [6.76433333e-01]
 [1.34900000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.41633333e-01]
 [9.27633333e-01]
 [9.38033333e-01]
 [8.38033333e-01]
 [7.15233333e-01]
 [8.17833333e-01]
 [8.14000000e-01]
 [5.41133333e-01]
 [9.63333333e-02]
 [7.49966667e-01]
 [7.56900000e-01]
 [7.67166667e-01]
 [7.36500000e-01]
 [7.29200000e-01]
 [6.37000000e-01]
 [7.18033333e-01]
 [5.17733333e-01]
 [1.03866667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.66666667e-04]
 [5.93533333e-01]
 [7.68333333e-01]
 [9.49966667e-01]
 [9.51900000e-01]
 [9.51733333e-01]
 [9.75366667e-01]
 [9.35800000e-01]
 [9.04766667e-01]
 [9.29900000e-01]
 [9.22133333e-01]
 [6.47666667e-01]
 [1.32900000e-01]
 [3.33333333e-05]
 [0.00000000e+00]
 [7.42033333e-01]
 [9.55433333e-01]
 [8.95366667e-01]
 [9.50333333e-01]
 [9.39933333e-01]
 [9.14666667e-01]
 [8.83566667e-01]
 [8.60766667e-01]
 [8.27766667e-01]
 [6.04733333e-01]
 [1.28500000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.12766667e-01]
 [8.79666667e-01]
 [9.16966667e-01]
 [9.83700000e-01]
 [9.76633333e-01]
 [9.70033333e-01]
 [8.54000000e-01]
 [9.44766667e-01]
 [9.41966667e-01]
 [6.38733333e-01]
 [1.34233333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.79966667e-01]
 [8.78133333e-01]
 [8.63900000e-01]
 [8.60000000e-01]
 [8.59233333e-01]
 [8.16733333e-01]
 [6.04733333e-01]
 [8.95366667e-01]
 [8.88066667e-01]
 [8.60833333e-01]
 [8.59400000e-01]
 [8.73633333e-01]
 [8.61933333e-01]
 [8.16733333e-01]
 [6.57833333e-01]
 [1.33966667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.86333333e-01]
 [9.03966667e-01]
 [8.77033333e-01]
 [8.57166667e-01]
 [8.50866667e-01]
 [8.54000000e-01]
 [7.73300000e-01]
 [7.45766667e-01]
 [5.59166667e-01]
 [9.18666667e-02]
 [3.33333333e-05]
 [0.00000000e+00]
 [4.93366667e-01]
 [7.06200000e-01]
 [7.16300000e-01]
 [7.01633333e-01]
 [6.85733333e-01]
 [6.80666667e-01]
 [6.88833333e-01]
 [6.87366667e-01]
 [6.82566667e-01]
 [4.99900000e-01]
 [9.83666667e-02]
 [6.66666667e-05]
 [0.00000000e+00]
 [6.55566667e-01]
 [7.40466667e-01]
 [7.48766667e-01]
 [7.48700000e-01]
 [7.42566667e-01]
 [7.41066667e-01]
 [7.40600000e-01]
 [7.27733333e-01]
 [7.02333333e-01]
 [5.67033333e-01]
 [1.54833333e-01]
 [1.13333333e-03]
 [0.00000000e+00]
 [9.25600000e-01]
 [9.35966667e-01]
 [9.38166667e-01]
 [9.28233333e-01]
 [9.26366667e-01]
 [9.25733333e-01]
 [9.19733333e-01]
 [8.77900000e-01]
 [7.23600000e-01]
 [1.93533333e-01]
 [1.43333333e-03]
 [0.00000000e+00]
 [9.45666667e-01]
 [9.38600000e-01]
 [9.28233333e-01]
 [9.26366667e-01]
 [9.25733333e-01]
 [9.09666667e-01]
 [8.77900000e-01]
 [7.15266667e-01]
 [2.00866667e-01]
 [1.60000000e-03]
 [9.43833333e-01]
 [9.43233333e-01]
 [9.40500000e-01]
 [9.26366667e-01]
 [9.32266667e-01]
 [9.13333333e-01]
 [8.77900000e-01]
 [7.08766667e-01]
 [1.93533333e-01]
 [1.43333333e-03]
 [0.00000000e+00]
 [9.95466667e-01]
 [9.95566667e-01]
 [9.94200000e-01]
 [9.87666667e-01]
 [9.69366667e-01]
 [9.55300000e-01]
 [8.80333333e-01]
 [5.72166667e-01]
 [1.18833333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.40466667e-01]
 [7.48766667e-01]
 [7.60500000e-01]
 [7.42566667e-01]
 [7.41066667e-01]
 [7.40600000e-01]
 [8.18700000e-01]
 [7.90133333e-01]
 [5.67033333e-01]
 [1.55000000e-01]
 [1.23333333e-03]
 [0.00000000e+00]
 [6.55566667e-01]
 [7.40466667e-01]
 [7.53133333e-01]
 [7.69133333e-01]
 [7.50566667e-01]
 [7.42333333e-01]
 [7.40600000e-01]
 [7.27733333e-01]
 [7.02333333e-01]
 [5.72700000e-01]
 [1.58866667e-01]
 [1.53333333e-03]
 [0.00000000e+00]
 [7.40466667e-01]
 [7.48766667e-01]
 [7.56266667e-01]
 [7.60966667e-01]
 [7.49200000e-01]
 [7.40600000e-01]
 [6.36766667e-01]
 [6.19600000e-01]
 [5.03100000e-01]
 [1.43233333e-01]
 [1.40000000e-03]
 [0.00000000e+00]
 [3.42366667e-01]
 [8.34100000e-01]
 [9.25600000e-01]
 [9.35966667e-01]
 [9.50600000e-01]
 [9.28233333e-01]
 [9.34933333e-01]
 [9.27933333e-01]
 [9.19733333e-01]
 [8.85233333e-01]
 [7.12900000e-01]
 [1.93533333e-01]
 [1.53333333e-03]
 [0.00000000e+00]
 [3.80700000e-01]
 [8.66833333e-01]
 [9.74500000e-01]
 [9.95466667e-01]
 [9.95433333e-01]
 [9.94366667e-01]
 [9.85700000e-01]
 [9.95466667e-01]
 [9.61066667e-01]
 [8.29166667e-01]
 [5.44333333e-01]
 [1.08133333e-01]
 [3.33333333e-05]
 [0.00000000e+00]
 [9.25600000e-01]
 [9.35966667e-01]
 [9.38666667e-01]
 [8.46000000e-01]
 [8.37066667e-01]
 [7.42366667e-01]
 [7.27733333e-01]
 [7.90133333e-01]
 [6.37900000e-01]
 [1.54833333e-01]
 [1.13333333e-03]
 [0.00000000e+00]
 [7.48566667e-01]
 [7.49766667e-01]
 [7.54766667e-01]
 [7.52966667e-01]
 [7.50966667e-01]
 [6.56566667e-01]
 [6.55966667e-01]
 [6.14533333e-01]
 [5.72466667e-01]
 [1.54833333e-01]
 [1.13333333e-03]
 [0.00000000e+00]
 [9.35966667e-01]
 [8.42266667e-01]
 [7.42566667e-01]
 [9.28733333e-01]
 [9.25733333e-01]
 [9.09666667e-01]
 [8.85233333e-01]
 [6.39533333e-01]
 [1.65300000e-01]
 [1.73333333e-03]
 [0.00000000e+00]
 [7.48766667e-01]
 [7.55500000e-01]
 [7.48433333e-01]
 [8.33766667e-01]
 [7.43200000e-01]
 [8.18700000e-01]
 [7.98633333e-01]
 [6.37900000e-01]
 [2.08033333e-01]
 [1.76666667e-03]
 [0.00000000e+00]
 [9.35966667e-01]
 [9.35866667e-01]
 [9.30333333e-01]
 [9.34100000e-01]
 [9.35533333e-01]
 [5.46000000e-01]
 [5.34800000e-01]
 [4.25333333e-01]
 [1.48633333e-01]
 [1.56666667e-03]
 [0.00000000e+00]
 [7.64600000e-01]
 [7.68100000e-01]
 [7.65933333e-01]
 [7.58566667e-01]
 [7.55666667e-01]
 [6.59333333e-01]
 [7.54133333e-01]
 [7.20366667e-01]
 [6.26533333e-01]
 [1.58300000e-01]
 [1.40000000e-03]
 [0.00000000e+00]
 [7.62200000e-01]
 [8.57766667e-01]
 [8.80800000e-01]
 [7.52700000e-01]
 [8.57333333e-01]
 [7.59900000e-01]
 [7.50133333e-01]
 [7.21133333e-01]
 [5.39600000e-01]
 [1.97433333e-01]
 [2.83333333e-03]
 [0.00000000e+00]
 [8.79100000e-01]
 [8.84933333e-01]
 [8.48900000e-01]
 [8.57233333e-01]
 [8.53933333e-01]
 [7.48133333e-01]
 [7.17766667e-01]
 [6.09200000e-01]
 [1.62733333e-01]
 [3.23333333e-03]
 [0.00000000e+00]
 [9.96700000e-01]
 [9.97000000e-01]
 [9.97600000e-01]
 [9.94600000e-01]
 [9.61233333e-01]
 [9.12066667e-01]
 [8.52033333e-01]
 [5.46600000e-01]
 [7.90333333e-02]
 [0.00000000e+00]
 [9.53066667e-01]
 [9.50766667e-01]
 [9.40866667e-01]
 [9.51733333e-01]
 [9.49866667e-01]
 [9.37666667e-01]
 [9.01433333e-01]
 [7.73033333e-01]
 [2.57900000e-01]
 [3.46666667e-03]
 [0.00000000e+00]
 [8.66900000e-01]
 [7.62466667e-01]
 [7.62033333e-01]
 [8.50033333e-01]
 [9.52566667e-01]
 [9.49866667e-01]
 [8.43900000e-01]
 [8.10266667e-01]
 [6.97233333e-01]
 [2.65466667e-01]
 [4.54800000e-01]
 [7.52700000e-01]
 [7.62066667e-01]
 [7.59900000e-01]
 [9.37666667e-01]
 [9.71333333e-01]
 [9.85466667e-01]
 [9.71233333e-01]
 [9.52566667e-01]
 [9.49866667e-01]
 [9.37666667e-01]
 [9.01433333e-01]
 [7.74700000e-01]
 [2.49433333e-01]
 [2.73333333e-03]
 [9.68300000e-01]
 [9.85466667e-01]
 [9.71233333e-01]
 [9.52566667e-01]
 [9.49866667e-01]
 [8.40366667e-01]
 [7.17966667e-01]
 [6.85333333e-01]
 [2.01966667e-01]
 [3.80000000e-03]
 [0.00000000e+00]
 [9.95766667e-01]
 [9.96533333e-01]
 [9.95033333e-01]
 [9.83733333e-01]
 [1.00000000e+00]
 [9.84933333e-01]
 [9.31033333e-01]
 [7.18566667e-01]
 [1.62233333e-01]
 [2.66666667e-04]
 [0.00000000e+00]
 [7.57933333e-01]
 [9.64766667e-01]
 [9.81133333e-01]
 [9.63200000e-01]
 [9.37400000e-01]
 [9.37700000e-01]
 [9.21500000e-01]
 [8.86033333e-01]
 [7.33966667e-01]
 [2.35400000e-01]
 [6.50000000e-03]
 [0.00000000e+00]
 [4.26866667e-01]
 [8.85433333e-01]
 [9.77866667e-01]
 [9.44766667e-01]
 [9.78233333e-01]
 [9.71066667e-01]
 [9.53666667e-01]
 [9.46333333e-01]
 [9.36966667e-01]
 [9.04700000e-01]
 [7.61466667e-01]
 [2.68533333e-01]
 [4.10000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.40333333e-02]
 [4.63500000e-01]
 [8.89200000e-01]
 [9.82566667e-01]
 [9.59700000e-01]
 [9.80800000e-01]
 [9.82000000e-01]
 [9.54566667e-01]
 [9.52566667e-01]
 [9.41300000e-01]
 [9.06166667e-01]
 [7.84833333e-01]
 [2.75000000e-01]
 [4.23333333e-03]
 [0.00000000e+00]
 [9.43300000e-01]
 [9.80200000e-01]
 [9.70766667e-01]
 [9.51266667e-01]
 [9.57466667e-01]
 [9.40866667e-01]
 [9.07500000e-01]
 [7.73100000e-01]
 [2.98533333e-01]
 [2.60000000e-03]
 [0.00000000e+00]
 [9.70566667e-01]
 [9.83000000e-01]
 [8.74100000e-01]
 [7.62066667e-01]
 [7.59900000e-01]
 [7.50133333e-01]
 [7.21133333e-01]
 [6.09200000e-01]
 [2.20066667e-01]
 [4.03333333e-03]
 [0.00000000e+00]
 [8.59000000e-01]
 [9.58833333e-01]
 [9.36833333e-01]
 [9.42933333e-01]
 [9.39366667e-01]
 [9.40033333e-01]
 [9.18133333e-01]
 [8.82033333e-01]
 [7.18600000e-01]
 [2.73700000e-01]
 [9.46666667e-03]
 [0.00000000e+00]
 [3.75833333e-01]
 [7.45533333e-01]
 [7.42033333e-01]
 [7.50933333e-01]
 [7.49466667e-01]
 [7.54333333e-01]
 [8.42366667e-01]
 [8.33833333e-01]
 [7.20566667e-01]
 [6.79966667e-01]
 [5.74900000e-01]
 [2.18966667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [8.15366667e-01]
 [9.09966667e-01]
 [9.42600000e-01]
 [9.46833333e-01]
 [9.28933333e-01]
 [9.32600000e-01]
 [9.26466667e-01]
 [8.09866667e-01]
 [7.69533333e-01]
 [5.74900000e-01]
 [2.20233333e-01]
 [7.80000000e-03]
 [0.00000000e+00]
 [6.32733333e-01]
 [8.39866667e-01]
 [9.36833333e-01]
 [9.36533333e-01]
 [9.33733333e-01]
 [8.33833333e-01]
 [8.10266667e-01]
 [7.64966667e-01]
 [7.18600000e-01]
 [2.85100000e-01]
 [9.70000000e-03]
 [0.00000000e+00]
 [8.11933333e-01]
 [9.33333333e-01]
 [9.38766667e-01]
 [9.45133333e-01]
 [8.40200000e-01]
 [7.42666667e-01]
 [8.09866667e-01]
 [8.51300000e-01]
 [7.18600000e-01]
 [2.86200000e-01]
 [1.03333333e-02]
 [0.00000000e+00]
 [7.26833333e-01]
 [7.47700000e-01]
 [7.49466667e-01]
 [8.50133333e-01]
 [8.45200000e-01]
 [8.39266667e-01]
 [7.20000000e-01]
 [6.84566667e-01]
 [5.74900000e-01]
 [2.98200000e-01]
 [1.05000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.05666667e-02]
 [3.93466667e-01]
 [6.52300000e-01]
 [7.27966667e-01]
 [7.46533333e-01]
 [7.53633333e-01]
 [7.46500000e-01]
 [7.46100000e-01]
 [7.41400000e-01]
 [7.23333333e-01]
 [6.80400000e-01]
 [5.75633333e-01]
 [2.28066667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [5.70766667e-01]
 [7.19233333e-01]
 [7.46533333e-01]
 [6.60366667e-01]
 [6.50233333e-01]
 [7.46100000e-01]
 [7.41166667e-01]
 [6.29900000e-01]
 [5.94966667e-01]
 [5.82866667e-01]
 [2.26866667e-01]
 [7.63333333e-03]
 [0.00000000e+00]
 [4.22800000e-01]
 [6.52300000e-01]
 [8.98300000e-01]
 [9.42600000e-01]
 [9.40133333e-01]
 [9.34366667e-01]
 [8.39366667e-01]
 [8.33833333e-01]
 [6.33700000e-01]
 [5.11333333e-01]
 [6.46766667e-01]
 [2.46333333e-01]
 [9.73333333e-03]
 [0.00000000e+00]
 [8.15366667e-01]
 [9.05200000e-01]
 [9.38133333e-01]
 [9.36833333e-01]
 [9.36033333e-01]
 [9.33733333e-01]
 [8.33833333e-01]
 [8.09866667e-01]
 [8.72800000e-01]
 [7.55366667e-01]
 [3.07166667e-01]
 [8.93333333e-03]
 [0.00000000e+00]
 [8.57133333e-01]
 [9.20300000e-01]
 [9.67966667e-01]
 [9.48966667e-01]
 [9.36900000e-01]
 [9.33266667e-01]
 [9.26466667e-01]
 [8.99866667e-01]
 [7.64966667e-01]
 [5.11633333e-01]
 [1.64200000e-01]
 [6.30000000e-03]
 [0.00000000e+00]
 [8.31733333e-01]
 [9.62566667e-01]
 [9.53566667e-01]
 [8.45700000e-01]
 [8.41600000e-01]
 [7.42200000e-01]
 [6.29900000e-01]
 [5.10000000e-01]
 [5.07933333e-01]
 [2.18966667e-01]
 [9.63333333e-03]
 [0.00000000e+00]
 [4.88366667e-01]
 [8.66500000e-01]
 [9.17300000e-01]
 [9.64300000e-01]
 [9.57766667e-01]
 [9.34333333e-01]
 [9.34400000e-01]
 [9.26466667e-01]
 [8.99866667e-01]
 [8.49966667e-01]
 [7.32000000e-01]
 [2.46333333e-01]
 [1.15000000e-02]
 [0.00000000e+00]
 [8.15366667e-01]
 [9.09966667e-01]
 [9.33200000e-01]
 [9.36833333e-01]
 [8.36033333e-01]
 [8.40566667e-01]
 [8.33833333e-01]
 [7.61866667e-01]
 [9.10933333e-01]
 [6.93933333e-01]
 [2.49333333e-01]
 [9.00000000e-03]
 [0.00000000e+00]
 [7.85633333e-01]
 [7.86966667e-01]
 [7.77733333e-01]
 [7.53266667e-01]
 [9.26466667e-01]
 [8.09866667e-01]
 [8.49966667e-01]
 [5.74900000e-01]
 [2.18966667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [6.94966667e-01]
 [7.50200000e-01]
 [7.66966667e-01]
 [7.78433333e-01]
 [7.85133333e-01]
 [7.75266667e-01]
 [8.73566667e-01]
 [8.55633333e-01]
 [9.04733333e-01]
 [7.97366667e-01]
 [2.79900000e-01]
 [8.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.65000000e-02]
 [4.80066667e-01]
 [8.19466667e-01]
 [9.23433333e-01]
 [9.54966667e-01]
 [9.58666667e-01]
 [9.60966667e-01]
 [8.60433333e-01]
 [8.57166667e-01]
 [7.42933333e-01]
 [7.32166667e-01]
 [5.94933333e-01]
 [2.18966667e-01]
 [8.06666667e-03]
 [0.00000000e+00]
 [9.00233333e-01]
 [9.34766667e-01]
 [9.42000000e-01]
 [9.28933333e-01]
 [9.32600000e-01]
 [9.65300000e-01]
 [9.53833333e-01]
 [8.59966667e-01]
 [7.29466667e-01]
 [2.73700000e-01]
 [9.83333333e-03]
 [0.00000000e+00]
 [9.44200000e-01]
 [9.36833333e-01]
 [9.28933333e-01]
 [9.32600000e-01]
 [9.70633333e-01]
 [9.54733333e-01]
 [8.54300000e-01]
 [7.19966667e-01]
 [2.73700000e-01]
 [9.50000000e-03]
 [0.00000000e+00]
 [9.08266667e-01]
 [9.46966667e-01]
 [9.36900000e-01]
 [9.28933333e-01]
 [9.32600000e-01]
 [9.70633333e-01]
 [9.56866667e-01]
 [8.54666667e-01]
 [7.27666667e-01]
 [2.82700000e-01]
 [1.01666667e-02]
 [0.00000000e+00]
 [7.27966667e-01]
 [7.51000000e-01]
 [9.42900000e-01]
 [9.35066667e-01]
 [8.85000000e-01]
 [8.64733333e-01]
 [7.58300000e-01]
 [7.37733333e-01]
 [6.49833333e-01]
 [3.20966667e-01]
 [1.74000000e-02]
 [0.00000000e+00]
 [8.98300000e-01]
 [9.55633333e-01]
 [9.81366667e-01]
 [9.78833333e-01]
 [9.46833333e-01]
 [9.26466667e-01]
 [8.99866667e-01]
 [8.53966667e-01]
 [7.22833333e-01]
 [2.73700000e-01]
 [2.87666667e-02]
 [0.00000000e+00]
 [9.02500000e-01]
 [9.42600000e-01]
 [9.36833333e-01]
 [9.37533333e-01]
 [9.36300000e-01]
 [9.26466667e-01]
 [8.99866667e-01]
 [8.57966667e-01]
 [7.18600000e-01]
 [2.73700000e-01]
 [1.70666667e-02]
 [0.00000000e+00]
 [9.09966667e-01]
 [9.33200000e-01]
 [9.40566667e-01]
 [9.31866667e-01]
 [9.56766667e-01]
 [8.33833333e-01]
 [8.09866667e-01]
 [7.72500000e-01]
 [6.46766667e-01]
 [2.47566667e-01]
 [1.04333333e-02]
 [0.00000000e+00]
 [9.34533333e-01]
 [9.33200000e-01]
 [9.53700000e-01]
 [8.58433333e-01]
 [7.74533333e-01]
 [7.62633333e-01]
 [7.27633333e-01]
 [7.73966667e-01]
 [6.46766667e-01]
 [2.82900000e-01]
 [1.91000000e-02]
 [0.00000000e+00]
 [9.31033333e-01]
 [9.33200000e-01]
 [9.47900000e-01]
 [9.57766667e-01]
 [9.63166667e-01]
 [9.62400000e-01]
 [9.08200000e-01]
 [8.59200000e-01]
 [7.24766667e-01]
 [2.82266667e-01]
 [1.94666667e-02]
 [0.00000000e+00]
 [9.34800000e-01]
 [9.33200000e-01]
 [9.48400000e-01]
 [9.62033333e-01]
 [9.68766667e-01]
 [9.57766667e-01]
 [7.29533333e-01]
 [6.95366667e-01]
 [5.77333333e-01]
 [2.26266667e-01]
 [1.72666667e-02]
 [0.00000000e+00]
 [8.38900000e-01]
 [9.05900000e-01]
 [9.35533333e-01]
 [9.44133333e-01]
 [8.43766667e-01]
 [8.44833333e-01]
 [9.64166667e-01]
 [8.09866667e-01]
 [6.79966667e-01]
 [5.03033333e-01]
 [1.14966667e-01]
 [8.16666667e-03]
 [0.00000000e+00]
 [9.43966667e-01]
 [9.76166667e-01]
 [9.70166667e-01]
 [9.73133333e-01]
 [9.45833333e-01]
 [9.50100000e-01]
 [9.40366667e-01]
 [8.58366667e-01]
 [7.97133333e-01]
 [3.98800000e-01]
 [2.59333333e-02]
 [0.00000000e+00]
 [9.38266667e-01]
 [9.58200000e-01]
 [9.52766667e-01]
 [9.49633333e-01]
 [9.58566667e-01]
 [9.59300000e-01]
 [9.57033333e-01]
 [8.80700000e-01]
 [8.21566667e-01]
 [3.95600000e-01]
 [2.73333333e-02]
 [0.00000000e+00]
 [9.40066667e-01]
 [9.68733333e-01]
 [9.52533333e-01]
 [9.54866667e-01]
 [9.78166667e-01]
 [9.59466667e-01]
 [9.44466667e-01]
 [8.92933333e-01]
 [7.68000000e-01]
 [3.49533333e-01]
 [2.87666667e-02]
 [0.00000000e+00]
 [9.11033333e-01]
 [9.42433333e-01]
 [9.41766667e-01]
 [9.39166667e-01]
 [9.39933333e-01]]
(994, 1)

In [25]:
y_val_scaled_df = pd.DataFrame(y_val_scaled, index=y_val.index, columns=y_val.columns)
y_val_scaled_df

       Generación
13288    0.892833
13289    0.893833
13290    0.853433
13291    0.514800
13292    0.051833
...           ...
15323    0.911033
15324    0.942433
15325    0.941767
15326    0.939167
15327    0.939933

[994 rows x 1 columns]

In [26]:
y_test_scaled = y_scaler.transform(y_test)
print(y_test_scaled)
print(y_test_scaled.shape)

[[0.9288    ]
 [0.8208    ]
 [0.78856667]
 [0.68943333]
 [0.35676667]
 [0.0301    ]
 [0.        ]
 [0.7288    ]
 [0.77463333]
 [0.7569    ]
 [0.75133333]
 [0.8674    ]
 [0.77346667]
 [0.85126667]
 [0.78006667]
 [0.69566667]
 [0.35676667]
 [0.0335    ]
 [0.        ]
 [0.8673    ]
 [0.94856667]
 [0.97976667]
 [0.9742    ]
 [0.98153333]
 [0.94706667]
 [0.94543333]
 [0.9458    ]
 [0.7962    ]
 [0.73963333]
 [0.37316667]
 [0.02813333]
 [0.        ]
 [0.84413333]
 [0.91103333]
 [0.94243333]
 [0.94176667]
 [0.94386667]
 [0.9725    ]
 [0.9308    ]
 [0.7296    ]
 [0.80933333]
 [0.78803333]
 [0.40506667]
 [0.03346667]
 [0.        ]
 [0.8243    ]
 [0.91103333]
 [0.943     ]
 [0.94176667]
 [0.94886667]
 [0.95573333]
 [0.95593333]
 [0.9241    ]
 [0.86676667]
 [0.76606667]
 [0.42396667]
 [0.0338    ]
 [0.        ]
 [0.8237    ]
 [0.91103333]
 [0.9482    ]
 [0.94176667]
 [0.9482    ]
 [0.96123333]
 [0.95666667]
 [0.91926667]
 [0.86676667]
 [0.6952    ]
 [0.37006667]
 [0.03346667]
 [0.        ]
 [0.91103333]
 [0.9482    ]
 [0.94463333]
 [0.93916667]
 [0.6743    ]
 [0.8359    ]
 [0.8208    ]
 [0.70683333]
 [0.55156667]
 [0.38056667]
 [0.03136667]
 [0.        ]
 [0.7596    ]
 [0.97846667]
 [0.9731    ]
 [0.974     ]
 [0.9657    ]
 [0.8589    ]
 [0.7531    ]
 [0.818     ]
 [0.74176667]
 [0.3495    ]
 [0.02446667]
 [0.        ]
 [0.94716667]
 [0.9805    ]
 [0.9791    ]
 [0.9787    ]
 [0.95886667]
 [0.95263333]
 [0.9354    ]
 [0.9109    ]
 [0.82416667]
 [0.45596667]
 [0.0394    ]
 [0.        ]
 [0.9495    ]
 [0.9808    ]
 [0.98196667]
 [0.97453333]
 [0.9628    ]
 [0.95946667]
 [0.94076667]
 [0.9109    ]
 [0.82416667]
 [0.46683333]
 [0.0379    ]
 [0.        ]
 [0.96563333]
 [0.96843333]
 [0.96723333]
 [0.9436    ]
 [0.93903333]
 [0.92876667]
 [0.89913333]
 [0.6494    ]
 [0.35516667]
 [0.04673333]
 [0.        ]
 [0.9349    ]
 [0.9482    ]
 [0.94176667]
 [0.94283333]
 [0.93653333]
 [0.93116667]
 [0.9193    ]
 [0.785     ]
 [0.7128    ]
 [0.32696667]
 [0.044     ]
 [0.        ]
 [0.93306667]
 [0.9554    ]
 [0.94776667]
 [0.94003333]
 [0.93653333]
 [0.9356    ]
 [0.912     ]
 [0.86676667]
 [0.76606667]
 [0.40376667]
 [0.0505    ]
 [0.        ]
 [0.8319    ]
 [0.95456667]
 [0.97073333]
 [0.97656667]
 [0.94936667]
 [0.9278    ]
 [0.9074    ]
 [0.68956667]
 [0.6108    ]
 [0.37246667]
 [0.04123333]
 [0.        ]
 [0.7711    ]
 [0.60836667]
 [0.85406667]
 [0.94046667]
 [0.9288    ]
 [0.912     ]
 [0.86676667]
 [0.76606667]
 [0.39786667]
 [0.03346667]
 [0.        ]
 [0.9154    ]
 [0.96963333]
 [0.97063333]
 [0.95266667]
 [0.9444    ]
 [0.9288    ]
 [0.912     ]
 [0.86676667]
 [0.76606667]
 [0.404     ]
 [0.03453333]
 [0.        ]
 [0.91876667]
 [0.96546667]
 [0.96666667]
 [0.95023333]
 [0.94056667]
 [0.9288    ]
 [0.912     ]
 [0.86706667]
 [0.77026667]
 [0.41783333]
 [0.03356667]
 [0.        ]
 [0.91623333]
 [0.94683333]
 [0.94586667]
 [0.93916667]
 [0.93653333]
 [0.9356    ]
 [0.912     ]
 [0.86676667]
 [0.77336667]
 [0.3964    ]
 [0.03346667]
 [0.        ]
 [0.90956667]
 [0.93696667]
 [0.94776667]
 [0.94386667]
 [0.94046667]
 [0.9214    ]
 [0.85693333]
 [0.6903    ]
 [0.6948    ]
 [0.3181    ]
 [0.02866667]
 [0.94776667]
 [0.93916667]
 [0.93653333]
 [0.9288    ]
 [0.91493333]
 [0.59166667]
 [0.5925    ]
 [0.58783333]
 [0.59383333]
 [0.94096667]
 [0.94473333]
 [0.9435    ]
 [0.93916667]
 [0.93696667]
 [0.9288    ]
 [0.912     ]
 [0.78006667]
 [0.6946    ]
 [0.94776667]
 [0.94176667]
 [0.94543333]
 [0.95876667]
 [0.94533333]
 [0.9314    ]
 [0.8848    ]
 [0.7935    ]
 [0.42906667]
 [0.94133333]
 [0.94803333]
 [0.94803333]
 [0.95443333]
 [0.95203333]
 [0.9233    ]
 [0.90183333]
 [0.81353333]
 [0.94433333]
 [0.94283333]
 [0.93916667]
 [0.93653333]
 [0.93036667]
 [0.912     ]
 [0.86676667]
 [0.70006667]
 [0.4085    ]
 [0.94176667]
 [0.93916667]
 [0.93653333]
 [0.67313333]
 [0.912     ]
 [0.62406667]
 [0.94193333]
 [0.93916667]
 [0.93653333]
 [0.93386667]
 [0.92616667]
 [0.92313333]
 [0.92316667]
 [0.91553333]
 [0.91063333]
 [0.8989    ]
 [0.86446667]
 [0.77156667]
 [0.9276    ]
 [0.92123333]
 [0.91896667]
 [0.91553333]
 [0.91063333]
 [0.8989    ]
 [0.86173333]
 [0.77603333]
 [0.92123333]
 [0.91896667]
 [0.9173    ]
 [0.9135    ]
 [0.90476667]
 [0.86173333]
 [0.7702    ]
 [0.36326667]
 [0.93066667]
 [0.9218    ]
 [0.9522    ]
 [0.9401    ]
 [0.8244    ]
 [0.444     ]
 [0.42223333]
 [0.69733333]
 [0.39323333]
 [0.03236667]
 [0.378     ]
 [0.32013333]
 [0.316     ]
 [0.37496667]
 [0.35636667]
 [0.3083    ]
 [0.336     ]
 [0.32383333]
 [0.19636667]
 [0.0184    ]
 [0.9       ]
 [0.89676667]
 [0.8788    ]
 [0.89866667]
 [0.842     ]
 [0.85893333]
 [0.80036667]
 [0.7702    ]
 [0.32726667]
 [0.03023333]
 [0.9       ]
 [0.9       ]
 [0.87366667]
 [0.9       ]
 [0.84603333]
 [0.85996667]
 [0.80066667]
 [0.7702    ]
 [0.42076667]
 [0.03893333]
 [0.9304    ]
 [0.92123333]
 [0.83      ]
 [0.91613333]
 [0.91063333]
 [0.90623333]
 [0.86173333]
 [0.77143333]
 [0.35383333]
 [0.04793333]
 [0.63076667]
 [0.65176667]
 [0.71903333]
 [0.7635    ]
 [0.7987    ]
 [0.74013333]
 [0.91553333]
 [0.82056667]
 [0.6512    ]
 [0.55643333]
 [0.27      ]
 [0.26786667]
 [0.26763333]
 [0.28973333]
 [0.16096667]
 [0.2012    ]
 [0.2518    ]
 [0.405     ]
 [0.32163333]
 [0.40356667]
 [0.36216667]
 [0.36216667]
 [0.4346    ]
 [0.3771    ]
 [0.34846667]
 [0.9       ]
 [0.8863    ]
 [0.9       ]
 [0.8048    ]
 [0.8048    ]
 [0.3632    ]
 [0.37996667]
 [0.34693333]
 [0.20373333]
 [0.51786667]
 [0.6633    ]
 [0.73633333]
 [0.75536667]
 [0.7569    ]
 [0.38693333]
 [0.36546667]
 [0.3293    ]
 [0.24296667]
 [0.3966    ]
 [0.39583333]
 [0.38616667]
 [0.5203    ]
 [0.39356667]
 [0.45426667]
 [0.4549    ]
 [0.45376667]
 [0.27963333]
 [0.28206667]
 [0.392     ]
 [0.4501    ]
 [0.39206667]
 [0.39176667]
 [0.4462    ]
 [0.58406667]
 [0.89363333]
 [0.79943333]
 [0.92476667]
 [0.83566667]
 [0.84806667]
 [0.85176667]
 [0.8617    ]
 [0.80903333]
 [0.78476667]
 [0.70753333]
 [0.39843333]
 [0.92476667]
 [0.93596667]
 [0.9438    ]
 [0.95016667]
 [0.95743333]
 [0.8989    ]
 [0.8784    ]
 [0.77786667]
 [0.92476667]
 [0.9375    ]
 [0.95086667]
 [0.95153333]
 [0.95743333]
 [0.8989    ]
 [0.87786667]
 [0.7854    ]
 [0.8524    ]
 [0.8321    ]
 [0.9522    ]
 [0.6613    ]
 [0.65823333]
 [0.57636667]
 [0.4958    ]
 [0.3774    ]
 [0.39263333]
 [0.39453333]
 [0.46656667]
 [0.4486    ]
 [0.51253333]
 [0.5035    ]
 [0.62146667]
 [0.66073333]
 [0.66416667]
 [0.688     ]
 [0.66283333]
 [0.65876667]
 [0.63633333]
 [0.92123333]
 [0.9215    ]
 [0.91553333]
 [0.91133333]
 [0.8989    ]
 [0.92446667]
 [0.92853333]
 [0.91553333]
 [0.91063333]
 [0.7407    ]
 [0.737     ]
 [0.83793333]
 [0.824     ]
 [0.82563333]
 [0.5772    ]
 [0.5515    ]
 [0.49453333]
 [0.31843333]
 [0.92456667]
 [0.94646667]
 [0.95036667]
 [0.94076667]
 [0.9155    ]
 [0.89793333]
 [0.7702    ]
 [0.92476667]
 [0.92123333]
 [0.91896667]
 [0.91553333]
 [0.81956667]
 [0.82336667]
 [0.86173333]
 [0.79553333]
 [0.37243333]
 [0.92196667]
 [0.92623333]
 [0.92043333]
 [0.9242    ]
 [0.9156    ]
 [0.9099    ]
 [0.865     ]
 [0.69463333]
 [0.2981    ]
 [0.92236667]
 [0.8345    ]
 [0.72543333]
 [0.82626667]
 [0.9101    ]
 [0.78643333]
 [0.69196667]
 [0.63806667]
 [0.3462    ]
 [0.92196667]
 [0.92103333]
 [0.9068    ]
 [0.91263333]
 [0.90873333]
 [0.9093    ]
 [0.87486667]
 [0.78106667]
 [0.38866667]
 [0.02246667]
 [0.92196667]
 [0.92593333]
 [0.90816667]
 [0.92106667]
 [0.9109    ]
 [0.9121    ]
 [0.86623333]
 [0.78116667]
 [0.39193333]
 [0.02276667]
 [0.92196667]
 [0.92456667]
 [0.90863333]
 [0.9157    ]
 [0.91783333]
 [0.8249    ]
 [0.78143333]
 [0.69826667]
 [0.39193333]
 [0.92613333]
 [0.92293333]
 [0.9093    ]
 [0.90856667]
 [0.90463333]
 [0.88623333]
 [0.87336667]
 [0.8009    ]
 [0.3411    ]
 [0.01933333]
 [0.        ]
 [0.8344    ]
 [0.92103333]
 [0.90856667]
 [0.9144    ]
 [0.81956667]
 [0.8202    ]
 [0.8783    ]
 [0.80133333]
 [0.36993333]
 [0.0213    ]
 [0.        ]
 [0.92196667]
 [0.92103333]
 [0.91476667]
 [0.9144    ]
 [0.90236667]
 [0.87806667]
 [0.85183333]
 [0.71376667]
 [0.30506667]
 [0.0167    ]
 [0.83153333]
 [0.73783333]
 [0.72696667]
 [0.72986667]
 [0.90236667]
 [0.87826667]
 [0.76673333]
 [0.67466667]
 [0.28106667]
 [0.92473333]
 [0.93346667]
 [0.93503333]
 [0.90513333]
 [0.90503333]
 [0.87786667]
 [0.74743333]
 [0.44653333]
 [0.1602    ]
 [0.92626667]
 [0.9386    ]
 [0.9374    ]
 [0.90716667]
 [0.81213333]
 [0.88676667]
 [0.83873333]
 [0.64      ]
 [0.22886667]
 [0.92556667]
 [0.93563333]
 [0.93943333]
 [0.90893333]
 [0.90616667]
 [0.87896667]
 [0.83016667]
 [0.64546667]
 [0.73936667]
 [0.72716667]
 [0.726     ]
 [0.90576667]
 [0.9074    ]
 [0.89053333]
 [0.71376667]
 [0.92393333]
 [0.93076667]
 [0.92466667]
 [0.919     ]
 [0.9105    ]
 [0.90826667]
 [0.73996667]
 [0.60356667]
 [0.35273333]
 [0.9374    ]
 [0.9068    ]
 [0.91156667]
 [0.81476667]
 [0.78376667]
 [0.74533333]
 [0.59436667]
 [0.939     ]
 [0.9426    ]
 [0.94876667]
 [0.954     ]
 [0.94613333]
 [0.7099    ]
 [0.73996667]
 [0.57583333]
 [0.93453333]
 [0.92463333]
 [0.91673333]
 [0.94343333]
 [0.92596667]
 [0.89053333]
 [0.6747    ]
 [0.93386667]
 [0.9326    ]
 [0.92056667]
 [0.9436    ]
 [0.66456667]
 [0.5003    ]
 [0.6026    ]
 [0.27746667]
 [0.75203333]
 [0.75153333]
 [0.73483333]
 [0.75106667]
 [0.74076667]
 [0.70643333]
 [0.55113333]
 [0.24633333]
 [0.74626667]
 [0.74663333]
 [0.7315    ]
 [0.7242    ]
 [0.69666667]
 [0.66436667]
 [0.51526667]
 [0.18306667]
 [0.97796667]
 [0.92286667]
 [0.95126667]
 [0.93203333]
 [0.8664    ]
 [0.832     ]
 [0.8181    ]
 [0.60666667]
 [0.99603333]
 [0.9275    ]
 [0.94186667]
 [0.93336667]
 [0.7441    ]
 [0.71483333]
 [0.7251    ]
 [0.5234    ]
 [0.12676667]
 [0.92196667]
 [0.92473333]
 [0.91503333]
 [0.9171    ]
 [0.9446    ]
 [0.8959    ]
 [0.87016667]
 [0.72956667]
 [0.27533333]
 [0.96206667]
 [0.86333333]
 [0.86216667]
 [0.76416667]
 [0.756     ]
 [0.74076667]
 [0.71673333]
 [0.59863333]
 [0.18846667]
 [0.96596667]
 [0.96363333]
 [0.9583    ]
 [0.9552    ]
 [0.95      ]
 [0.92596667]
 [0.8974    ]
 [0.76766667]
 [0.20596667]
 [0.00503333]
 [0.96846667]
 [0.96363333]
 [0.9616    ]
 [0.9552    ]
 [0.95      ]
 [0.92596667]
 [0.88663333]
 [0.75743333]
 [0.23426667]
 [0.92196667]
 [0.92103333]
 [0.9068    ]
 [0.90693333]
 [0.90326667]
 [0.90243333]
 [0.87916667]
 [0.57983333]
 [0.21093333]
 [0.95373333]
 [0.93163333]
 [0.93036667]
 [0.93206667]
 [0.93726667]
 [0.91026667]
 [0.7636    ]
 [0.6073    ]
 [0.18306667]
 [0.96083333]
 [0.92233333]
 [0.90866667]
 [0.90966667]
 [0.90236667]
 [0.87976667]
 [0.8222    ]
 [0.6484    ]
 [0.22886667]
 [0.82976667]
 [0.8321    ]
 [0.91196667]
 [0.81583333]
 [0.6497    ]
 [0.49086667]
 [0.59793333]
 [0.5747    ]
 [0.20596667]
 [0.82976667]
 [0.82893333]
 [0.81613333]
 [0.6591    ]
 [0.58003333]
 [0.55733333]
 [0.40286667]
 [0.38563333]
 [0.38703333]
 [0.3811    ]
 [0.38356667]
 [0.38253333]
 [0.4381    ]
 [0.35406667]
 [0.1929    ]
 [0.01676667]
 [0.0828    ]
 [0.08283333]
 [0.082     ]
 [0.0822    ]
 [0.0819    ]
 [0.08046667]
 [0.07586667]
 [0.0574    ]
 [0.39023333]
 [0.27863333]
 [0.27263333]
 [0.27396667]
 [0.2749    ]
 [0.44023333]
 [0.56633333]
 [0.51426667]
 [0.50846667]
 [0.5007    ]
 [0.53933333]
 [0.2123    ]
 [0.43786667]
 [0.37723333]
 [0.08256667]
 [0.26853333]
 [0.31293333]
 [0.647     ]
 [0.38296667]
 [0.378     ]
 [0.38356667]
 [0.43863333]
 [0.50653333]
 [0.56166667]
 [0.68306667]
 [0.52456667]
 [0.5601    ]
 [0.9214    ]
 [0.65593333]
 [0.8941    ]
 [0.8       ]
 [0.64013333]
 [0.8526    ]
 [0.5256    ]
 [0.4984    ]
 [0.58486667]
 [0.58226667]
 [0.71526667]
 [0.71113333]
 [0.70473333]
 [0.1301    ]
 [0.9487    ]
 [0.93423333]
 [0.89173333]
 [0.91693333]
 [0.91146667]
 [0.8941    ]
 [0.89443333]
 [0.71126667]
 [0.1301    ]
 [0.89813333]
 [0.88903333]
 [0.9238    ]
 [0.9137    ]
 [0.90866667]
 [0.87236667]
 [0.62396667]
 [0.1301    ]
 [0.91223333]
 [0.90286667]
 [0.88903333]
 [0.91323333]
 [0.89513333]
 [0.8941    ]
 [0.84303333]
 [0.89286667]
 [0.9185    ]
 [0.8987    ]
 [0.7185    ]
 [0.7143    ]
 [0.8219    ]
 [0.80806667]
 [0.71526667]
 [0.53956667]
 [0.89286667]
 [0.91323333]
 [0.80966667]
 [0.57223333]
 [0.89813333]
 [0.89673333]
 [0.91323333]
 [0.80633333]
 [0.80466667]
 [0.53956667]
 [0.64686667]
 [0.8975    ]
 [0.91416667]
 [0.8992    ]
 [0.4996    ]
 [0.89216667]
 [0.7821    ]
 [0.86836667]
 [0.91403333]
 [0.87446667]
 [0.8313    ]
 [0.922     ]
 [0.89383333]
 [0.91443333]
 [0.87146667]
 [0.906     ]
 [0.87833333]
 [0.6069    ]
 [0.922     ]
 [0.9105    ]
 [0.9114    ]
 [0.91413333]
 [0.906     ]
 [0.87833333]
 [0.59856667]
 [0.89873333]
 [0.89206667]
 [0.89613333]
 [0.89583333]
 [0.88786667]
 [0.86076667]
 [0.5905    ]
 [0.07903333]
 [0.90356667]
 [0.8923    ]
 [0.8883    ]
 [0.82103333]
 [0.85373333]
 [0.7758    ]
 [0.59476667]
 [0.07676667]
 [0.91063333]
 [0.9003    ]
 [0.8923    ]
 [0.89466667]
 [0.89583333]
 [0.7854    ]
 [0.63586667]
 [0.46996667]
 [0.91063333]
 [0.90356667]
 [0.8923    ]
 [0.89613333]
 [0.89583333]
 [0.78563333]
 [0.71536667]
 [0.52683333]
 [0.83453333]
 [0.89136667]
 [0.87756667]
 [0.8949    ]
 [0.88706667]
 [0.8509    ]
 [0.77896667]
 [0.53383333]
 [0.05713333]
 [0.87463333]
 [0.8788    ]
 [0.87466667]
 [0.87696667]
 [0.84476667]
 [0.69613333]
 [0.46423333]
 [0.85716667]
 [0.8817    ]
 [0.8046    ]
 [0.7149    ]
 [0.62646667]
 [0.7777    ]
 [0.72793333]
 [0.5151    ]
 [0.87166667]
 [0.85193333]
 [0.84953333]
 [0.8389    ]
 [0.84076667]
 [0.61913333]
 [0.79653333]
 [0.85433333]
 [0.85406667]
 [0.842     ]
 [0.84313333]
 [0.76006667]
 [0.47626667]
 [0.86963333]
 [0.84993333]
 [0.85183333]
 [0.84156667]
 [0.84376667]
 [0.75776667]
 [0.52603333]
 [0.04826667]
 [0.8727    ]
 [0.85196667]
 [0.85263333]
 [0.84776667]
 [0.8391    ]
 [0.76006667]
 [0.52973333]
 [0.04583333]
 [0.87186667]
 [0.8762    ]
 [0.8551    ]
 [0.8454    ]
 [0.8481    ]
 [0.84616667]
 [0.75546667]
 [0.52453333]
 [0.0469    ]
 [0.8759    ]
 [0.85326667]
 [0.84663333]
 [0.85206667]
 [0.8462    ]
 [0.7624    ]
 [0.5275    ]
 [0.04833333]
 [0.        ]]
(995, 1)

In [27]:
y_test_scaled_df = pd.DataFrame(y_test_scaled, index=y_test.index, columns=y_test.columns)
y_test_scaled_df

       Generación
15328    0.928800
15329    0.820800
15330    0.788567
15331    0.689433
15332    0.356767
...           ...
18281    0.846200
18282    0.762400
18283    0.527500
18284    0.048333
18285    0.000000

[995 rows x 1 columns]

In [28]:
y_scaller_all = MinMaxScaler().fit(y)
print(y_scaller_all)

MinMaxScaler()

In [29]:
y_scaled = y_scaller_all.transform(y)
print(y_scaled)
print(y_scaled.shape)

[[0.91746284]
 [0.68654263]
 [0.95      ]
 ...
 [0.5275    ]
 [0.04833333]
 [0.        ]]
(6630, 1)

In [30]:
y_scaled_df = pd.DataFrame(y_scaled, index=y.index, columns=y.columns)
y_scaled_df

       Generación
36       0.917463
37       0.686543
38       0.950000
39       0.821586
40       0.850000
...           ...
18281    0.846200
18282    0.762400
18283    0.527500
18284    0.048333
18285    0.000000

[6630 rows x 1 columns]

## Preparación para Redes Neuronales

In [31]:
import numpy as np
import pandas as pd

def create_sliding_window_with_index(data_X, data_y, lookback):
    X, y, indices = [], [], []

    # Asegurar que `data_y` tiene los mismos índices que `data_X`
    data_y = data_y.reindex(data_X.index)

    max_index = len(data_X) - lookback

    for i in range(max_index):
        X.append(data_X.iloc[i:i + lookback].values)  # Ventana de entrada

        # Obtener el índice correcto en `data_y`
        y_index = data_X.index[i + lookback]

        # Extraer el valor correspondiente de `data_y`
        if y_index in data_y.index:
            y_value = data_y.loc[y_index]
            if isinstance(y_value, pd.Series):  # Si devuelve una serie, extraer el valor
                y_value = y_value.iloc[0]
        else:
            y_value = np.nan  # Si no está, asignamos NaN

        y.append(y_value)
        indices.append(y_index)  # 🔹 Guardamos el índice original de `data_y`

    # Convertimos `X` en un array y `y` en DataFrame conservando sus índices originales
    X_array = np.array(X)
    y_df = pd.DataFrame(y, index=indices, columns=['y'])  # 🔹 Conservamos los índices originales

    return X_array, y_df

In [32]:
lookback = 48  # Puedes ajustar a 24, 72, etc.

# Aplicar la ventana deslizante a cada conjunto
X_train_windowed, y_train_windowed = create_sliding_window_with_index(X_train_scaled_df, y_train_scaled_df, lookback)
X_val_windowed, y_val_windowed = create_sliding_window_with_index(X_val_scaled_df, y_val_scaled_df, lookback)
X_test_windowed, y_test_windowed = create_sliding_window_with_index(X_test_scaled_df, y_test_scaled_df, lookback)

In [33]:
print(f'X_train: {X_train_windowed.shape}, y_train: {y_train_windowed.shape}')
print(f'X_val: {X_val_windowed.shape}, y_val: {y_val_windowed.shape}')
print(f'X_test: {X_test_windowed.shape}, y_test: {y_test_windowed.shape}')

X_train: (4593, 48, 6), y_train: (4593, 1)
X_val: (946, 48, 6), y_val: (946, 1)
X_test: (947, 48, 6), y_test: (947, 1)

## Optuna

In [34]:
pip install optuna

Collecting optuna
  Downloading optuna-4.2.1-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.15.1-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.38)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna) (6.0.2)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading Mako-1.3.9-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.11/dist-packages (from alembic>=1.5.0->optuna) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.1.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.11/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)
Downloading optuna-4.2.1-py3-none-any.whl (383 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.6/383.6 kB 8.7 MB/s eta 0:00:00
Downloading alembic-1.15.1-py3-none-any.whl (231 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.8/231.8 kB 19.9 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Downloading Mako-1.3.9-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 7.5 MB/s eta 0:00:00
Installing collected packages: Mako, colorlog, alembic, optuna
Successfully installed Mako-1.3.9 alembic-1.15.1 colorlog-6.9.0 optuna-4.2.1

In [35]:
from lightgbm import LGBMRegressor
from sklearn.ensemble import RandomForestRegressor
import optuna
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import seaborn as sns
from sklearn.metrics import mean_absolute_percentage_error as mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error as mean_absolute_error
from sklearn.metrics import mean_squared_error as mean_squared_error
from sklearn.metrics import r2_score as r2_score
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping

### Optimización de LightGBM

In [36]:
import optuna
import numpy as np
import pandas as pd
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_squared_error

# Definir la función de optimización
def objective(trial):
    # Espacio de búsqueda para los hiperparámetros
    num_leaves = trial.suggest_int('num_leaves', 10, 1000)
    subsample = trial.suggest_float('subsample', 0.1, 1.0)
    colsample_bytree = trial.suggest_float('colsample_bytree', 0.1, 1.0)
    min_data_in_leaf = trial.suggest_int('min_data_in_leaf', 10, 100)

    # Modelo LightGBM con los hiperparámetros sugeridos
    model = LGBMRegressor(
        num_leaves=num_leaves,
        subsample=subsample,
        colsample_bytree=colsample_bytree,
        min_data_in_leaf=min_data_in_leaf,
        random_state=42
    )

    # Entrenamos el modelo con los datos de entrenamiento
    model.fit(X_train_scaled_df, y_train_scaled_df)

    # Predicciones en el conjunto de validación
    y_pred = model.predict(X_val_scaled_df)
    rmse = mean_squared_error(y_val_scaled_df, y_pred)

    return rmse  # Optuna minimizará este valor

# Ejecutar la optimización con 50 iteraciones
LightGBM_study = optuna.create_study(direction="minimize")
LightGBM_study.optimize(objective, n_trials=50)

# Obtener los mejores hiperparámetros
best_params = LightGBM_study.best_params
print("Mejores hiperparámetros:", best_params)

[I 2025-03-14 03:13:44,918] A new study created in memory with name: no-name-9a3ff8fa-2dda-459b-aeb8-a524888bd8e4
[I 2025-03-14 03:13:45,132] Trial 0 finished with value: 0.003833215926179182 and parameters: {'num_leaves': 86, 'subsample': 0.34849292732635223, 'colsample_bytree': 0.6577823852250162, 'min_data_in_leaf': 24}. Best is trial 0 with value: 0.003833215926179182.

[LightGBM] [Warning] min_data_in_leaf is set=24, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=24
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=24, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=24
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000981 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] min_data_in_leaf is set=24, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=24
[LightGBM] [Warning] min_data_in_leaf is set=96, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=96

[I 2025-03-14 03:13:45,224] Trial 1 finished with value: 0.0036339970483070688 and parameters: {'num_leaves': 893, 'subsample': 0.155728742319433, 'colsample_bytree': 0.5830236741420652, 'min_data_in_leaf': 96}. Best is trial 1 with value: 0.0036339970483070688.

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=96, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=96
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000131 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=96, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=96
[LightGBM] [Warning] min_data_in_leaf is set=46, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=46
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=46, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=46
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000114 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:45,373] Trial 2 finished with value: 0.0035460621284409406 and parameters: {'num_leaves': 999, 'subsample': 0.11644877197214226, 'colsample_bytree': 0.6542716362752501, 'min_data_in_leaf': 46}. Best is trial 2 with value: 0.0035460621284409406.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=46, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=46
[LightGBM] [Warning] min_data_in_leaf is set=26, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=26
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=26, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=26
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000128 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:45,598] Trial 3 finished with value: 0.004081915104346337 and parameters: {'num_leaves': 581, 'subsample': 0.7079604814637164, 'colsample_bytree': 0.797743920986731, 'min_data_in_leaf': 26}. Best is trial 2 with value: 0.0035460621284409406.
[I 2025-03-14 03:13:45,707] Trial 4 finished with value: 0.004110866405673936 and parameters: {'num_leaves': 101, 'subsample': 0.28083432249904083, 'colsample_bytree': 0.27336441175078086, 'min_data_in_leaf': 46}. Best is trial 2 with value: 0.0035460621284409406.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=26, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=26
[LightGBM] [Warning] min_data_in_leaf is set=46, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=46
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=46, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=46
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000251 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=46, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=46
[LightGBM] [Warning] min_data_in_leaf is set=69, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=69
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=69, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=69
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000134 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:45,806] Trial 5 finished with value: 0.0035702187966677435 and parameters: {'num_leaves': 492, 'subsample': 0.933144601929644, 'colsample_bytree': 0.8093075233919923, 'min_data_in_leaf': 69}. Best is trial 2 with value: 0.0035460621284409406.
[I 2025-03-14 03:13:45,878] Trial 6 finished with value: 0.003480828677603682 and parameters: {'num_leaves': 262, 'subsample': 0.4239723951859832, 'colsample_bytree': 0.6890982894205911, 'min_data_in_leaf': 95}. Best is trial 6 with value: 0.003480828677603682.
[I 2025-03-14 03:13:45,914] Trial 7 finished with value: 0.0034141882433979327 and parameters: {'num_leaves': 14, 'subsample': 0.4760889418510119, 'colsample_bytree': 0.6253614019455985, 'min_data_in_leaf': 32}. Best is trial 7 with value: 0.0034141882433979327.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=69, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=69
[LightGBM] [Warning] min_data_in_leaf is set=95, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=95
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=95, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=95
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000205 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=95, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=95
[LightGBM] [Warning] min_data_in_leaf is set=32, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=32
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=32, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=32
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000133 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] min_data_in_leaf is set=32, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=32
[LightGBM] [Warning] min_data_in_leaf is set=70, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=70
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=70, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=70
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000100 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:46,021] Trial 8 finished with value: 0.0035839162502196223 and parameters: {'num_leaves': 837, 'subsample': 0.8483199302544864, 'colsample_bytree': 0.9657568970365528, 'min_data_in_leaf': 70}. Best is trial 7 with value: 0.0034141882433979327.
[I 2025-03-14 03:13:46,077] Trial 9 finished with value: 0.004275672610114824 and parameters: {'num_leaves': 294, 'subsample': 0.450020377858968, 'colsample_bytree': 0.12091767790313097, 'min_data_in_leaf': 90}. Best is trial 7 with value: 0.0034141882433979327.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=70, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=70
[LightGBM] [Warning] min_data_in_leaf is set=90, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=90
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=90, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=90
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000107 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=90, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=90
[LightGBM] [Warning] min_data_in_leaf is set=10, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=10
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=10, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=10
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000041 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:46,662] Trial 10 finished with value: 0.004384634919258435 and parameters: {'num_leaves': 619, 'subsample': 0.6232988552669811, 'colsample_bytree': 0.33332596008862714, 'min_data_in_leaf': 10}. Best is trial 7 with value: 0.0034141882433979327.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=10, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=10
[LightGBM] [Warning] min_data_in_leaf is set=68, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=68
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=68, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=68
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000140 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:46,774] Trial 11 finished with value: 0.0037080394773711715 and parameters: {'num_leaves': 274, 'subsample': 0.515126584157518, 'colsample_bytree': 0.4447500256608148, 'min_data_in_leaf': 68}. Best is trial 7 with value: 0.0034141882433979327.
[I 2025-03-14 03:13:46,844] Trial 12 finished with value: 0.003453956076191257 and parameters: {'num_leaves': 22, 'subsample': 0.3921691407476881, 'colsample_bytree': 0.7772430122980936, 'min_data_in_leaf': 36}. Best is trial 7 with value: 0.0034141882433979327.
[I 2025-03-14 03:13:46,912] Trial 13 finished with value: 0.0034173470347112233 and parameters: {'num_leaves': 19, 'subsample': 0.6472302703901885, 'colsample_bytree': 0.9988147175104403, 'min_data_in_leaf': 36}. Best is trial 7 with value: 0.0034141882433979327.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=68, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=68
[LightGBM] [Warning] min_data_in_leaf is set=36, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=36
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=36, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=36
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000155 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] min_data_in_leaf is set=36, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=36
[LightGBM] [Warning] min_data_in_leaf is set=36, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=36
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=36, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=36
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000145 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] min_data_in_leaf is set=36, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=36
[LightGBM] [Warning] min_data_in_leaf is set=21, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=21
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=21, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=21
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000223 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:47,185] Trial 14 finished with value: 0.003945910854245615 and parameters: {'num_leaves': 162, 'subsample': 0.7215816172416745, 'colsample_bytree': 0.9335416631511704, 'min_data_in_leaf': 21}. Best is trial 7 with value: 0.0034141882433979327.
[I 2025-03-14 03:13:47,319] Trial 15 finished with value: 0.0037582219593402665 and parameters: {'num_leaves': 440, 'subsample': 0.5898901579128046, 'colsample_bytree': 0.47291261259161343, 'min_data_in_leaf': 51}. Best is trial 7 with value: 0.0034141882433979327.
[I 2025-03-14 03:13:47,367] Trial 16 finished with value: 0.0033723004723925556 and parameters: {'num_leaves': 10, 'subsample': 0.7617972941586467, 'colsample_bytree': 0.8997770318422503, 'min_data_in_leaf': 36}. Best is trial 16 with value: 0.0033723004723925556.

[LightGBM] [Warning] min_data_in_leaf is set=21, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=21
[LightGBM] [Warning] min_data_in_leaf is set=51, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=51
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=51, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=51
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000353 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=51, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=51
[LightGBM] [Warning] min_data_in_leaf is set=36, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=36
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=36, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=36
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000283 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] min_data_in_leaf is set=36, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=36

[I 2025-03-14 03:13:47,552] Trial 17 finished with value: 0.003661163174507599 and parameters: {'num_leaves': 237, 'subsample': 0.7906376663505211, 'colsample_bytree': 0.886393368510428, 'min_data_in_leaf': 34}. Best is trial 16 with value: 0.0033723004723925556.

[LightGBM] [Warning] min_data_in_leaf is set=34, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=34
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=34, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=34
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000225 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=34, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=34
[LightGBM] [Warning] min_data_in_leaf is set=60, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=60
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=60, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=60
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000141 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:47,678] Trial 18 finished with value: 0.003741760487493551 and parameters: {'num_leaves': 364, 'subsample': 0.9233048833690654, 'colsample_bytree': 0.5346466665876909, 'min_data_in_leaf': 60}. Best is trial 16 with value: 0.0033723004723925556.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=60, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=60
[LightGBM] [Warning] min_data_in_leaf is set=13, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=13
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=13, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=13
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000240 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742

[I 2025-03-14 03:13:47,968] Trial 19 finished with value: 0.004550196792782138 and parameters: {'num_leaves': 165, 'subsample': 0.5147580300850674, 'colsample_bytree': 0.8618716149938122, 'min_data_in_leaf': 13}. Best is trial 16 with value: 0.0033723004723925556.
[I 2025-03-14 03:13:48,081] Trial 20 finished with value: 0.0034195695910025302 and parameters: {'num_leaves': 693, 'subsample': 0.2422278325624821, 'colsample_bytree': 0.7242259446928667, 'min_data_in_leaf': 80}. Best is trial 16 with value: 0.0033723004723925556.
[I 2025-03-14 03:13:48,133] Trial 21 finished with value: 0.0033351437437482254 and parameters: {'num_leaves': 10, 'subsample': 0.6705774866860973, 'colsample_bytree': 0.9907112668862691, 'min_data_in_leaf': 37}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] min_data_in_leaf is set=13, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=13
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000145 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Warning] min_data_in_leaf is set=37, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=37
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=37, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=37
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000228 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] min_data_in_leaf is set=37, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=37
[LightGBM] [Warning] min_data_in_leaf is set=31, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=31
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=31, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=31
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000337 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742

[I 2025-03-14 03:13:48,192] Trial 22 finished with value: 0.0034406744408896233 and parameters: {'num_leaves': 14, 'subsample': 0.7996114811781717, 'colsample_bytree': 0.8954763236681829, 'min_data_in_leaf': 31}. Best is trial 21 with value: 0.0033351437437482254.
[I 2025-03-14 03:13:48,362] Trial 23 finished with value: 0.0035982433976792373 and parameters: {'num_leaves': 158, 'subsample': 0.6981937220692596, 'colsample_bytree': 0.9993297146760698, 'min_data_in_leaf': 42}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] min_data_in_leaf is set=31, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=31
[LightGBM] [Warning] min_data_in_leaf is set=42, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=42
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=42, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=42
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000122 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=42, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=42
[LightGBM] [Warning] min_data_in_leaf is set=55, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=55
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=55, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=55
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000229 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:48,492] Trial 24 finished with value: 0.0035607048692827808 and parameters: {'num_leaves': 108, 'subsample': 0.9985740307664455, 'colsample_bytree': 0.8539396605950558, 'min_data_in_leaf': 55}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=55, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=55
[LightGBM] [Warning] min_data_in_leaf is set=19, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=19
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=19, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=19
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000137 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:48,824] Trial 25 finished with value: 0.004343554908338742 and parameters: {'num_leaves': 357, 'subsample': 0.5468249874855298, 'colsample_bytree': 0.7522562715624868, 'min_data_in_leaf': 19}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] min_data_in_leaf is set=19, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=19
[LightGBM] [Warning] min_data_in_leaf is set=31, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=31
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=31, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=31
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000126 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:49,024] Trial 26 finished with value: 0.00407419758098038 and parameters: {'num_leaves': 189, 'subsample': 0.7718511384008103, 'colsample_bytree': 0.3450011801400923, 'min_data_in_leaf': 31}. Best is trial 21 with value: 0.0033351437437482254.
[I 2025-03-14 03:13:49,185] Trial 27 finished with value: 0.003549220334936529 and parameters: {'num_leaves': 86, 'subsample': 0.6595030565252623, 'colsample_bytree': 0.6222282444651513, 'min_data_in_leaf': 41}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] min_data_in_leaf is set=31, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=31
[LightGBM] [Warning] min_data_in_leaf is set=41, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=41
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=41, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=41
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000375 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=41, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=41
[LightGBM] [Warning] min_data_in_leaf is set=53, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=53
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=53, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=53
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000156 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:49,330] Trial 28 finished with value: 0.003668013054234557 and parameters: {'num_leaves': 77, 'subsample': 0.4765384603416567, 'colsample_bytree': 0.930370454418276, 'min_data_in_leaf': 53}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=53, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=53
[LightGBM] [Warning] min_data_in_leaf is set=26, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=26
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=26, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=26
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000145 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742

[I 2025-03-14 03:13:49,470] Trial 29 finished with value: 0.0039106558971242125 and parameters: {'num_leaves': 70, 'subsample': 0.3285948147392327, 'colsample_bytree': 0.5065301745056339, 'min_data_in_leaf': 26}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] min_data_in_leaf is set=26, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=26
[LightGBM] [Warning] min_data_in_leaf is set=16, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=16
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=16, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=16
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000373 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:49,838] Trial 30 finished with value: 0.004452946670953602 and parameters: {'num_leaves': 359, 'subsample': 0.5809011730353686, 'colsample_bytree': 0.83288387588021, 'min_data_in_leaf': 16}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=16, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=16
[LightGBM] [Warning] min_data_in_leaf is set=40, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=40
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=40, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=40
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000207 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742

[I 2025-03-14 03:13:49,913] Trial 31 finished with value: 0.003411398800831376 and parameters: {'num_leaves': 16, 'subsample': 0.6582798708181958, 'colsample_bytree': 0.9750209112537963, 'min_data_in_leaf': 40}. Best is trial 21 with value: 0.0033351437437482254.
[I 2025-03-14 03:13:49,983] Trial 32 finished with value: 0.00340416862069676 and parameters: {'num_leaves': 20, 'subsample': 0.7510439993910848, 'colsample_bytree': 0.932212238325077, 'min_data_in_leaf': 41}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] min_data_in_leaf is set=40, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=40
[LightGBM] [Warning] min_data_in_leaf is set=41, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=41
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=41, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=41
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000384 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] min_data_in_leaf is set=41, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=41
[LightGBM] [Warning] min_data_in_leaf is set=42, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=42
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=42, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=42
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000348 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:50,158] Trial 33 finished with value: 0.0035982433976792373 and parameters: {'num_leaves': 201, 'subsample': 0.8422765663435983, 'colsample_bytree': 0.9333771190541602, 'min_data_in_leaf': 42}. Best is trial 21 with value: 0.0033351437437482254.
[I 2025-03-14 03:13:50,311] Trial 34 finished with value: 0.0035883266989181245 and parameters: {'num_leaves': 124, 'subsample': 0.7394732825630439, 'colsample_bytree': 0.9124352588313891, 'min_data_in_leaf': 48}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=42, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=42
[LightGBM] [Warning] min_data_in_leaf is set=48, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=48
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=48, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=48
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000314 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=48, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=48

[I 2025-03-14 03:13:50,476] Trial 35 finished with value: 0.0038148164928211064 and parameters: {'num_leaves': 77, 'subsample': 0.8702076015359896, 'colsample_bytree': 0.9705222174647633, 'min_data_in_leaf': 40}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] min_data_in_leaf is set=40, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=40
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=40, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=40
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000157 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] min_data_in_leaf is set=40, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=40
[LightGBM] [Warning] min_data_in_leaf is set=60, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=60
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=60, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=60
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000256 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:50,613] Trial 36 finished with value: 0.0035602954219044487 and parameters: {'num_leaves': 130, 'subsample': 0.6894760421380103, 'colsample_bytree': 0.8356316246086636, 'min_data_in_leaf': 60}. Best is trial 21 with value: 0.0033351437437482254.
[I 2025-03-14 03:13:50,725] Trial 37 finished with value: 0.0036933243978208323 and parameters: {'num_leaves': 49, 'subsample': 0.7502269708732426, 'colsample_bytree': 0.7051510477177048, 'min_data_in_leaf': 25}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=60, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=60
[LightGBM] [Warning] min_data_in_leaf is set=25, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=25
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=25, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=25
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000327 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] min_data_in_leaf is set=25, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=25

[I 2025-03-14 03:13:50,886] Trial 38 finished with value: 0.0036361761598797046 and parameters: {'num_leaves': 220, 'subsample': 0.6112927908909207, 'colsample_bytree': 0.7827770633108281, 'min_data_in_leaf': 47}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] min_data_in_leaf is set=47, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=47
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=47, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=47
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000325 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=47, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=47
[LightGBM] [Warning] min_data_in_leaf is set=29, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=29
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=29, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=29
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000262 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=29, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=29

[I 2025-03-14 03:13:51,160] Trial 39 finished with value: 0.0036731961990699143 and parameters: {'num_leaves': 812, 'subsample': 0.674269215705699, 'colsample_bytree': 0.9619010682115627, 'min_data_in_leaf': 29}. Best is trial 21 with value: 0.0033351437437482254.
[I 2025-03-14 03:13:51,339] Trial 40 finished with value: 0.003533665091048187 and parameters: {'num_leaves': 131, 'subsample': 0.8943363577527335, 'colsample_bytree': 0.8972184178062093, 'min_data_in_leaf': 38}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] min_data_in_leaf is set=38, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=38
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=38, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=38
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000291 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=38, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=38
[LightGBM] [Warning] min_data_in_leaf is set=45, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=45
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=45, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=45
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000205 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742

[I 2025-03-14 03:13:51,397] Trial 41 finished with value: 0.0034320207495983 and parameters: {'num_leaves': 12, 'subsample': 0.823998102492928, 'colsample_bytree': 0.592985076417972, 'min_data_in_leaf': 45}. Best is trial 21 with value: 0.0033351437437482254.
[I 2025-03-14 03:13:51,526] Trial 42 finished with value: 0.003761376111831089 and parameters: {'num_leaves': 62, 'subsample': 0.5519481317294859, 'colsample_bytree': 0.9983900629824501, 'min_data_in_leaf': 30}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] min_data_in_leaf is set=45, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=45
[LightGBM] [Warning] min_data_in_leaf is set=30, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=30
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=30, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=30
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000317 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] min_data_in_leaf is set=30, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=30
[LightGBM] [Warning] min_data_in_leaf is set=34, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=34
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=34, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=34
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000289 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:51,731] Trial 43 finished with value: 0.003661163174507599 and parameters: {'num_leaves': 989, 'subsample': 0.4029884451191671, 'colsample_bytree': 0.807288130719383, 'min_data_in_leaf': 34}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=34, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=34
[LightGBM] [Warning] min_data_in_leaf is set=23, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=23
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=23, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=23
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000331 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742

[I 2025-03-14 03:13:51,830] Trial 44 finished with value: 0.0037750183224940234 and parameters: {'num_leaves': 40, 'subsample': 0.6443436084735604, 'colsample_bytree': 0.6678241648351144, 'min_data_in_leaf': 23}. Best is trial 21 with value: 0.0033351437437482254.
[I 2025-03-14 03:13:51,966] Trial 45 finished with value: 0.004061842075032171 and parameters: {'num_leaves': 107, 'subsample': 0.7275070383332669, 'colsample_bytree': 0.38246903055454107, 'min_data_in_leaf': 44}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] min_data_in_leaf is set=23, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=23
[LightGBM] [Warning] min_data_in_leaf is set=44, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=44
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=44, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=44
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000207 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=44, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=44
[LightGBM] [Warning] min_data_in_leaf is set=49, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=49
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=49, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=49
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000142 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2025-03-14 03:13:52,107] Trial 46 finished with value: 0.0041541798634626 and parameters: {'num_leaves': 301, 'subsample': 0.46252490800927504, 'colsample_bytree': 0.2687892836440973, 'min_data_in_leaf': 49}. Best is trial 21 with value: 0.0033351437437482254.
[I 2025-03-14 03:13:52,215] Trial 47 finished with value: 0.00435075036481481 and parameters: {'num_leaves': 54, 'subsample': 0.5051483089361924, 'colsample_bytree': 0.12194908119531961, 'min_data_in_leaf': 57}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=49, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=49
[LightGBM] [Warning] min_data_in_leaf is set=57, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=57
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=57, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=57
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000149 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=57, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=57

[I 2025-03-14 03:13:52,410] Trial 48 finished with value: 0.0038055565142243136 and parameters: {'num_leaves': 634, 'subsample': 0.1048014988276329, 'colsample_bytree': 0.9591306652892188, 'min_data_in_leaf': 37}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] min_data_in_leaf is set=37, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=37
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=37, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=37
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000197 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=37, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=37
[LightGBM] [Warning] min_data_in_leaf is set=33, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=33
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=33, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=33
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000281 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742

[I 2025-03-14 03:13:52,473] Trial 49 finished with value: 0.003409521775775256 and parameters: {'num_leaves': 16, 'subsample': 0.607113548722454, 'colsample_bytree': 0.8536308746582677, 'min_data_in_leaf': 33}. Best is trial 21 with value: 0.0033351437437482254.

[LightGBM] [Warning] min_data_in_leaf is set=33, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=33
Mejores hiperparámetros: {'num_leaves': 10, 'subsample': 0.6705774866860973, 'colsample_bytree': 0.9907112668862691, 'min_data_in_leaf': 37}

### Random Forest

In [37]:
def objective(trial):
    # Definir los hiperparámetros a optimizar
    n_estimators = trial.suggest_int("n_estimators", 100, 500, step=50)
    max_depth = trial.suggest_int("max_depth", 10, 50, step=5)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
    min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 10)
    bootstrap = trial.suggest_categorical("bootstrap", [True, False])

    # Definir el modelo con los hiperparámetros actuales
    RF_model = RandomForestRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        bootstrap=bootstrap,
        criterion="squared_error",
        random_state=0
    )

    # Entrenar el modelo
    RF_model.fit(X_train_scaled_df, y_train_scaled_df)

    # Predicciones en el conjunto de validación
    y_pred = RF_model.predict(X_val_scaled_df)
    rmse = mean_squared_error(y_val_scaled_df, y_pred)

    return rmse  # Optuna minimizará este valor

# Crear el estudio de optimización
RF_study = optuna.create_study(direction="minimize")
RF_study.optimize(objective, n_trials=50)  # Ejecutar 50 pruebas

# Imprimir los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", RF_study.best_params)

[I 2025-03-14 03:13:52,480] A new study created in memory with name: no-name-b9d9d36f-b179-45d0-b144-31f5afc79200
[I 2025-03-14 03:13:58,552] Trial 0 finished with value: 0.006383512683529774 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.006383512683529774.
[I 2025-03-14 03:14:03,999] Trial 1 finished with value: 0.0037274273685884343 and parameters: {'n_estimators': 450, 'max_depth': 20, 'min_samples_split': 14, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 1 with value: 0.0037274273685884343.
[I 2025-03-14 03:14:07,345] Trial 2 finished with value: 0.0036711195702908133 and parameters: {'n_estimators': 300, 'max_depth': 25, 'min_samples_split': 9, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 2 with value: 0.0036711195702908133.
[I 2025-03-14 03:14:09,287] Trial 3 finished with value: 0.00631375868143921 and parameters: {'n_estimators': 100, 'max_depth': 25, 'min_samples_split': 9, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 2 with value: 0.0036711195702908133.
[I 2025-03-14 03:14:13,843] Trial 4 finished with value: 0.0036839106537876203 and parameters: {'n_estimators': 400, 'max_depth': 50, 'min_samples_split': 16, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 2 with value: 0.0036711195702908133.
[I 2025-03-14 03:14:17,064] Trial 5 finished with value: 0.003952552450388803 and parameters: {'n_estimators': 200, 'max_depth': 35, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 2 with value: 0.0036711195702908133.
[I 2025-03-14 03:14:22,147] Trial 6 finished with value: 0.005677507369631586 and parameters: {'n_estimators': 300, 'max_depth': 30, 'min_samples_split': 19, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 2 with value: 0.0036711195702908133.
[I 2025-03-14 03:14:26,246] Trial 7 finished with value: 0.0038343639378293796 and parameters: {'n_estimators': 300, 'max_depth': 50, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 2 with value: 0.0036711195702908133.
[I 2025-03-14 03:14:29,408] Trial 8 finished with value: 0.006416572701196876 and parameters: {'n_estimators': 150, 'max_depth': 45, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.0036711195702908133.
[I 2025-03-14 03:14:37,258] Trial 9 finished with value: 0.005321131222691361 and parameters: {'n_estimators': 450, 'max_depth': 40, 'min_samples_split': 18, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 2 with value: 0.0036711195702908133.
[I 2025-03-14 03:14:39,359] Trial 10 finished with value: 0.0036890697164046853 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 2 with value: 0.0036711195702908133.
[I 2025-03-14 03:14:44,055] Trial 11 finished with value: 0.003708713594367807 and parameters: {'n_estimators': 400, 'max_depth': 30, 'min_samples_split': 13, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 2 with value: 0.0036711195702908133.
[I 2025-03-14 03:14:48,066] Trial 12 finished with value: 0.003687010561519398 and parameters: {'n_estimators': 350, 'max_depth': 50, 'min_samples_split': 15, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 2 with value: 0.0036711195702908133.
[I 2025-03-14 03:14:53,669] Trial 13 finished with value: 0.003668829637600202 and parameters: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 11, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:14:56,478] Trial 14 finished with value: 0.003672054129912529 and parameters: {'n_estimators': 250, 'max_depth': 40, 'min_samples_split': 11, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:15:02,726] Trial 15 finished with value: 0.003742286151042875 and parameters: {'n_estimators': 500, 'max_depth': 25, 'min_samples_split': 11, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:15:06,655] Trial 16 finished with value: 0.0036691946510584617 and parameters: {'n_estimators': 350, 'max_depth': 35, 'min_samples_split': 5, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:15:12,504] Trial 17 finished with value: 0.0037067419549715133 and parameters: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 5, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:15:17,498] Trial 18 finished with value: 0.0037397774369825106 and parameters: {'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 4, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:15:22,768] Trial 19 finished with value: 0.0037121045608650345 and parameters: {'n_estimators': 450, 'max_depth': 35, 'min_samples_split': 5, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:15:28,023] Trial 20 finished with value: 0.004020073149971892 and parameters: {'n_estimators': 350, 'max_depth': 45, 'min_samples_split': 12, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:15:30,869] Trial 21 finished with value: 0.003672054129912529 and parameters: {'n_estimators': 250, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:15:34,816] Trial 22 finished with value: 0.0036691946510584617 and parameters: {'n_estimators': 350, 'max_depth': 30, 'min_samples_split': 6, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:15:38,882] Trial 23 finished with value: 0.003687010561519398 and parameters: {'n_estimators': 350, 'max_depth': 30, 'min_samples_split': 6, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:15:44,459] Trial 24 finished with value: 0.003668829637600202 and parameters: {'n_estimators': 500, 'max_depth': 35, 'min_samples_split': 2, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:15:50,483] Trial 25 finished with value: 0.0037231485421426514 and parameters: {'n_estimators': 500, 'max_depth': 45, 'min_samples_split': 2, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:15:55,753] Trial 26 finished with value: 0.0037121045608650345 and parameters: {'n_estimators': 450, 'max_depth': 35, 'min_samples_split': 4, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:16:04,254] Trial 27 finished with value: 0.005667390663940737 and parameters: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 2, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:16:08,723] Trial 28 finished with value: 0.0036688940859751114 and parameters: {'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 17, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:16:16,926] Trial 29 finished with value: 0.00586852369916571 and parameters: {'n_estimators': 450, 'max_depth': 20, 'min_samples_split': 17, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:16:21,466] Trial 30 finished with value: 0.0036791877650326162 and parameters: {'n_estimators': 400, 'max_depth': 45, 'min_samples_split': 20, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:16:27,048] Trial 31 finished with value: 0.003668829637600202 and parameters: {'n_estimators': 500, 'max_depth': 35, 'min_samples_split': 13, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:16:32,630] Trial 32 finished with value: 0.003668829637600202 and parameters: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 14, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:16:38,345] Trial 33 finished with value: 0.003685316366957528 and parameters: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 14, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:16:43,368] Trial 34 finished with value: 0.003673450855535842 and parameters: {'n_estimators': 450, 'max_depth': 40, 'min_samples_split': 15, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:16:49,212] Trial 35 finished with value: 0.0037067419549715133 and parameters: {'n_estimators': 500, 'max_depth': 45, 'min_samples_split': 13, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:16:54,354] Trial 36 finished with value: 0.003690393985495441 and parameters: {'n_estimators': 450, 'max_depth': 35, 'min_samples_split': 9, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:17:02,637] Trial 37 finished with value: 0.004702873239817669 and parameters: {'n_estimators': 500, 'max_depth': 20, 'min_samples_split': 13, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:17:07,787] Trial 38 finished with value: 0.003690393985495441 and parameters: {'n_estimators': 450, 'max_depth': 30, 'min_samples_split': 15, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:17:13,833] Trial 39 finished with value: 0.0037231485421426514 and parameters: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 12, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:17:15,604] Trial 40 finished with value: 0.005936015246928013 and parameters: {'n_estimators': 100, 'max_depth': 30, 'min_samples_split': 10, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:17:20,057] Trial 41 finished with value: 0.0036688940859751114 and parameters: {'n_estimators': 400, 'max_depth': 35, 'min_samples_split': 17, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:17:25,631] Trial 42 finished with value: 0.003668829637600202 and parameters: {'n_estimators': 500, 'max_depth': 35, 'min_samples_split': 16, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:17:31,218] Trial 43 finished with value: 0.003668829637600202 and parameters: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 16, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:17:36,363] Trial 44 finished with value: 0.003690393985495441 and parameters: {'n_estimators': 450, 'max_depth': 35, 'min_samples_split': 14, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:17:42,897] Trial 45 finished with value: 0.0038964182046306874 and parameters: {'n_estimators': 500, 'max_depth': 45, 'min_samples_split': 16, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:17:47,913] Trial 46 finished with value: 0.003673450855535842 and parameters: {'n_estimators': 450, 'max_depth': 30, 'min_samples_split': 18, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:17:53,619] Trial 47 finished with value: 0.003685316366957528 and parameters: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 12, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:17:58,643] Trial 48 finished with value: 0.003673450855535842 and parameters: {'n_estimators': 450, 'max_depth': 25, 'min_samples_split': 8, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 13 with value: 0.003668829637600202.
[I 2025-03-14 03:18:05,977] Trial 49 finished with value: 0.0055534572772277455 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 14, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 13 with value: 0.003668829637600202.

Mejores hiperparámetros: {'n_estimators': 500, 'max_depth': 40, 'min_samples_split': 11, 'min_samples_leaf': 10, 'bootstrap': True}

### CTNET

In [38]:
def compile_and_fit(model, xtrain=X_train_windowed, ytrain=y_train_windowed, learning_rate=0.0001):
    model.compile(loss=[tf.keras.losses.MeanSquaredError()],
                  optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                  metrics=[tf.keras.metrics.RootMeanSquaredError(), tf.keras.metrics.MeanAbsolutePercentageError(), tf.keras.metrics.MeanAbsoluteError()])

    history = model.fit(xtrain, ytrain, epochs=50,
                        batch_size=512, validation_split=0.2, verbose=1)
    return history

def Loss(train_loss, valid_loss):
    plt.plot(train_loss)
    plt.plot(valid_loss)
    plt.rcParams["figure.figsize"] = (15, 3)
    plt.title('Model Losses')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(['Train Loss', 'Validation Loss'], loc='upper left')
    plt.savefig('out/loss_plot.png')
    plt.show()

def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    x = layers.LayerNormalization()(inputs)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=128, kernel_size=2, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(norm_x, norm_x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    return norm_x

# Construir modelo con hiperparámetros sugeridos
def build_model(input_shape, head_size, num_heads, ff_dim, num_transformer_blocks, mlp_units, dropout, mlp_dropout):
    inputs = tf.keras.Input(shape=input_shape)
    x = inputs

    for _ in range(num_transformer_blocks):
        x = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)

    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(x, x)
    x = layers.LayerNormalization(epsilon=1e-6)(x)
    x = layers.GlobalAveragePooling1D(data_format="channels_first")(x)

    for units in mlp_units:
        x = layers.Dense(units, activation="relu")(x)

    x = layers.Dropout(mlp_dropout)(x)
    outputs = layers.Dense(1)(x)
    return tf.keras.Model(inputs, outputs)

In [39]:
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [40]:
# Definir la función objetivo para Optuna
def objective(trial):
    # Hiperparámetros a optimizar
    head_size = trial.suggest_int("head_size", 2, 8)
    num_heads = trial.suggest_int("num_heads", 2, 8)
    ff_dim = trial.suggest_int("ff_dim", 16, 128, step=16)
    num_transformer_blocks = trial.suggest_int("num_transformer_blocks", 1, 5)
    mlp_units = [trial.suggest_int("mlp_units_1", 64, 512, step=64),
                 trial.suggest_int("mlp_units_2", 32, 256, step=32)]
    dropout = trial.suggest_float("dropout", 0.1, 0.5)
    mlp_dropout = trial.suggest_float("mlp_dropout", 0.1, 0.5)
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-5, 1e-2)
    batch_size = trial.suggest_categorical("batch_size", [128, 256, 512])

    # Construir el modelo
    model = build_model(
        input_shape=(X_train_windowed.shape[1], X_train_windowed.shape[2]),
        head_size=head_size,
        num_heads=num_heads,
        ff_dim=ff_dim,
        num_transformer_blocks=num_transformer_blocks,
        mlp_units=mlp_units,
        dropout=dropout,
        mlp_dropout=mlp_dropout
    )

    # Compilar y entrenar el modelo
    model.compile(
        loss=tf.keras.losses.MeanSquaredError(),
        optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
        metrics=[tf.keras.metrics.RootMeanSquaredError()]
    )

    history = model.fit(
        X_train_windowed, y_train_windowed,
        epochs=100,  # Se puede detener antes con Early Stopping
        batch_size=batch_size,  # 🔹 Batch size optimizado
        validation_data=(X_val_windowed, y_val_windowed),  # 🔹 Validación en cada época
        callbacks=[early_stop],  # 🔹 Early Stopping activado
        verbose=0
    )

    # Obtener pérdida de validación
    val_loss = min(history.history['val_loss'])
    return val_loss  # Minimizar MSE

# Crear el estudio de optimización
CTNET_study = optuna.create_study(direction="minimize")
CTNET_study.optimize(objective, n_trials=50)  # Ejecutar 50 pruebas

# Imprimir los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", CTNET_study.best_params)

[I 2025-03-14 03:18:05,998] A new study created in memory with name: no-name-6fcad712-75a3-4d48-be1d-e92ed35272dd
[I 2025-03-14 03:19:02,888] Trial 0 finished with value: 0.04209723323583603 and parameters: {'head_size': 5, 'num_heads': 2, 'ff_dim': 32, 'num_transformer_blocks': 2, 'mlp_units_1': 320, 'mlp_units_2': 32, 'dropout': 0.2834417621934571, 'mlp_dropout': 0.3918526042440692, 'learning_rate': 0.0001145885594966619, 'batch_size': 128}. Best is trial 0 with value: 0.04209723323583603.
[I 2025-03-14 03:19:49,186] Trial 1 finished with value: 0.12246109545230865 and parameters: {'head_size': 2, 'num_heads': 7, 'ff_dim': 32, 'num_transformer_blocks': 1, 'mlp_units_1': 448, 'mlp_units_2': 128, 'dropout': 0.4823495503922436, 'mlp_dropout': 0.32802147766954015, 'learning_rate': 4.5625940218394675e-05, 'batch_size': 256}. Best is trial 0 with value: 0.04209723323583603.
[I 2025-03-14 03:21:14,669] Trial 2 finished with value: 0.017130950465798378 and parameters: {'head_size': 8, 'num_heads': 3, 'ff_dim': 112, 'num_transformer_blocks': 5, 'mlp_units_1': 384, 'mlp_units_2': 256, 'dropout': 0.43737239769528335, 'mlp_dropout': 0.43685006252187875, 'learning_rate': 0.0005438152720054761, 'batch_size': 128}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:22:48,842] Trial 3 finished with value: 0.12164565175771713 and parameters: {'head_size': 3, 'num_heads': 2, 'ff_dim': 64, 'num_transformer_blocks': 5, 'mlp_units_1': 192, 'mlp_units_2': 64, 'dropout': 0.47384954643579935, 'mlp_dropout': 0.10501656710671231, 'learning_rate': 1.5579352576636538e-05, 'batch_size': 512}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:23:58,762] Trial 4 finished with value: 0.12145866453647614 and parameters: {'head_size': 2, 'num_heads': 6, 'ff_dim': 96, 'num_transformer_blocks': 5, 'mlp_units_1': 384, 'mlp_units_2': 64, 'dropout': 0.1233035628199398, 'mlp_dropout': 0.348597493150285, 'learning_rate': 0.009571920932718848, 'batch_size': 128}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:24:45,739] Trial 5 finished with value: 0.022286292165517807 and parameters: {'head_size': 2, 'num_heads': 3, 'ff_dim': 112, 'num_transformer_blocks': 1, 'mlp_units_1': 256, 'mlp_units_2': 96, 'dropout': 0.41102751703832985, 'mlp_dropout': 0.32965275309625075, 'learning_rate': 3.0808674375734035e-05, 'batch_size': 128}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:25:33,151] Trial 6 finished with value: 0.02359318546950817 and parameters: {'head_size': 8, 'num_heads': 4, 'ff_dim': 32, 'num_transformer_blocks': 1, 'mlp_units_1': 448, 'mlp_units_2': 160, 'dropout': 0.42379234447470815, 'mlp_dropout': 0.14040973307647825, 'learning_rate': 0.0016759760348432024, 'batch_size': 128}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:26:21,315] Trial 7 finished with value: 0.02114064432680607 and parameters: {'head_size': 5, 'num_heads': 6, 'ff_dim': 96, 'num_transformer_blocks': 3, 'mlp_units_1': 448, 'mlp_units_2': 160, 'dropout': 0.2863895340927334, 'mlp_dropout': 0.14876316582190247, 'learning_rate': 0.002027489825194061, 'batch_size': 128}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:27:31,387] Trial 8 finished with value: 0.018564315512776375 and parameters: {'head_size': 6, 'num_heads': 3, 'ff_dim': 96, 'num_transformer_blocks': 3, 'mlp_units_1': 384, 'mlp_units_2': 96, 'dropout': 0.44793222557737844, 'mlp_dropout': 0.11443261239519353, 'learning_rate': 0.0003996481071566472, 'batch_size': 512}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:28:26,314] Trial 9 finished with value: 0.021004844456911087 and parameters: {'head_size': 6, 'num_heads': 6, 'ff_dim': 64, 'num_transformer_blocks': 3, 'mlp_units_1': 384, 'mlp_units_2': 32, 'dropout': 0.3107752151215629, 'mlp_dropout': 0.32419871637179665, 'learning_rate': 0.004397554986195875, 'batch_size': 128}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:29:38,353] Trial 10 finished with value: 0.027677446603775024 and parameters: {'head_size': 8, 'num_heads': 8, 'ff_dim': 128, 'num_transformer_blocks': 4, 'mlp_units_1': 64, 'mlp_units_2': 256, 'dropout': 0.36937604598491497, 'mlp_dropout': 0.48053078362684126, 'learning_rate': 0.0004034855917528782, 'batch_size': 256}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:30:59,026] Trial 11 finished with value: 0.01963927038013935 and parameters: {'head_size': 7, 'num_heads': 4, 'ff_dim': 96, 'num_transformer_blocks': 4, 'mlp_units_1': 512, 'mlp_units_2': 256, 'dropout': 0.3698523672800396, 'mlp_dropout': 0.2144985449457083, 'learning_rate': 0.00048218771007292686, 'batch_size': 512}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:32:26,920] Trial 12 finished with value: 0.020172247663140297 and parameters: {'head_size': 6, 'num_heads': 4, 'ff_dim': 128, 'num_transformer_blocks': 4, 'mlp_units_1': 256, 'mlp_units_2': 224, 'dropout': 0.49018583677227784, 'mlp_dropout': 0.49459160750795333, 'learning_rate': 0.00017038929986018137, 'batch_size': 512}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:33:30,941] Trial 13 finished with value: 0.019860150292515755 and parameters: {'head_size': 7, 'num_heads': 3, 'ff_dim': 80, 'num_transformer_blocks': 2, 'mlp_units_1': 320, 'mlp_units_2': 192, 'dropout': 0.2129196517004994, 'mlp_dropout': 0.23386949904205928, 'learning_rate': 0.001000933621656312, 'batch_size': 512}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:34:41,453] Trial 14 finished with value: 0.020339354872703552 and parameters: {'head_size': 4, 'num_heads': 3, 'ff_dim': 112, 'num_transformer_blocks': 3, 'mlp_units_1': 128, 'mlp_units_2': 128, 'dropout': 0.41296704100214177, 'mlp_dropout': 0.42922644488153994, 'learning_rate': 0.0001435816921961053, 'batch_size': 512}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:35:45,297] Trial 15 finished with value: 0.021866748109459877 and parameters: {'head_size': 7, 'num_heads': 5, 'ff_dim': 80, 'num_transformer_blocks': 2, 'mlp_units_1': 384, 'mlp_units_2': 192, 'dropout': 0.3459115056186784, 'mlp_dropout': 0.2605000259514375, 'learning_rate': 0.0006818733902293424, 'batch_size': 256}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:37:01,230] Trial 16 finished with value: 0.025603987276554108 and parameters: {'head_size': 6, 'num_heads': 2, 'ff_dim': 112, 'num_transformer_blocks': 5, 'mlp_units_1': 512, 'mlp_units_2': 96, 'dropout': 0.4390445291805488, 'mlp_dropout': 0.4198344546286078, 'learning_rate': 0.00025957597570962367, 'batch_size': 512}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:38:15,030] Trial 17 finished with value: 0.08164790272712708 and parameters: {'head_size': 8, 'num_heads': 5, 'ff_dim': 48, 'num_transformer_blocks': 4, 'mlp_units_1': 320, 'mlp_units_2': 224, 'dropout': 0.24042362853744045, 'mlp_dropout': 0.26829940215544723, 'learning_rate': 5.4279610274582415e-05, 'batch_size': 128}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:39:18,046] Trial 18 finished with value: 0.01726742833852768 and parameters: {'head_size': 4, 'num_heads': 3, 'ff_dim': 128, 'num_transformer_blocks': 4, 'mlp_units_1': 192, 'mlp_units_2': 192, 'dropout': 0.11351134900632817, 'mlp_dropout': 0.20382504155151648, 'learning_rate': 0.0015214075363138423, 'batch_size': 512}. Best is trial 2 with value: 0.017130950465798378.
[I 2025-03-14 03:40:36,282] Trial 19 finished with value: 0.01576073467731476 and parameters: {'head_size': 4, 'num_heads': 4, 'ff_dim': 128, 'num_transformer_blocks': 5, 'mlp_units_1': 192, 'mlp_units_2': 224, 'dropout': 0.10447944152617603, 'mlp_dropout': 0.19228076386626258, 'learning_rate': 0.002756100769940104, 'batch_size': 256}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 03:41:43,794] Trial 20 finished with value: 0.12146063894033432 and parameters: {'head_size': 4, 'num_heads': 4, 'ff_dim': 112, 'num_transformer_blocks': 5, 'mlp_units_1': 64, 'mlp_units_2': 224, 'dropout': 0.16541761195543359, 'mlp_dropout': 0.1691790873914745, 'learning_rate': 0.003560044898845369, 'batch_size': 256}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 03:42:54,660] Trial 21 finished with value: 0.01999569498002529 and parameters: {'head_size': 4, 'num_heads': 3, 'ff_dim': 128, 'num_transformer_blocks': 5, 'mlp_units_1': 192, 'mlp_units_2': 192, 'dropout': 0.10222484191982173, 'mlp_dropout': 0.19369730001201088, 'learning_rate': 0.001127619013403477, 'batch_size': 256}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 03:43:59,789] Trial 22 finished with value: 0.01743939518928528 and parameters: {'head_size': 3, 'num_heads': 4, 'ff_dim': 128, 'num_transformer_blocks': 4, 'mlp_units_1': 192, 'mlp_units_2': 256, 'dropout': 0.15350442410658918, 'mlp_dropout': 0.2817957426908742, 'learning_rate': 0.003623749902379638, 'batch_size': 256}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 03:45:15,624] Trial 23 finished with value: 0.05137556418776512 and parameters: {'head_size': 3, 'num_heads': 2, 'ff_dim': 128, 'num_transformer_blocks': 5, 'mlp_units_1': 128, 'mlp_units_2': 224, 'dropout': 0.19302828114032447, 'mlp_dropout': 0.23483074632803305, 'learning_rate': 0.009151927943023656, 'batch_size': 256}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 03:46:18,938] Trial 24 finished with value: 0.017258670181035995 and parameters: {'head_size': 4, 'num_heads': 5, 'ff_dim': 112, 'num_transformer_blocks': 4, 'mlp_units_1': 128, 'mlp_units_2': 192, 'dropout': 0.1321962432329667, 'mlp_dropout': 0.18170900828663583, 'learning_rate': 0.0018857057699386537, 'batch_size': 256}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 03:47:36,230] Trial 25 finished with value: 0.018714051693677902 and parameters: {'head_size': 5, 'num_heads': 5, 'ff_dim': 112, 'num_transformer_blocks': 5, 'mlp_units_1': 128, 'mlp_units_2': 256, 'dropout': 0.23805289435196678, 'mlp_dropout': 0.3789144775072152, 'learning_rate': 0.002935972765252174, 'batch_size': 256}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 03:48:49,117] Trial 26 finished with value: 0.01913801208138466 and parameters: {'head_size': 5, 'num_heads': 5, 'ff_dim': 80, 'num_transformer_blocks': 4, 'mlp_units_1': 256, 'mlp_units_2': 224, 'dropout': 0.1510946259207686, 'mlp_dropout': 0.16557206102562783, 'learning_rate': 0.0006588675216641874, 'batch_size': 256}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 03:49:54,865] Trial 27 finished with value: 0.12146203219890594 and parameters: {'head_size': 3, 'num_heads': 5, 'ff_dim': 16, 'num_transformer_blocks': 5, 'mlp_units_1': 128, 'mlp_units_2': 160, 'dropout': 0.18995101998051536, 'mlp_dropout': 0.29394915203487443, 'learning_rate': 0.006084054022064201, 'batch_size': 256}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 03:51:00,824] Trial 28 finished with value: 0.018258532509207726 and parameters: {'head_size': 4, 'num_heads': 4, 'ff_dim': 112, 'num_transformer_blocks': 4, 'mlp_units_1': 64, 'mlp_units_2': 192, 'dropout': 0.32315781813585653, 'mlp_dropout': 0.24192685024940852, 'learning_rate': 0.000883745923395661, 'batch_size': 256}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 03:52:22,955] Trial 29 finished with value: 0.016004368662834167 and parameters: {'head_size': 5, 'num_heads': 7, 'ff_dim': 96, 'num_transformer_blocks': 5, 'mlp_units_1': 256, 'mlp_units_2': 256, 'dropout': 0.24099658099000798, 'mlp_dropout': 0.4457913984415759, 'learning_rate': 0.0021734496164316774, 'batch_size': 128}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 03:53:49,735] Trial 30 finished with value: 0.02208748646080494 and parameters: {'head_size': 5, 'num_heads': 8, 'ff_dim': 96, 'num_transformer_blocks': 5, 'mlp_units_1': 320, 'mlp_units_2': 256, 'dropout': 0.2524264696481266, 'mlp_dropout': 0.45333551314354475, 'learning_rate': 0.0002410990557343424, 'batch_size': 128}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 03:54:51,817] Trial 31 finished with value: 0.12159212678670883 and parameters: {'head_size': 5, 'num_heads': 7, 'ff_dim': 112, 'num_transformer_blocks': 5, 'mlp_units_1': 256, 'mlp_units_2': 224, 'dropout': 0.13336971173719359, 'mlp_dropout': 0.3921642701588593, 'learning_rate': 0.002475082372515985, 'batch_size': 128}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 03:56:08,133] Trial 32 finished with value: 0.1215071901679039 and parameters: {'head_size': 4, 'num_heads': 7, 'ff_dim': 96, 'num_transformer_blocks': 5, 'mlp_units_1': 192, 'mlp_units_2': 256, 'dropout': 0.27220243174458497, 'mlp_dropout': 0.37422002481664757, 'learning_rate': 0.006178108126942448, 'batch_size': 128}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 03:57:17,574] Trial 33 finished with value: 0.01888490840792656 and parameters: {'head_size': 3, 'num_heads': 6, 'ff_dim': 112, 'num_transformer_blocks': 4, 'mlp_units_1': 128, 'mlp_units_2': 224, 'dropout': 0.1771058778913197, 'mlp_dropout': 0.46300478523762834, 'learning_rate': 0.0014065388441275484, 'batch_size': 128}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 03:58:24,411] Trial 34 finished with value: 0.02527930587530136 and parameters: {'head_size': 5, 'num_heads': 7, 'ff_dim': 128, 'num_transformer_blocks': 5, 'mlp_units_1': 320, 'mlp_units_2': 256, 'dropout': 0.13634408674840498, 'mlp_dropout': 0.41959712651190917, 'learning_rate': 0.00218186220777929, 'batch_size': 128}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 03:59:40,970] Trial 35 finished with value: 0.03618358075618744 and parameters: {'head_size': 4, 'num_heads': 5, 'ff_dim': 80, 'num_transformer_blocks': 5, 'mlp_units_1': 192, 'mlp_units_2': 224, 'dropout': 0.20977643767919435, 'mlp_dropout': 0.4524793994030509, 'learning_rate': 7.520560774985443e-05, 'batch_size': 256}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 04:00:33,628] Trial 36 finished with value: 0.12150213122367859 and parameters: {'head_size': 2, 'num_heads': 6, 'ff_dim': 96, 'num_transformer_blocks': 4, 'mlp_units_1': 256, 'mlp_units_2': 192, 'dropout': 0.10285579836244153, 'mlp_dropout': 0.11958972677226348, 'learning_rate': 0.005239152938403145, 'batch_size': 128}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 04:01:38,809] Trial 37 finished with value: 0.016363224014639854 and parameters: {'head_size': 6, 'num_heads': 2, 'ff_dim': 112, 'num_transformer_blocks': 5, 'mlp_units_1': 192, 'mlp_units_2': 256, 'dropout': 0.377021779136414, 'mlp_dropout': 0.34846924340849433, 'learning_rate': 0.0006097817053038715, 'batch_size': 128}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 04:02:55,189] Trial 38 finished with value: 0.016996603459119797 and parameters: {'head_size': 7, 'num_heads': 2, 'ff_dim': 64, 'num_transformer_blocks': 5, 'mlp_units_1': 448, 'mlp_units_2': 256, 'dropout': 0.3840523929336549, 'mlp_dropout': 0.345466225265462, 'learning_rate': 0.0005749343014664288, 'batch_size': 128}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 04:04:01,044] Trial 39 finished with value: 0.018672797828912735 and parameters: {'head_size': 7, 'num_heads': 2, 'ff_dim': 64, 'num_transformer_blocks': 5, 'mlp_units_1': 256, 'mlp_units_2': 256, 'dropout': 0.38971118141747035, 'mlp_dropout': 0.35225602856839033, 'learning_rate': 0.0007341437265073725, 'batch_size': 128}. Best is trial 19 with value: 0.01576073467731476.
[I 2025-03-14 04:05:18,099] Trial 40 finished with value: 0.01450075302273035 and parameters: {'head_size': 6, 'num_heads': 2, 'ff_dim': 48, 'num_transformer_blocks': 5, 'mlp_units_1': 448, 'mlp_units_2': 256, 'dropout': 0.3360822470360483, 'mlp_dropout': 0.32432206414310666, 'learning_rate': 0.001237208136295941, 'batch_size': 128}. Best is trial 40 with value: 0.01450075302273035.
[I 2025-03-14 04:06:17,649] Trial 41 finished with value: 0.0188454557210207 and parameters: {'head_size': 6, 'num_heads': 2, 'ff_dim': 48, 'num_transformer_blocks': 5, 'mlp_units_1': 448, 'mlp_units_2': 256, 'dropout': 0.33551913492166047, 'mlp_dropout': 0.3209085910471589, 'learning_rate': 0.0013127070568581696, 'batch_size': 128}. Best is trial 40 with value: 0.01450075302273035.
[I 2025-03-14 04:07:29,951] Trial 42 finished with value: 0.019057121127843857 and parameters: {'head_size': 6, 'num_heads': 2, 'ff_dim': 48, 'num_transformer_blocks': 5, 'mlp_units_1': 448, 'mlp_units_2': 256, 'dropout': 0.3906392439938993, 'mlp_dropout': 0.3114938865046101, 'learning_rate': 0.0003356071693879946, 'batch_size': 128}. Best is trial 40 with value: 0.01450075302273035.
[I 2025-03-14 04:08:45,097] Trial 43 finished with value: 0.12142142653465271 and parameters: {'head_size': 7, 'num_heads': 2, 'ff_dim': 48, 'num_transformer_blocks': 5, 'mlp_units_1': 512, 'mlp_units_2': 256, 'dropout': 0.460268414636374, 'mlp_dropout': 0.3451139862953089, 'learning_rate': 1.1081566258353168e-05, 'batch_size': 128}. Best is trial 40 with value: 0.01450075302273035.
[I 2025-03-14 04:10:06,413] Trial 44 finished with value: 0.019366635009646416 and parameters: {'head_size': 6, 'num_heads': 2, 'ff_dim': 64, 'num_transformer_blocks': 5, 'mlp_units_1': 448, 'mlp_units_2': 224, 'dropout': 0.35595547235577935, 'mlp_dropout': 0.3939001783552457, 'learning_rate': 0.0005436992677740009, 'batch_size': 128}. Best is trial 40 with value: 0.01450075302273035.
[I 2025-03-14 04:10:40,740] Trial 45 finished with value: 0.019949065521359444 and parameters: {'head_size': 7, 'num_heads': 3, 'ff_dim': 32, 'num_transformer_blocks': 1, 'mlp_units_1': 384, 'mlp_units_2': 256, 'dropout': 0.31082423352033606, 'mlp_dropout': 0.3446352579725334, 'learning_rate': 0.000961017670993127, 'batch_size': 128}. Best is trial 40 with value: 0.01450075302273035.
[I 2025-03-14 04:11:53,425] Trial 46 finished with value: 0.02110230177640915 and parameters: {'head_size': 6, 'num_heads': 3, 'ff_dim': 32, 'num_transformer_blocks': 5, 'mlp_units_1': 192, 'mlp_units_2': 224, 'dropout': 0.3870884152981166, 'mlp_dropout': 0.36700818203936114, 'learning_rate': 0.002702211792066943, 'batch_size': 128}. Best is trial 40 with value: 0.01450075302273035.
[I 2025-03-14 04:12:41,816] Trial 47 finished with value: 0.021256452426314354 and parameters: {'head_size': 6, 'num_heads': 2, 'ff_dim': 64, 'num_transformer_blocks': 3, 'mlp_units_1': 448, 'mlp_units_2': 256, 'dropout': 0.3616079215477807, 'mlp_dropout': 0.30140939669677624, 'learning_rate': 0.0004243375521268071, 'batch_size': 128}. Best is trial 40 with value: 0.01450075302273035.
[I 2025-03-14 04:13:43,539] Trial 48 finished with value: 0.020012659952044487 and parameters: {'head_size': 7, 'num_heads': 2, 'ff_dim': 64, 'num_transformer_blocks': 5, 'mlp_units_1': 256, 'mlp_units_2': 224, 'dropout': 0.2728599868235306, 'mlp_dropout': 0.33076905126399425, 'learning_rate': 0.001758653704631906, 'batch_size': 128}. Best is trial 40 with value: 0.01450075302273035.
[I 2025-03-14 04:14:55,116] Trial 49 finished with value: 0.023765528574585915 and parameters: {'head_size': 6, 'num_heads': 3, 'ff_dim': 80, 'num_transformer_blocks': 4, 'mlp_units_1': 512, 'mlp_units_2': 32, 'dropout': 0.33524796207861157, 'mlp_dropout': 0.4061441046617811, 'learning_rate': 0.0002644399111734509, 'batch_size': 128}. Best is trial 40 with value: 0.01450075302273035.

Mejores hiperparámetros: {'head_size': 6, 'num_heads': 2, 'ff_dim': 48, 'num_transformer_blocks': 5, 'mlp_units_1': 448, 'mlp_units_2': 256, 'dropout': 0.3360822470360483, 'mlp_dropout': 0.32432206414310666, 'learning_rate': 0.001237208136295941, 'batch_size': 128}

### Forescasting

In [41]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer, Conv1D, BatchNormalization, MaxPooling1D, Bidirectional, LSTM, Dropout, Dense
from tensorflow.keras.optimizers import Adam

# Definir la función objetivo para Optuna
def objective(trial):
    # Hiperparámetros a optimizar
    filters = trial.suggest_categorical("filters", [32, 64, 128])
    kernel_size = trial.suggest_int("kernel_size", 2, 5)
    lstm_units_1 = trial.suggest_categorical("lstm_units_1", [64, 128, 256])
    lstm_units_2 = trial.suggest_categorical("lstm_units_2", [32, 64, 128])
    lstm_units_3 = trial.suggest_categorical("lstm_units_3", [16, 32, 64])
    dropout_lstm = trial.suggest_float("dropout_lstm", 0.1, 0.5)
    dropout_dense = trial.suggest_float("dropout_dense", 0.1, 0.5)
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-4, 1e-2)
    batch_size = trial.suggest_categorical("batch_size", [128, 256, 512])  # 🔹 Optimización del batch size

    # Construcción del modelo
    model = Sequential()
    model.add(InputLayer((X_train_windowed.shape[1], X_train_windowed.shape[2])))

    # CNN
    model.add(Conv1D(filters=filters, kernel_size=kernel_size, padding='same', activation='relu'))
    model.add(BatchNormalization())
    model.add(MaxPooling1D(pool_size=2))

    # BiLSTM
    model.add(Bidirectional(LSTM(lstm_units_1, return_sequences=True)))
    model.add(Bidirectional(LSTM(lstm_units_2, return_sequences=True)))
    model.add(Dropout(dropout_lstm))
    model.add(Bidirectional(LSTM(lstm_units_3, return_sequences=False)))

    # Normalización y Dropout
    model.add(BatchNormalization())
    model.add(Dropout(dropout_dense))

    # Capas Densas
    model.add(Dense(16, activation='relu'))
    model.add(Dense(1, activation='relu'))

    # Compilar el modelo
    model.compile(
        loss=tf.keras.losses.MeanSquaredError(),
        optimizer=Adam(learning_rate=learning_rate),
        metrics=[tf.keras.metrics.RootMeanSquaredError()]
    )

    # Entrenar el modelo con validación
    history = model.fit(
        X_train_windowed, y_train_windowed,
        epochs=100,  # Se puede detener antes con Early Stopping
        batch_size=batch_size,  # 🔹 Batch size optimizado
        validation_data=(X_val_windowed, y_val_windowed),  # 🔹 Validación en cada época
        callbacks=[early_stop],  # 🔹 Early Stopping activado
        verbose=0
    )

    # Obtener la mejor pérdida de validación
    val_loss = min(history.history['val_loss'])
    return val_loss  # Optuna minimizará este valor

# Crear el estudio de optimización
Forecasting_study = optuna.create_study(direction="minimize")
Forecasting_study.optimize(objective, n_trials=50, n_jobs=-1)  # Ejecutar 50 pruebas

# Imprimir los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", Forecasting_study.best_params)

[I 2025-03-14 04:14:55,131] A new study created in memory with name: no-name-5634438c-9fbb-4581-8aaa-62deae5204df
WARNING:tensorflow:5 out of the last 1904 calls to <function TensorFlowTrainer._make_function.<locals>.multi_step_on_iterator at 0x7bbe29da1620> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 1905 calls to <function TensorFlowTrainer._make_function.<locals>.multi_step_on_iterator at 0x7bbe0cfb2ca0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[I 2025-03-14 04:16:24,746] Trial 11 finished with value: 0.156172975897789 and parameters: {'filters': 128, 'kernel_size': 5, 'lstm_units_1': 256, 'lstm_units_2': 64, 'lstm_units_3': 32, 'dropout_lstm': 0.4586887589315084, 'dropout_dense': 0.3722642180326162, 'learning_rate': 0.0007914457778434024, 'batch_size': 256}. Best is trial 11 with value: 0.156172975897789.
[I 2025-03-14 04:16:36,071] Trial 12 finished with value: 0.20963075757026672 and parameters: {'filters': 64, 'kernel_size': 2, 'lstm_units_1': 256, 'lstm_units_2': 128, 'lstm_units_3': 32, 'dropout_lstm': 0.3264048264900261, 'dropout_dense': 0.123827987649261, 'learning_rate': 0.001874078805325109, 'batch_size': 256}. Best is trial 11 with value: 0.156172975897789.
[I 2025-03-14 04:16:47,475] Trial 13 finished with value: 0.3738705813884735 and parameters: {'filters': 64, 'kernel_size': 5, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 32, 'dropout_lstm': 0.2184679314060075, 'dropout_dense': 0.45822723165377455, 'learning_rate': 0.0003949541541902464, 'batch_size': 128}. Best is trial 11 with value: 0.156172975897789.
[I 2025-03-14 04:16:58,795] Trial 14 finished with value: 0.5368598699569702 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 256, 'lstm_units_2': 64, 'lstm_units_3': 32, 'dropout_lstm': 0.24635718377909668, 'dropout_dense': 0.44123471962155336, 'learning_rate': 0.007932765824049087, 'batch_size': 256}. Best is trial 11 with value: 0.156172975897789.
[I 2025-03-14 04:17:11,494] Trial 15 finished with value: 0.4482162594795227 and parameters: {'filters': 32, 'kernel_size': 3, 'lstm_units_1': 256, 'lstm_units_2': 64, 'lstm_units_3': 32, 'dropout_lstm': 0.10820667199772416, 'dropout_dense': 0.43723869861276243, 'learning_rate': 0.00015125205992973353, 'batch_size': 128}. Best is trial 11 with value: 0.156172975897789.
[I 2025-03-14 04:17:22,717] Trial 16 finished with value: 0.31559863686561584 and parameters: {'filters': 64, 'kernel_size': 2, 'lstm_units_1': 256, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.29683239435897246, 'dropout_dense': 0.18030323128054923, 'learning_rate': 0.0030251409952165337, 'batch_size': 512}. Best is trial 11 with value: 0.156172975897789.
[I 2025-03-14 04:17:33,074] Trial 17 finished with value: 0.5368598699569702 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 128, 'lstm_units_2': 128, 'lstm_units_3': 32, 'dropout_lstm': 0.16579331644313833, 'dropout_dense': 0.4880882536092589, 'learning_rate': 0.0002470253897995667, 'batch_size': 256}. Best is trial 11 with value: 0.156172975897789.
[I 2025-03-14 04:17:44,546] Trial 18 finished with value: 0.48799756169319153 and parameters: {'filters': 32, 'kernel_size': 5, 'lstm_units_1': 256, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.135195890427811, 'dropout_dense': 0.29132141003082634, 'learning_rate': 0.00018145936175949112, 'batch_size': 256}. Best is trial 11 with value: 0.156172975897789.
[I 2025-03-14 04:17:55,972] Trial 19 finished with value: 0.5368598699569702 and parameters: {'filters': 64, 'kernel_size': 2, 'lstm_units_1': 64, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.32981131364202454, 'dropout_dense': 0.35226666555613917, 'learning_rate': 0.0002265218994715393, 'batch_size': 128}. Best is trial 11 with value: 0.156172975897789.
[I 2025-03-14 04:18:06,937] Trial 20 finished with value: 0.3865015208721161 and parameters: {'filters': 128, 'kernel_size': 4, 'lstm_units_1': 256, 'lstm_units_2': 128, 'lstm_units_3': 32, 'dropout_lstm': 0.27857023444791046, 'dropout_dense': 0.15437443395242087, 'learning_rate': 0.0006613564567452126, 'batch_size': 512}. Best is trial 11 with value: 0.156172975897789.
[I 2025-03-14 04:18:17,336] Trial 21 finished with value: 0.4166871905326843 and parameters: {'filters': 128, 'kernel_size': 5, 'lstm_units_1': 128, 'lstm_units_2': 64, 'lstm_units_3': 64, 'dropout_lstm': 0.48799153121909333, 'dropout_dense': 0.309313020412846, 'learning_rate': 0.001067248354345269, 'batch_size': 256}. Best is trial 11 with value: 0.156172975897789.
[I 2025-03-14 04:18:27,911] Trial 22 finished with value: 0.16922788321971893 and parameters: {'filters': 128, 'kernel_size': 3, 'lstm_units_1': 256, 'lstm_units_2': 128, 'lstm_units_3': 16, 'dropout_lstm': 0.42644778919278326, 'dropout_dense': 0.23444851838698028, 'learning_rate': 0.0017216459674834457, 'batch_size': 256}. Best is trial 11 with value: 0.156172975897789.
[I 2025-03-14 04:18:38,610] Trial 23 finished with value: 0.5352180600166321 and parameters: {'filters': 128, 'kernel_size': 3, 'lstm_units_1': 256, 'lstm_units_2': 128, 'lstm_units_3': 16, 'dropout_lstm': 0.4607399838647454, 'dropout_dense': 0.22940483465388511, 'learning_rate': 0.0024285393067718926, 'batch_size': 256}. Best is trial 11 with value: 0.156172975897789.
[I 2025-03-14 04:18:53,869] Trial 4 finished with value: 0.016976721584796906 and parameters: {'filters': 32, 'kernel_size': 3, 'lstm_units_1': 64, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.43026150816089503, 'dropout_dense': 0.1963114984291774, 'learning_rate': 0.0012259070096615106, 'batch_size': 512}. Best is trial 4 with value: 0.016976721584796906.
[I 2025-03-14 04:18:56,336] Trial 9 finished with value: 0.021850327029824257 and parameters: {'filters': 64, 'kernel_size': 4, 'lstm_units_1': 256, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.2654375619082505, 'dropout_dense': 0.48983405144164405, 'learning_rate': 0.0015199567118711072, 'batch_size': 512}. Best is trial 4 with value: 0.016976721584796906.
[I 2025-03-14 04:18:57,896] Trial 24 finished with value: 0.49404993653297424 and parameters: {'filters': 128, 'kernel_size': 3, 'lstm_units_1': 128, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.4139654018565265, 'dropout_dense': 0.3623927535923021, 'learning_rate': 0.001003438740375676, 'batch_size': 256}. Best is trial 4 with value: 0.016976721584796906.
[I 2025-03-14 04:18:58,361] Trial 3 finished with value: 0.01740117371082306 and parameters: {'filters': 32, 'kernel_size': 5, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.3300672289340355, 'dropout_dense': 0.26927768670971397, 'learning_rate': 0.0016881462181818432, 'batch_size': 512}. Best is trial 4 with value: 0.016976721584796906.
[I 2025-03-14 04:18:58,678] Trial 0 finished with value: 0.014132257550954819 and parameters: {'filters': 64, 'kernel_size': 3, 'lstm_units_1': 128, 'lstm_units_2': 64, 'lstm_units_3': 32, 'dropout_lstm': 0.311943963114354, 'dropout_dense': 0.389238411944303, 'learning_rate': 0.0053811821951197086, 'batch_size': 512}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:19:35,739] Trial 29 finished with value: 0.1414206475019455 and parameters: {'filters': 32, 'kernel_size': 3, 'lstm_units_1': 64, 'lstm_units_2': 32, 'lstm_units_3': 64, 'dropout_lstm': 0.37747640732724397, 'dropout_dense': 0.10429949027355022, 'learning_rate': 0.005708459768816326, 'batch_size': 512}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:19:47,523] Trial 30 finished with value: 0.41965946555137634 and parameters: {'filters': 64, 'kernel_size': 2, 'lstm_units_1': 64, 'lstm_units_2': 32, 'lstm_units_3': 64, 'dropout_lstm': 0.3864696430625291, 'dropout_dense': 0.40274394548349735, 'learning_rate': 0.004252184622632722, 'batch_size': 512}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:19:57,803] Trial 31 finished with value: 0.12184619158506393 and parameters: {'filters': 32, 'kernel_size': 3, 'lstm_units_1': 64, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.1861486217890992, 'dropout_dense': 0.2142507049889515, 'learning_rate': 0.008644191714026833, 'batch_size': 512}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:20:08,175] Trial 32 finished with value: 0.12216441333293915 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.3501521390397297, 'dropout_dense': 0.29556808927120576, 'learning_rate': 0.003455801439931957, 'batch_size': 512}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:20:18,378] Trial 33 finished with value: 0.5368598699569702 and parameters: {'filters': 32, 'kernel_size': 3, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.36695395787785945, 'dropout_dense': 0.2577557291885456, 'learning_rate': 0.0004603795041124341, 'batch_size': 512}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:20:28,862] Trial 34 finished with value: 0.5365070700645447 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 64, 'dropout_lstm': 0.31037508834119437, 'dropout_dense': 0.18215780558247657, 'learning_rate': 0.0012327360932637141, 'batch_size': 512}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:20:39,031] Trial 35 finished with value: 0.1902017444372177 and parameters: {'filters': 32, 'kernel_size': 3, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.41606732838986477, 'dropout_dense': 0.32611354379109797, 'learning_rate': 0.005912318932966018, 'batch_size': 512}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:20:49,447] Trial 36 finished with value: 0.3461131453514099 and parameters: {'filters': 64, 'kernel_size': 2, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.22609190257068212, 'dropout_dense': 0.2631706543396063, 'learning_rate': 0.0025489924566699535, 'batch_size': 512}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:20:59,802] Trial 37 finished with value: 0.5361617803573608 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 32, 'dropout_lstm': 0.49900327701113234, 'dropout_dense': 0.19198777798772163, 'learning_rate': 0.00010639078295654796, 'batch_size': 512}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:21:07,209] Trial 7 finished with value: 0.02490747720003128 and parameters: {'filters': 32, 'kernel_size': 2, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 32, 'dropout_lstm': 0.40374701248910405, 'dropout_dense': 0.4337454969194394, 'learning_rate': 0.0002269665182891516, 'batch_size': 256}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:21:09,033] Trial 1 finished with value: 0.02109081856906414 and parameters: {'filters': 128, 'kernel_size': 3, 'lstm_units_1': 128, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.3063513298215208, 'dropout_dense': 0.3718119144476917, 'learning_rate': 0.00038717818292002126, 'batch_size': 256}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:21:09,982] Trial 5 finished with value: 0.014148710295557976 and parameters: {'filters': 128, 'kernel_size': 5, 'lstm_units_1': 256, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.22913840827432772, 'dropout_dense': 0.4654396638586844, 'learning_rate': 0.008745528884171913, 'batch_size': 256}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:21:11,713] Trial 38 finished with value: 0.5368598699569702 and parameters: {'filters': 64, 'kernel_size': 3, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 32, 'dropout_lstm': 0.35464607897780115, 'dropout_dense': 0.3323263638581817, 'learning_rate': 0.0006318664062477219, 'batch_size': 512}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:21:43,771] Trial 42 finished with value: 0.5341936349868774 and parameters: {'filters': 128, 'kernel_size': 5, 'lstm_units_1': 128, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.2731648706310272, 'dropout_dense': 0.3912103848038736, 'learning_rate': 0.00564020892287084, 'batch_size': 128}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:21:56,080] Trial 43 finished with value: 0.12119505554437637 and parameters: {'filters': 128, 'kernel_size': 5, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.190299145981417, 'dropout_dense': 0.39497478119648777, 'learning_rate': 0.009186477014811982, 'batch_size': 512}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:22:02,295] Trial 25 finished with value: 0.020015552639961243 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 32, 'lstm_units_3': 64, 'dropout_lstm': 0.4013002015570329, 'dropout_dense': 0.3563245963150094, 'learning_rate': 0.0006569268452260102, 'batch_size': 512}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:22:05,612] Trial 26 finished with value: 0.018322506919503212 and parameters: {'filters': 32, 'kernel_size': 3, 'lstm_units_1': 64, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.3737181003826078, 'dropout_dense': 0.22564463930424122, 'learning_rate': 0.004857864820379154, 'batch_size': 512}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:22:09,609] Trial 44 finished with value: 0.42766857147216797 and parameters: {'filters': 32, 'kernel_size': 5, 'lstm_units_1': 128, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.2339404650383832, 'dropout_dense': 0.26715507325254295, 'learning_rate': 0.004393524041271431, 'batch_size': 512}. Best is trial 0 with value: 0.014132257550954819.
[I 2025-03-14 04:22:12,643] Trial 28 finished with value: 0.013057021424174309 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 32, 'lstm_units_3': 64, 'dropout_lstm': 0.3954687263632784, 'dropout_dense': 0.231502974955673, 'learning_rate': 0.004079575760685706, 'batch_size': 512}. Best is trial 28 with value: 0.013057021424174309.
[I 2025-03-14 04:22:13,844] Trial 27 finished with value: 0.014274352230131626 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 32, 'lstm_units_3': 16, 'dropout_lstm': 0.3777802063343513, 'dropout_dense': 0.2234627405556665, 'learning_rate': 0.004405762310024971, 'batch_size': 512}. Best is trial 28 with value: 0.013057021424174309.
[I 2025-03-14 04:22:46,949] Trial 49 finished with value: 0.5368598699569702 and parameters: {'filters': 64, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 64, 'dropout_lstm': 0.4514375891000749, 'dropout_dense': 0.15238097019018698, 'learning_rate': 0.006295764683201052, 'batch_size': 128}. Best is trial 28 with value: 0.013057021424174309.
[I 2025-03-14 04:24:03,923] Trial 39 finished with value: 0.01818094588816166 and parameters: {'filters': 64, 'kernel_size': 3, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 64, 'dropout_lstm': 0.3441528009371757, 'dropout_dense': 0.26924022059652597, 'learning_rate': 0.0005717363899326573, 'batch_size': 512}. Best is trial 28 with value: 0.013057021424174309.
[I 2025-03-14 04:24:10,438] Trial 40 finished with value: 0.015521054156124592 and parameters: {'filters': 64, 'kernel_size': 5, 'lstm_units_1': 128, 'lstm_units_2': 32, 'lstm_units_3': 64, 'dropout_lstm': 0.3515372468086491, 'dropout_dense': 0.27365836096043517, 'learning_rate': 0.000594453241189894, 'batch_size': 512}. Best is trial 28 with value: 0.013057021424174309.
[I 2025-03-14 04:24:48,241] Trial 45 finished with value: 0.018908092752099037 and parameters: {'filters': 64, 'kernel_size': 5, 'lstm_units_1': 128, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.3050361243006181, 'dropout_dense': 0.47041208550860647, 'learning_rate': 0.004393162078338776, 'batch_size': 512}. Best is trial 28 with value: 0.013057021424174309.
[I 2025-03-14 04:24:56,442] Trial 46 finished with value: 0.01908448338508606 and parameters: {'filters': 64, 'kernel_size': 5, 'lstm_units_1': 128, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.24137997491189306, 'dropout_dense': 0.4989088215679967, 'learning_rate': 0.001432540808299998, 'batch_size': 512}. Best is trial 28 with value: 0.013057021424174309.
[I 2025-03-14 04:25:00,319] Trial 2 finished with value: 0.013489306904375553 and parameters: {'filters': 128, 'kernel_size': 2, 'lstm_units_1': 256, 'lstm_units_2': 128, 'lstm_units_3': 64, 'dropout_lstm': 0.2692458234127081, 'dropout_dense': 0.1530849667446908, 'learning_rate': 0.007118151484005409, 'batch_size': 128}. Best is trial 28 with value: 0.013057021424174309.
[I 2025-03-14 04:25:00,952] Trial 6 finished with value: 0.013196970336139202 and parameters: {'filters': 64, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 128, 'lstm_units_3': 16, 'dropout_lstm': 0.44479745240000224, 'dropout_dense': 0.15030840392804384, 'learning_rate': 0.0023282234487667203, 'batch_size': 128}. Best is trial 28 with value: 0.013057021424174309.
[I 2025-03-14 04:25:02,479] Trial 8 finished with value: 0.016023920848965645 and parameters: {'filters': 32, 'kernel_size': 5, 'lstm_units_1': 256, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.37677397636345134, 'dropout_dense': 0.2897635054113572, 'learning_rate': 0.0025353211887094522, 'batch_size': 128}. Best is trial 28 with value: 0.013057021424174309.
[I 2025-03-14 04:25:06,884] Trial 10 finished with value: 0.013992532156407833 and parameters: {'filters': 32, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 64, 'dropout_lstm': 0.35089973795609, 'dropout_dense': 0.12748131008947847, 'learning_rate': 0.0009024469132983753, 'batch_size': 128}. Best is trial 28 with value: 0.013057021424174309.
[I 2025-03-14 04:26:32,578] Trial 41 finished with value: 0.012921338900923729 and parameters: {'filters': 128, 'kernel_size': 3, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.1907120591332447, 'dropout_dense': 0.3841859555154085, 'learning_rate': 0.005337799002681695, 'batch_size': 128}. Best is trial 41 with value: 0.012921338900923729.
[I 2025-03-14 04:26:46,437] Trial 48 finished with value: 0.01619102619588375 and parameters: {'filters': 64, 'kernel_size': 4, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 64, 'dropout_lstm': 0.46124593597058083, 'dropout_dense': 0.4752756147834965, 'learning_rate': 0.007813682137730767, 'batch_size': 128}. Best is trial 41 with value: 0.012921338900923729.

Mejores hiperparámetros: {'filters': 128, 'kernel_size': 3, 'lstm_units_1': 64, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.1907120591332447, 'dropout_dense': 0.3841859555154085, 'learning_rate': 0.005337799002681695, 'batch_size': 128}

### Photovoltaic

In [42]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv1D, MaxPooling1D, Bidirectional, GRU, MultiHeadAttention
from tensorflow.keras.layers import Flatten, Dropout, Dense
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import mean_squared_error

# Definir la función objetivo para Optuna
def objective(trial):
    # Hiperparámetros a optimizar
    filters_1 = trial.suggest_categorical("filters_1", [32, 64, 128])
    filters_2 = trial.suggest_categorical("filters_2", [64, 128, 256])
    kernel_size = trial.suggest_int("kernel_size", 2, 5)
    gru_units = trial.suggest_categorical("gru_units", [32, 64, 128])
    num_heads = trial.suggest_categorical("num_heads", [2, 4, 8])
    dropout_rate = trial.suggest_float("dropout_rate", 0.2, 0.5)
    dense_units_1 = trial.suggest_categorical("dense_units_1", [32, 64, 128])
    dense_units_2 = trial.suggest_categorical("dense_units_2", [16, 32, 64])
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-4, 1e-2)
    batch_size = trial.suggest_categorical("batch_size", [128, 256, 512])

    # Definir el modelo
    inputs = Input(shape=(X_train_windowed.shape[1], X_train_windowed.shape[2]))

    # Primera capa CNN
    x = Conv1D(filters=filters_1, kernel_size=kernel_size, padding='same', activation='relu')(inputs)
    x = MaxPooling1D(pool_size=2)(x)

    # Segunda capa CNN
    x = Conv1D(filters=filters_2, kernel_size=kernel_size, padding='same', activation='relu')(x)
    x = MaxPooling1D(pool_size=2)(x)

    # Capa BiGRU
    x = Bidirectional(GRU(gru_units, return_sequences=True))(x)

    # Atención MultiHead
    attention = MultiHeadAttention(num_heads=num_heads, key_dim=128)(x, x)

    # Aplanar y Dropout
    x = Flatten()(attention)
    x = Dropout(dropout_rate)(x)
    x = Dense(dense_units_1, activation="relu", kernel_regularizer=l2(0.01))(x)
    x = Dense(dense_units_2, activation="relu")(x)

    # Capa de salida
    outputs = Dense(1, activation="linear")(x)

    # Construcción del modelo
    model = Model(inputs=inputs, outputs=outputs)

    # Compilar el modelo
    model.compile(
        loss=tf.keras.losses.MeanSquaredError(),
        optimizer=Adam(learning_rate=learning_rate),
        metrics=[tf.keras.metrics.RootMeanSquaredError()]
    )

    # Early Stopping
    early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True, verbose=1)

    # Entrenar el modelo
    history = model.fit(
        X_train_windowed, y_train_windowed,
        epochs=100,  # Se detendrá con Early Stopping
        batch_size=batch_size,
        validation_data=(X_val_windowed, y_val_windowed),
        callbacks=[early_stop],
        verbose=0
    )

    # Obtener la mejor pérdida de validación
    val_loss = min(history.history['val_loss'])
    return val_loss  # Optuna minimizará este valor

# Crear el estudio de optimización
Photovoltaic_study = optuna.create_study(direction="minimize")
Photovoltaic_study.optimize(objective, n_trials=50, n_jobs=-1)  # Ejecutar 50 pruebas

# Imprimir los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", Photovoltaic_study.best_params)

[I 2025-03-14 04:26:46,467] A new study created in memory with name: no-name-9a82c53f-95fe-4f4e-b352-bf8aff70762b

Epoch 25: early stopping
Restoring model weights from the end of the best epoch: 15.

[I 2025-03-14 04:28:36,051] Trial 6 finished with value: 0.013736714608967304 and parameters: {'filters_1': 64, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.3938452117846962, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.003771794003679529, 'batch_size': 256}. Best is trial 6 with value: 0.013736714608967304.

Epoch 74: early stopping
Restoring model weights from the end of the best epoch: 64.

[I 2025-03-14 04:29:02,955] Trial 0 finished with value: 0.016442205756902695 and parameters: {'filters_1': 32, 'filters_2': 64, 'kernel_size': 5, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.4417461483219919, 'dense_units_1': 128, 'dense_units_2': 16, 'learning_rate': 0.001184161135227899, 'batch_size': 512}. Best is trial 6 with value: 0.013736714608967304.

Epoch 52: early stopping
Restoring model weights from the end of the best epoch: 42.

[I 2025-03-14 04:29:26,175] Trial 11 finished with value: 0.014119774103164673 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.3415594335460972, 'dense_units_1': 128, 'dense_units_2': 16, 'learning_rate': 0.0011046837877007874, 'batch_size': 256}. Best is trial 6 with value: 0.013736714608967304.

Restoring model weights from the end of the best epoch: 99.

[I 2025-03-14 04:29:27,314] Trial 7 finished with value: 0.018904590979218483 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 4, 'gru_units': 128, 'num_heads': 8, 'dropout_rate': 0.3301063123695176, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.004631554458884543, 'batch_size': 512}. Best is trial 6 with value: 0.013736714608967304.

Epoch 54: early stopping
Restoring model weights from the end of the best epoch: 44.

[I 2025-03-14 04:29:30,156] Trial 5 finished with value: 0.014042828232049942 and parameters: {'filters_1': 128, 'filters_2': 64, 'kernel_size': 4, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.43140901793295766, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.0006111044427305197, 'batch_size': 256}. Best is trial 6 with value: 0.013736714608967304.

Epoch 30: early stopping
Restoring model weights from the end of the best epoch: 20.

[I 2025-03-14 04:29:36,137] Trial 2 finished with value: 0.014407294802367687 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 32, 'num_heads': 4, 'dropout_rate': 0.427847796592267, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.004051395137084854, 'batch_size': 128}. Best is trial 6 with value: 0.013736714608967304.

Epoch 64: early stopping
Restoring model weights from the end of the best epoch: 54.

[I 2025-03-14 04:29:50,248] Trial 9 finished with value: 0.016328616067767143 and parameters: {'filters_1': 32, 'filters_2': 64, 'kernel_size': 3, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.31467687375682685, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.0005711610134673786, 'batch_size': 256}. Best is trial 6 with value: 0.013736714608967304.

Epoch 44: early stopping
Restoring model weights from the end of the best epoch: 34.

[I 2025-03-14 04:30:26,192] Trial 1 finished with value: 0.014810003340244293 and parameters: {'filters_1': 64, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 4, 'dropout_rate': 0.43011690560613247, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.00043952837663361385, 'batch_size': 128}. Best is trial 6 with value: 0.013736714608967304.

Epoch 53: early stopping
Restoring model weights from the end of the best epoch: 43.

[I 2025-03-14 04:30:26,777] Trial 12 finished with value: 0.015438227914273739 and parameters: {'filters_1': 32, 'filters_2': 64, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.34418133786883287, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.0006823317824456111, 'batch_size': 256}. Best is trial 6 with value: 0.013736714608967304.

Epoch 44: early stopping
Restoring model weights from the end of the best epoch: 34.

[I 2025-03-14 04:30:28,089] Trial 4 finished with value: 0.014019908383488655 and parameters: {'filters_1': 128, 'filters_2': 256, 'kernel_size': 3, 'gru_units': 128, 'num_heads': 8, 'dropout_rate': 0.4137738821575604, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.0017872653058814592, 'batch_size': 128}. Best is trial 6 with value: 0.013736714608967304.

Epoch 51: early stopping
Restoring model weights from the end of the best epoch: 41.

[I 2025-03-14 04:30:51,075] Trial 3 finished with value: 0.01528247632086277 and parameters: {'filters_1': 32, 'filters_2': 256, 'kernel_size': 5, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.2989385773777592, 'dense_units_1': 128, 'dense_units_2': 16, 'learning_rate': 0.002104875380859376, 'batch_size': 128}. Best is trial 6 with value: 0.013736714608967304.

Epoch 80: early stopping
Restoring model weights from the end of the best epoch: 70.

[I 2025-03-14 04:31:09,563] Trial 14 finished with value: 0.014731484465301037 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 8, 'dropout_rate': 0.42770817225256696, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.0038146234273998708, 'batch_size': 512}. Best is trial 6 with value: 0.013736714608967304.

Epoch 56: early stopping
Restoring model weights from the end of the best epoch: 46.

[I 2025-03-14 04:31:13,898] Trial 10 finished with value: 0.013847937807440758 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.23346717382182, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.0002805953993625552, 'batch_size': 128}. Best is trial 6 with value: 0.013736714608967304.

Epoch 78: early stopping
Restoring model weights from the end of the best epoch: 68.

[I 2025-03-14 04:31:14,408] Trial 16 finished with value: 0.016731487587094307 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 4, 'gru_units': 128, 'num_heads': 2, 'dropout_rate': 0.20102096763396812, 'dense_units_1': 32, 'dense_units_2': 32, 'learning_rate': 0.002773532669434586, 'batch_size': 512}. Best is trial 6 with value: 0.013736714608967304.

Epoch 36: early stopping
Restoring model weights from the end of the best epoch: 26.

[I 2025-03-14 04:31:24,102] Trial 13 finished with value: 0.01421085000038147 and parameters: {'filters_1': 128, 'filters_2': 64, 'kernel_size': 4, 'gru_units': 64, 'num_heads': 2, 'dropout_rate': 0.430600553963689, 'dense_units_1': 128, 'dense_units_2': 16, 'learning_rate': 0.0036244978802332318, 'batch_size': 128}. Best is trial 6 with value: 0.013736714608967304.

Epoch 91: early stopping
Restoring model weights from the end of the best epoch: 81.

[I 2025-03-14 04:31:27,419] Trial 17 finished with value: 0.013951498083770275 and parameters: {'filters_1': 32, 'filters_2': 256, 'kernel_size': 4, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.4994665311548885, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.0017960555927558767, 'batch_size': 512}. Best is trial 6 with value: 0.013736714608967304.

Epoch 55: early stopping
Restoring model weights from the end of the best epoch: 45.

[I 2025-03-14 04:31:43,356] Trial 20 finished with value: 0.013700459152460098 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.4562748680586573, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.0037282681230435804, 'batch_size': 512}. Best is trial 20 with value: 0.013700459152460098.

Restoring model weights from the end of the best epoch: 91.

[I 2025-03-14 04:31:49,161] Trial 18 finished with value: 0.012901460751891136 and parameters: {'filters_1': 128, 'filters_2': 64, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.2547668056441918, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.0004315906506319696, 'batch_size': 512}. Best is trial 18 with value: 0.012901460751891136.

Epoch 73: early stopping
Restoring model weights from the end of the best epoch: 63.

[I 2025-03-14 04:32:05,077] Trial 15 finished with value: 0.0151910912245512 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 5, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.40387665243616877, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.006304874520515725, 'batch_size': 256}. Best is trial 18 with value: 0.012901460751891136.

Epoch 78: early stopping
Restoring model weights from the end of the best epoch: 68.

[I 2025-03-14 04:33:08,823] Trial 19 finished with value: 0.015279601328074932 and parameters: {'filters_1': 32, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.49516733725079776, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.002209563912306224, 'batch_size': 256}. Best is trial 18 with value: 0.012901460751891136.

Epoch 73: early stopping
Restoring model weights from the end of the best epoch: 63.

[I 2025-03-14 04:33:09,676] Trial 29 finished with value: 0.014537636190652847 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.2671052238751308, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.008215034582693794, 'batch_size': 512}. Best is trial 18 with value: 0.012901460751891136.

Epoch 92: early stopping
Restoring model weights from the end of the best epoch: 82.

[I 2025-03-14 04:33:15,696] Trial 8 finished with value: 0.018919920548796654 and parameters: {'filters_1': 32, 'filters_2': 256, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.3165642236916825, 'dense_units_1': 32, 'dense_units_2': 32, 'learning_rate': 0.0052980962979666405, 'batch_size': 128}. Best is trial 18 with value: 0.012901460751891136.

Epoch 42: early stopping
Restoring model weights from the end of the best epoch: 32.

[I 2025-03-14 04:33:24,953] Trial 22 finished with value: 0.014641986228525639 and parameters: {'filters_1': 64, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.2130669182725697, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.008913458481550125, 'batch_size': 128}. Best is trial 18 with value: 0.012901460751891136.

Restoring model weights from the end of the best epoch: 100.

[I 2025-03-14 04:33:51,514] Trial 21 finished with value: 0.01709338091313839 and parameters: {'filters_1': 64, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.21705347531216745, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00011844080759227755, 'batch_size': 256}. Best is trial 18 with value: 0.012901460751891136.

Restoring model weights from the end of the best epoch: 100.

[I 2025-03-14 04:33:53,153] Trial 30 finished with value: 0.03469295799732208 and parameters: {'filters_1': 128, 'filters_2': 64, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.27953407841253, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.00012119184213481326, 'batch_size': 512}. Best is trial 18 with value: 0.012901460751891136.

Epoch 92: early stopping
Restoring model weights from the end of the best epoch: 82.

[I 2025-03-14 04:34:39,805] Trial 28 finished with value: 0.01368874404579401 and parameters: {'filters_1': 64, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.38408034531222074, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.006603096036494777, 'batch_size': 256}. Best is trial 18 with value: 0.012901460751891136.

Restoring model weights from the end of the best epoch: 99.

[I 2025-03-14 04:34:44,146] Trial 26 finished with value: 0.014445400796830654 and parameters: {'filters_1': 64, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.26435579111669505, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.0001569867485066459, 'batch_size': 256}. Best is trial 18 with value: 0.012901460751891136.

Restoring model weights from the end of the best epoch: 99.

[I 2025-03-14 04:34:46,387] Trial 27 finished with value: 0.014323832467198372 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.23905398018320023, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.00017377786588375306, 'batch_size': 256}. Best is trial 18 with value: 0.012901460751891136.

Epoch 61: early stopping
Restoring model weights from the end of the best epoch: 51.

[I 2025-03-14 04:34:56,016] Trial 23 finished with value: 0.01667664386332035 and parameters: {'filters_1': 64, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.49898390288693484, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.009836892627110282, 'batch_size': 128}. Best is trial 18 with value: 0.012901460751891136.

Restoring model weights from the end of the best epoch: 100.

[I 2025-03-14 04:35:09,124] Trial 31 finished with value: 0.030108746141195297 and parameters: {'filters_1': 128, 'filters_2': 64, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.2764365307841824, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.00012932043604057348, 'batch_size': 512}. Best is trial 18 with value: 0.012901460751891136.

Restoring model weights from the end of the best epoch: 100.

[I 2025-03-14 04:35:10,313] Trial 32 finished with value: 0.023757942020893097 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.38440759313605866, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00016146304531608228, 'batch_size': 512}. Best is trial 18 with value: 0.012901460751891136.

Restoring model weights from the end of the best epoch: 100.

[I 2025-03-14 04:35:16,386] Trial 33 finished with value: 0.027379753068089485 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.38084738530987566, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00014570650198233526, 'batch_size': 512}. Best is trial 18 with value: 0.012901460751891136.

Restoring model weights from the end of the best epoch: 100.

[I 2025-03-14 04:35:22,869] Trial 34 finished with value: 0.04824499413371086 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.3845923753398277, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00010904236907637034, 'batch_size': 512}. Best is trial 18 with value: 0.012901460751891136.

Epoch 73: early stopping
Restoring model weights from the end of the best epoch: 63.

[I 2025-03-14 04:35:37,677] Trial 25 finished with value: 0.013327331282198429 and parameters: {'filters_1': 64, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.2577757802832876, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.00016121246568574475, 'batch_size': 128}. Best is trial 18 with value: 0.012901460751891136.

Restoring model weights from the end of the best epoch: 100.

[I 2025-03-14 04:35:47,665] Trial 36 finished with value: 0.01744951494038105 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.3789244363016889, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00025483597692374223, 'batch_size': 512}. Best is trial 18 with value: 0.012901460751891136.

Restoring model weights from the end of the best epoch: 97.

[I 2025-03-14 04:35:47,757] Trial 35 finished with value: 0.015722976997494698 and parameters: {'filters_1': 128, 'filters_2': 64, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.388553142588991, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.0002409152294215382, 'batch_size': 512}. Best is trial 18 with value: 0.012901460751891136.

Epoch 79: early stopping
Restoring model weights from the end of the best epoch: 69.

[I 2025-03-14 04:35:49,429] Trial 24 finished with value: 0.014986027963459492 and parameters: {'filters_1': 64, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 2, 'dropout_rate': 0.23520703598857495, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.00012952609839947185, 'batch_size': 128}. Best is trial 18 with value: 0.012901460751891136.

Epoch 55: early stopping
Restoring model weights from the end of the best epoch: 45.

[I 2025-03-14 04:36:25,290] Trial 42 finished with value: 0.016248047351837158 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 3, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.37275184415263407, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.0014524720318040798, 'batch_size': 512}. Best is trial 18 with value: 0.012901460751891136.

Restoring model weights from the end of the best epoch: 99.

[I 2025-03-14 04:36:39,197] Trial 37 finished with value: 0.015494321472942829 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.3687766752771372, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.0002940623860999111, 'batch_size': 512}. Best is trial 18 with value: 0.012901460751891136.

Restoring model weights from the end of the best epoch: 98.

[I 2025-03-14 04:36:51,761] Trial 38 finished with value: 0.015247310511767864 and parameters: {'filters_1': 128, 'filters_2': 64, 'kernel_size': 3, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.38452686767450905, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.0002663445851405149, 'batch_size': 512}. Best is trial 18 with value: 0.012901460751891136.

Restoring model weights from the end of the best epoch: 97.

[I 2025-03-14 04:36:52,643] Trial 39 finished with value: 0.02031131274998188 and parameters: {'filters_1': 128, 'filters_2': 64, 'kernel_size': 3, 'gru_units': 32, 'num_heads': 8, 'dropout_rate': 0.3786666098761982, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.0002725843089529847, 'batch_size': 512}. Best is trial 18 with value: 0.012901460751891136.

Epoch 98: early stopping
Restoring model weights from the end of the best epoch: 88.

[I 2025-03-14 04:36:53,161] Trial 40 finished with value: 0.019230784848332405 and parameters: {'filters_1': 128, 'filters_2': 64, 'kernel_size': 3, 'gru_units': 32, 'num_heads': 8, 'dropout_rate': 0.37666323498332727, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.00037327948274053354, 'batch_size': 512}. Best is trial 18 with value: 0.012901460751891136.

Epoch 47: early stopping
Restoring model weights from the end of the best epoch: 37.

[I 2025-03-14 04:36:59,169] Trial 44 finished with value: 0.014981339685618877 and parameters: {'filters_1': 64, 'filters_2': 256, 'kernel_size': 3, 'gru_units': 32, 'num_heads': 8, 'dropout_rate': 0.44957163270566564, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.0013690957276392877, 'batch_size': 256}. Best is trial 18 with value: 0.012901460751891136.

Epoch 91: early stopping
Restoring model weights from the end of the best epoch: 81.

[I 2025-03-14 04:36:59,330] Trial 41 finished with value: 0.01828049309551716 and parameters: {'filters_1': 128, 'filters_2': 64, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.37245285991467464, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.0002917964375083433, 'batch_size': 512}. Best is trial 18 with value: 0.012901460751891136.

Restoring model weights from the end of the best epoch: 96.

[I 2025-03-14 04:37:15,595] Trial 45 finished with value: 0.016396883875131607 and parameters: {'filters_1': 128, 'filters_2': 256, 'kernel_size': 3, 'gru_units': 32, 'num_heads': 8, 'dropout_rate': 0.4704270691891347, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.0002868610393612813, 'batch_size': 512}. Best is trial 18 with value: 0.012901460751891136.

Epoch 66: early stopping
Restoring model weights from the end of the best epoch: 56.

[I 2025-03-14 04:37:17,532] Trial 43 finished with value: 0.015429913997650146 and parameters: {'filters_1': 64, 'filters_2': 256, 'kernel_size': 3, 'gru_units': 32, 'num_heads': 8, 'dropout_rate': 0.4679334667065952, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.00030648763299639167, 'batch_size': 256}. Best is trial 18 with value: 0.012901460751891136.

Epoch 47: early stopping
Restoring model weights from the end of the best epoch: 37.

[I 2025-03-14 04:37:43,155] Trial 48 finished with value: 0.01559158693999052 and parameters: {'filters_1': 128, 'filters_2': 256, 'kernel_size': 3, 'gru_units': 32, 'num_heads': 8, 'dropout_rate': 0.4729495393945804, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.0003695535039880011, 'batch_size': 128}. Best is trial 18 with value: 0.012901460751891136.

Epoch 49: early stopping
Restoring model weights from the end of the best epoch: 39.

[I 2025-03-14 04:37:51,509] Trial 49 finished with value: 0.015017085708677769 and parameters: {'filters_1': 128, 'filters_2': 256, 'kernel_size': 3, 'gru_units': 32, 'num_heads': 8, 'dropout_rate': 0.4646423154365713, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.00038804060858454244, 'batch_size': 128}. Best is trial 18 with value: 0.012901460751891136.

Epoch 62: early stopping
Restoring model weights from the end of the best epoch: 52.

[I 2025-03-14 04:37:55,510] Trial 47 finished with value: 0.015617715194821358 and parameters: {'filters_1': 128, 'filters_2': 256, 'kernel_size': 3, 'gru_units': 32, 'num_heads': 8, 'dropout_rate': 0.46452907294029555, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.0003328298928570522, 'batch_size': 128}. Best is trial 18 with value: 0.012901460751891136.

Epoch 67: early stopping
Restoring model weights from the end of the best epoch: 57.

[I 2025-03-14 04:37:57,383] Trial 46 finished with value: 0.014311643317341805 and parameters: {'filters_1': 128, 'filters_2': 256, 'kernel_size': 3, 'gru_units': 32, 'num_heads': 8, 'dropout_rate': 0.4755903637807232, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.00036395514235322096, 'batch_size': 128}. Best is trial 18 with value: 0.012901460751891136.

Mejores hiperparámetros: {'filters_1': 128, 'filters_2': 64, 'kernel_size': 2, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.2547668056441918, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.0004315906506319696, 'batch_size': 512}